/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * Copyright (c) 2026 Michal Svacha
 */
package io.github.gbkt.examples.metasprites

import io.github.gbkt.backend.gbdk.codegen.pipeline.GBDKPipeline
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull

// =============================================================================
// PHASE 13.3 PLAN 22 — GRAY SUB-PALETTE COLOR-VALUE EMISSION (RED→GREEN)
//
// Locks the CORRECT slot-0 `gray_pal` RGB byte ORDER per the 13.3-21 diagnostic
// root cause (b) palette-INDEX-POLARITY (see
//   .planning/phases/13.3-…-inserted/evidence/13.3-DIAGNOSTIC.md
//   "## COLOR-VALUE root cause") and D-19 (faithful, non-inverted gray).
//
// WHY this exact order:
//   png2asset baked the elephant tile 2bpp indices in ASCENDING luminance from
//   the source PNG PLTE (index0 = transparent dark-teal, index3 = the lightest
//   body colour RGB8(224,248,207); index3 is 29.2% of pixels — the dominant
//   body). At runtime those indices select `gray_pal` (OBJ slot 0). For a
//   faithful, NON-inverted render the gray ramp must therefore ASCEND in
//   luminance too, so the index-3 body lands on the LIGHT end:
//
//       gray_pal[4] = {0x0000, 0x294A, 0x56B5, 0x7FFF}
//                      ^idx0    ^idx1    ^idx2    ^idx3
//                      (transparent key) ... outline ... BODY=light
//
//   The PRIOR (inverted) emission was {0x7FFF, 0x56B5, 0x294A, 0x0000}, which
//   mapped the light body (index3) to 0x0000 BLACK — the user's "inverted /
//   wrongly set" residual flagged at the 13.3-20 binding sign-off.
//
// This test asserts the color0..3 TOKEN ORDER (not set membership) so an
// index-polarity regression is caught. It is RED against the pre-13.3-22 codegen
// and GREEN after the Metasprites.kt gray spritePalette reorder.
// =============================================================================

class MetaspritesGrayPaletteEmissionTest {

    private fun mainC(): String {
        val output = GBDKPipeline().generate(metasprites.build())
        return assertNotNull(output.files["main.c"], "main.c not generated by GBDKPipeline")
    }

    /** Extracts the `{...}` body of the named `*_pal[4]` array literal from generated C. */
    private fun paletteLiteral(cSource: String, name: String): String {
        val regex = Regex("""${Regex.escape(name)}\[4\]\s*=\s*\{([^}]*)\}""")
        val match =
            regex.find(cSource) ?: error("Could not find $name[4] literal in generated main.c")
        return match.groupValues[1].split(",").joinToString(", ") { it.trim() }
    }

    @Test
    fun `gray_pal emits ascending-luminance ramp so the index-3 body renders light (non-inverted)`() {
        // Fix-target byte ORDER from 13.3-21 diagnostic "## COLOR-VALUE root cause" + D-19.
        val expected = "0x0000, 0x294A, 0x56B5, 0x7FFF"
        val actual = paletteLiteral(mainC(), "gray_pal")
        assertEquals(
            expected,
            actual,
            "gray_pal color0..3 ORDER must ascend in luminance (index3=light body) per the " +
                "13.3-21 index-polarity fix; an inverted/wrong order ships a luminance-inverted elephant.",
        )
    }

    // -------------------------------------------------------------------------
    // 13.3-24 — the `rot>>2` cycle palettes (pink/cyan/green) carried the SAME index-polarity
    // inversion gray had. The visible shades are swapped (color1<->color3) so the index-3 body
    // lands on the BRIGHT hue and the index-1 outline on the DARK hue (color0 = transparent key,
    // color2 unused). These assertions lock the corrected token ORDER so the colored elephants
    // cannot regress back to a dark-body / bright-outline (inverted) shading.
    // -------------------------------------------------------------------------

    @Test
    fun `pink_pal body lands on the bright magenta hue (non-inverted)`() {
        assertEquals(
            "0x7FFF, 0x280A, 0x5415, 0x7C1F",
            paletteLiteral(mainC(), "pink_pal"),
            "pink_pal index-3 body must be bright magenta (0x7C1F), index-1 outline dark (0x280A).",
        )
    }

    @Test
    fun `cyan_pal body lands on the bright cyan hue (non-inverted)`() {
        assertEquals(
            "0x7FFF, 0x2940, 0x56A0, 0x7FEA",
            paletteLiteral(mainC(), "cyan_pal"),
            "cyan_pal index-3 body must be bright cyan (0x7FEA), index-1 outline dark (0x2940).",
        )
    }

    @Test
    fun `green_pal body lands on the bright green hue (non-inverted)`() {
        assertEquals(
            "0x7FFF, 0x0140, 0x02A0, 0x57F5",
            paletteLiteral(mainC(), "green_pal"),
            "green_pal index-3 body must be bright green (0x57F5), index-1 outline dark (0x0140).",
        )
    }
}
