/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * Copyright (c) 2026 Michal Svacha
 */
package io.github.gbkt.backend.gbdk.codegen.world

import io.github.gbkt.backend.gbdk.codegen.GBDKCodeGenerator
import io.github.gbkt.backend.gbdk.codegen.core.generateStatement
import io.github.gbkt.core.exploration.Exploration
import io.github.gbkt.core.exploration.MovementStyle

// =============================================================================
// EXPLORATION CODE GENERATION
// =============================================================================

/**
 * Generate exploration system code.
 *
 * Creates:
 * - Movement state machine
 * - D-pad input handling
 * - Collision detection
 * - Gauge/key management
 * - Integration with floors and encounters
 */
/**
 * Generate global player position variables.
 *
 * These variables are always generated as they are used by the exploration system and other codegen
 * modules.
 *
 * Note: _current_zone and _current_map are generated by ZoneCodegen. We define _current_floor as an
 * alias for _current_zone for exploration compatibility.
 */
internal fun GBDKCodeGenerator.generatePlayerPositionVariables() {
    line("// =============================================================================")
    line("// PLAYER POSITION VARIABLES")
    line("// =============================================================================")
    line()
    line("// Player position (tile coordinates)")
    line("static UINT8 _player_tile_x = 0u;")
    line("static UINT8 _player_tile_y = 0u;")
    line()
    line("// Player position (pixel coordinates)")
    line("static UINT8 _player_pixel_x = 0u;")
    line("static UINT8 _player_pixel_y = 0u;")
    line()
    line("// Alias: _current_floor is an alias for _current_zone (for exploration compatibility)")
    line("#define _current_floor _current_zone")
    line()
}

internal fun GBDKCodeGenerator.generateExplorationSystem() {
    val explorations = game.explorations
    if (explorations.isEmpty()) return

    line("// =============================================================================")
    line("// EXPLORATION SYSTEM")
    line("// =============================================================================")
    line()

    // Generate movement state constants
    generateMovementStateConstants()

    // Generate each exploration system
    for (exploration in explorations) {
        generateExplorationDefinition(exploration)
    }
}

/** Generate movement state constants. */
private fun GBDKCodeGenerator.generateMovementStateConstants() {
    line("// Movement states")
    line("#define MOVE_IDLE 0u")
    line("#define MOVE_WALKING 1u")
    line("#define MOVE_BLOCKED 2u")
    line("#define MOVE_INTERACTING 3u")
    line("#define MOVE_TRANSITIONING 4u")
    line()

    line("// Movement directions")
    line("#define DIR_NONE 0u")
    line("#define DIR_UP 1u")
    line("#define DIR_DOWN 2u")
    line("#define DIR_LEFT 3u")
    line("#define DIR_RIGHT 4u")
    line()

    line("// Map states (for textbox display, etc.)")
    line("#define MAP_STATE_EXPLORING 0u")
    line("#define MAP_STATE_TEXTBOX 1u")
    line("#define MAP_STATE_MENU 2u")
    line("#define MAP_STATE_TRANSITION 3u")
    line()

    line("// Map textbox system variables")
    line("static UINT8 _map_state = MAP_STATE_EXPLORING;")
    line("static const char* _map_textbox_message = NULL;")
    line("static UINT8 _map_textbox_auto_dismiss = 0u;")
    line()
}

/** Generate exploration system definition. */
private fun GBDKCodeGenerator.generateExplorationDefinition(exploration: Exploration) {
    val name = exploration.id
    val nameUpper = name.uppercase()

    line("// -----------------------------------------------------------------------------")
    line("// Exploration System: $name")
    line("// -----------------------------------------------------------------------------")
    line()

    // Generate constants
    generateExplorationConstants(exploration)

    // Generate state variables
    generateExplorationVariables(exploration)

    // Generate gauge/key management
    if (exploration.gauges.isNotEmpty()) {
        generateGaugeSystem(exploration)
    }
    if (exploration.keys.isNotEmpty()) {
        generateKeySystem(exploration)
    }

    // Generate collision checking (must be before movement functions which use it)
    generateCollisionCheck(exploration)

    // Generate movement functions
    generateMovementFunctions(exploration)

    // Generate update function
    generateExplorationUpdate(exploration)

    // Generate helper functions
    generateExplorationHelpers(exploration)
}

/** Generate exploration constants. */
private fun GBDKCodeGenerator.generateExplorationConstants(exploration: Exploration) {
    val nameUpper = exploration.id.uppercase()

    line("// ${exploration.id} constants")
    line("#define ${nameUpper}_TILE_SIZE ${exploration.tileSize}u")
    line("#define ${nameUpper}_MOVE_SPEED ${exploration.movementSpeed}u")
    line("#define ${nameUpper}_WALL_COLLISION ${if (exploration.wallCollisionEnabled) 1 else 0}u")
    line("#define ${nameUpper}_WATER_BLOCKS ${if (exploration.waterBlocks) 1 else 0}u")
    line("#define ${nameUpper}_PIT_DAMAGE ${exploration.pitDamage}u")

    if (exploration.movementStyle == MovementStyle.GRID) {
        line("#define ${nameUpper}_GRID_MOVEMENT 1u")
    } else {
        line("#define ${nameUpper}_GRID_MOVEMENT 0u")
    }
    line()
}

/** Generate exploration state variables. */
private fun GBDKCodeGenerator.generateExplorationVariables(exploration: Exploration) {
    val name = exploration.id

    line("// ${name} state variables")
    line("static UINT8 _${name}_move_state = MOVE_IDLE;")
    line("static UINT8 _${name}_move_dir = DIR_NONE;")
    line("static UINT8 _${name}_move_timer = 0u;")
    line("static UINT8 _${name}_target_x = 0u;")
    line("static UINT8 _${name}_target_y = 0u;")
    line("static UINT8 _${name}_facing = DIR_DOWN;")
    line("static UINT8 _${name}_active = 0u;")
    line()
}

/** Generate gauge management system. */
private fun GBDKCodeGenerator.generateGaugeSystem(exploration: Exploration) {
    val name = exploration.id
    val nameUpper = name.uppercase()

    line("// ${name} resource gauges")

    for ((index, gauge) in exploration.gauges.withIndex()) {
        val gaugeId = gauge.id
        val gaugeUpper = gaugeId.uppercase()

        line("#define ${nameUpper}_GAUGE_${gaugeUpper} ${index}u")
        line("#define ${nameUpper}_GAUGE_${gaugeUpper}_MAX ${gauge.maxValue}u")
        line("static UINT16 _${name}_gauge_${gaugeId} = ${gauge.initialValue}u;")

        if (gauge.lowThreshold > 0) {
            line("#define ${nameUpper}_GAUGE_${gaugeUpper}_LOW ${gauge.lowThreshold}u")
            line("static UINT8 _${name}_gauge_${gaugeId}_was_low = 0u;")
        }
    }
    line()

    // Generate gauge update function
    line("// Update gauges (call on step)")
    line("static void _${name}_update_gauges_on_step(void) {")
    indent++

    for (gauge in exploration.gauges) {
        val gaugeId = gauge.id
        val gaugeUpper = gaugeId.uppercase()

        if (gauge.decrementPerStep > 0) {
            line("// Decrement ${gaugeId}")
            line("if (_${name}_gauge_${gaugeId} >= ${gauge.decrementPerStep}u) {")
            indent++
            line("_${name}_gauge_${gaugeId} -= ${gauge.decrementPerStep}u;")
            indent--
            line("} else if (_${name}_gauge_${gaugeId} > 0u) {")
            indent++
            line("_${name}_gauge_${gaugeId} = 0u;")

            // Call on-depleted callback if present
            if (gauge.onDepletedStatements.isNotEmpty()) {
                line("// Gauge depleted callback")
                for (stmt in gauge.onDepletedStatements) {
                    generateStatement(stmt)
                }
            }

            indent--
            line("}")

            // Check low threshold
            if (gauge.lowThreshold > 0 && gauge.onLowStatements.isNotEmpty()) {
                line("// Check low threshold")
                line(
                    "if (_${name}_gauge_${gaugeId} <= ${nameUpper}_GAUGE_${gaugeUpper}_LOW && !_${name}_gauge_${gaugeId}_was_low) {"
                )
                indent++
                line("_${name}_gauge_${gaugeId}_was_low = 1u;")
                for (stmt in gauge.onLowStatements) {
                    generateStatement(stmt)
                }
                indent--
                line("}")
            }
        }
    }

    indent--
    line("}")
    line()

    // Generate gauge frame update if any have per-frame decrement
    val frameDecrementGauges = exploration.gauges.filter { it.decrementPerFrame > 0 }
    if (frameDecrementGauges.isNotEmpty()) {
        line("// Update gauges (call per frame)")
        line("static void _${name}_update_gauges_frame(void) {")
        indent++

        for (gauge in frameDecrementGauges) {
            val gaugeId = gauge.id
            line("if (_${name}_gauge_${gaugeId} >= ${gauge.decrementPerFrame}u) {")
            indent++
            line("_${name}_gauge_${gaugeId} -= ${gauge.decrementPerFrame}u;")
            indent--
            line("}")
        }

        indent--
        line("}")
        line()
    }

    // Generate gauge getter/setter helpers
    line("// Get gauge value")
    line("static UINT16 _${name}_get_gauge(UINT8 gauge_id) {")
    indent++
    line("switch (gauge_id) {")
    indent++
    for ((index, gauge) in exploration.gauges.withIndex()) {
        line("case ${index}u: return _${name}_gauge_${gauge.id};")
    }
    line("default: return 0u;")
    indent--
    line("}")
    indent--
    line("}")
    line()

    line("// Set gauge value")
    line("static void _${name}_set_gauge(UINT8 gauge_id, UINT16 value) {")
    indent++
    line("switch (gauge_id) {")
    indent++
    for ((index, gauge) in exploration.gauges.withIndex()) {
        val gaugeUpper = gauge.id.uppercase()
        line(
            "case ${index}u: _${name}_gauge_${gauge.id} = (value > ${name.uppercase()}_GAUGE_${gaugeUpper}_MAX) ? ${name.uppercase()}_GAUGE_${gaugeUpper}_MAX : value; break;"
        )
    }
    indent--
    line("}")
    indent--
    line("}")
    line()
}

/** Generate key/collectible management system. */
private fun GBDKCodeGenerator.generateKeySystem(exploration: Exploration) {
    val name = exploration.id
    val nameUpper = name.uppercase()

    line("// ${name} keys/collectibles")

    for ((index, key) in exploration.keys.withIndex()) {
        val keyId = key.id
        val keyUpper = keyId.uppercase()

        line("#define ${nameUpper}_KEY_${keyUpper} ${index}u")
        line("#define ${nameUpper}_KEY_${keyUpper}_MAX ${key.maxCount}u")
        line("static UINT8 _${name}_key_${keyId} = ${key.initialCount}u;")
    }
    line()

    // Generate key helpers
    line("// Add key")
    line("static void _${name}_add_key(UINT8 key_id, UINT8 count) {")
    indent++
    line("switch (key_id) {")
    indent++
    for ((index, key) in exploration.keys.withIndex()) {
        val keyUpper = key.id.uppercase()
        line("case ${index}u:")
        indent++
        line("_${name}_key_${key.id} += count;")
        line(
            "if (_${name}_key_${key.id} > ${nameUpper}_KEY_${keyUpper}_MAX) _${name}_key_${key.id} = ${nameUpper}_KEY_${keyUpper}_MAX;"
        )
        line("break;")
        indent--
    }
    indent--
    line("}")
    indent--
    line("}")
    line()

    line("// Use key (returns 1 if successful, 0 if not enough)")
    line("static UINT8 _${name}_use_key(UINT8 key_id) {")
    indent++
    line("switch (key_id) {")
    indent++
    for ((index, key) in exploration.keys.withIndex()) {
        line("case ${index}u:")
        indent++
        line("if (_${name}_key_${key.id} > 0u) { _${name}_key_${key.id}--; return 1u; }")
        line("return 0u;")
        indent--
    }
    line("default: return 0u;")
    indent--
    line("}")
    indent--
    line("}")
    line()

    line("// Get key count")
    line("static UINT8 _${name}_get_key(UINT8 key_id) {")
    indent++
    line("switch (key_id) {")
    indent++
    for ((index, key) in exploration.keys.withIndex()) {
        line("case ${index}u: return _${name}_key_${key.id};")
    }
    line("default: return 0u;")
    indent--
    line("}")
    indent--
    line("}")
    line()
}

/** Generate movement functions. */
private fun GBDKCodeGenerator.generateMovementFunctions(exploration: Exploration) {
    val name = exploration.id
    val nameUpper = name.uppercase()

    line("// Start movement in a direction")
    line("static void _${name}_start_move(UINT8 direction) {")
    indent++
    line("if (_${name}_move_state != MOVE_IDLE) return;")
    line()
    line("INT16 new_x = (INT16)_player_tile_x;")
    line("INT16 new_y = (INT16)_player_tile_y;")
    line()
    line("switch (direction) {")
    indent++
    line("case DIR_UP: new_y--; break;")
    line("case DIR_DOWN: new_y++; break;")
    line("case DIR_LEFT: new_x--; break;")
    line("case DIR_RIGHT: new_x++; break;")
    line("default: return;")
    indent--
    line("}")
    line()
    line("// Update facing direction")
    line("_${name}_facing = direction;")
    line()
    line("// Bounds check")
    line("if (new_x < 0 || new_y < 0) {")
    indent++
    line("_${name}_move_state = MOVE_BLOCKED;")
    if (exploration.onBlockedStatements.isNotEmpty()) {
        for (stmt in exploration.onBlockedStatements) {
            generateStatement(stmt)
        }
    }
    line("_${name}_move_state = MOVE_IDLE;")
    line("return;")
    indent--
    line("}")
    line()
    line("// Collision check")
    line("UINT8 attr = _${name}_get_tile_attr((UINT8)new_x, (UINT8)new_y);")
    line("if (${nameUpper}_WALL_COLLISION && attr == TILE_WALL) {")
    indent++
    line("_${name}_move_state = MOVE_BLOCKED;")
    if (exploration.onBlockedStatements.isNotEmpty()) {
        for (stmt in exploration.onBlockedStatements) {
            generateStatement(stmt)
        }
    }
    line("_${name}_move_state = MOVE_IDLE;")
    line("return;")
    indent--
    line("}")
    line()
    line("// Water check")
    line("if (${nameUpper}_WATER_BLOCKS && attr == TILE_WATER) {")
    indent++
    if (exploration.onWaterStatements.isNotEmpty()) {
        for (stmt in exploration.onWaterStatements) {
            generateStatement(stmt)
        }
    }
    line("return;")
    indent--
    line("}")
    line()
    line("// Start movement")
    line("_${name}_target_x = (UINT8)new_x;")
    line("_${name}_target_y = (UINT8)new_y;")
    line("_${name}_move_dir = direction;")
    line("_${name}_move_state = MOVE_WALKING;")
    line("_${name}_move_timer = ${nameUpper}_MOVE_SPEED;")

    indent--
    line("}")
    line()
}

/** Generate collision check function. */
private fun GBDKCodeGenerator.generateCollisionCheck(exploration: Exploration) {
    val name = exploration.id

    line("// Get tile attribute at position")
    line("static UINT8 _${name}_get_tile_attr(UINT8 tx, UINT8 ty) {")
    indent++
    line("// Delegate to floor system's tile attribute lookup")
    line("// This requires floor system to be generated first")

    // Check if we have zones with tile attributes defined
    if (game.zones.any { zone -> zone.maps.values.any { it.tileAttributes.isNotEmpty() } }) {
        line("switch (_current_floor) {")
        indent++
        for (zone in game.zones) {
            val mapsWithAttrs = zone.maps.filter { it.value.tileAttributes.isNotEmpty() }
            if (mapsWithAttrs.isNotEmpty()) {
                line("case ${zone.zoneIndex}u: {")
                indent++
                line("switch (_current_map) {")
                indent++
                for ((mapIndex, entry) in mapsWithAttrs.entries.withIndex()) {
                    val (mapName, _) = entry
                    line("case ${zone.maps.keys.indexOf(mapName)}u: {")
                    indent++
                    line(
                        "UINT8 tile = ${zone.id}_${mapName}_data[ty * ${zone.id.uppercase()}_MAP_${mapName.uppercase()}_WIDTH + tx];"
                    )
                    line("return ${zone.id}_${mapName}_get_tile_attr(tile);")
                    indent--
                    line("}")
                }
                line("default: return TILE_GROUND;")
                indent--
                line("}")
                indent--
                line("}")
            }
        }
        line("default: return TILE_GROUND;")
        indent--
        line("}")
    } else {
        line("(void)tx; (void)ty;")
        line("return TILE_GROUND;")
    }

    indent--
    line("}")
    line()
}

/** Generate exploration update function. */
private fun GBDKCodeGenerator.generateExplorationUpdate(exploration: Exploration) {
    val name = exploration.id
    val nameUpper = name.uppercase()

    line("// Main exploration update (call once per frame)")
    line("static void _${name}_update(void) {")
    indent++
    line("if (!_${name}_active) return;")
    line()

    // Movement state machine
    line("switch (_${name}_move_state) {")
    indent++

    // IDLE state - check input
    line("case MOVE_IDLE: {")
    indent++
    line("// Check D-pad input")
    line("UINT8 keys = joypad();")
    line("if (keys & J_UP) _${name}_start_move(DIR_UP);")
    line("else if (keys & J_DOWN) _${name}_start_move(DIR_DOWN);")
    line("else if (keys & J_LEFT) _${name}_start_move(DIR_LEFT);")
    line("else if (keys & J_RIGHT) _${name}_start_move(DIR_RIGHT);")
    line()
    line("// Check interact button")
    line("if (keys & J_A) {")
    indent++
    if (exploration.onInteractStatements.isNotEmpty()) {
        for (stmt in exploration.onInteractStatements) {
            generateStatement(stmt)
        }
    } else {
        line("// No interact callback defined")
    }
    indent--
    line("}")
    line("break;")
    indent--
    line("}")

    // WALKING state - animate movement
    line("case MOVE_WALKING: {")
    indent++
    line("if (_${name}_move_timer > 0u) {")
    indent++
    line("_${name}_move_timer--;")
    line()

    if (exploration.movementStyle == MovementStyle.SMOOTH) {
        line("// Smooth movement - interpolate pixel position")
        line("// Progress: 0 at start of move (timer=MOVE_SPEED) to 1 at end (timer=0)")
        line(
            "// Pixel position = start_tile_pixels + (direction * (MOVE_SPEED - timer) * TILE_SIZE) / MOVE_SPEED"
        )
        line("UINT8 _progress = ${nameUpper}_MOVE_SPEED - _${name}_move_timer;")
        line("switch (_${name}_move_dir) {")
        indent++
        line("case DIR_UP:")
        indent++
        line(
            "_player_pixel_y = (_player_tile_y * ${nameUpper}_TILE_SIZE) - (_progress * ${nameUpper}_TILE_SIZE / ${nameUpper}_MOVE_SPEED);"
        )
        line("break;")
        indent--
        line("case DIR_DOWN:")
        indent++
        line(
            "_player_pixel_y = (_player_tile_y * ${nameUpper}_TILE_SIZE) + (_progress * ${nameUpper}_TILE_SIZE / ${nameUpper}_MOVE_SPEED);"
        )
        line("break;")
        indent--
        line("case DIR_LEFT:")
        indent++
        line(
            "_player_pixel_x = (_player_tile_x * ${nameUpper}_TILE_SIZE) - (_progress * ${nameUpper}_TILE_SIZE / ${nameUpper}_MOVE_SPEED);"
        )
        line("break;")
        indent--
        line("case DIR_RIGHT:")
        indent++
        line(
            "_player_pixel_x = (_player_tile_x * ${nameUpper}_TILE_SIZE) + (_progress * ${nameUpper}_TILE_SIZE / ${nameUpper}_MOVE_SPEED);"
        )
        line("break;")
        indent--
        indent--
        line("}")

        // Update player sprite position if configured
        exploration.playerSprite?.let { sprite ->
            line("// Update player sprite position")
            line("move_sprite(${sprite.oamSlot}, _player_pixel_x + 8, _player_pixel_y + 16);")
        }
    }

    indent--
    line("} else {")
    indent++
    line("// Movement complete - update tile position")
    line("_player_tile_x = _${name}_target_x;")
    line("_player_tile_y = _${name}_target_y;")
    line("// Update pixel position to final tile position")
    line("_player_pixel_x = _player_tile_x * ${nameUpper}_TILE_SIZE;")
    line("_player_pixel_y = _player_tile_y * ${nameUpper}_TILE_SIZE;")

    // Update player sprite position if configured
    exploration.playerSprite?.let { sprite ->
        line("// Update player sprite to final position")
        line("move_sprite(${sprite.oamSlot}, _player_pixel_x + 8, _player_pixel_y + 16);")
    }

    line("_${name}_move_state = MOVE_IDLE;")
    line("_${name}_move_dir = DIR_NONE;")
    line()

    // Check for special tiles
    line("// Check tile attribute at new position")
    line("UINT8 attr = _${name}_get_tile_attr(_player_tile_x, _player_tile_y);")
    line()
    line("// Handle exit tiles")
    line("if (attr == TILE_EXIT) {")
    indent++
    line("floor_check_exits();")
    indent--
    line("}")
    line()

    // Handle pit tiles
    if (exploration.pitDamage > 0) {
        line("// Handle pit tiles")
        line("if (attr == TILE_PIT) {")
        indent++
        if (exploration.onPitStatements.isNotEmpty()) {
            for (stmt in exploration.onPitStatements) {
                generateStatement(stmt)
            }
        } else {
            line("// Default pit damage")
            line("// hero_hp -= ${nameUpper}_PIT_DAMAGE;")
        }
        indent--
        line("}")
    }

    // Update gauges on step
    if (exploration.gauges.any { it.decrementPerStep > 0 }) {
        line()
        line("// Update gauges on step")
        line("_${name}_update_gauges_on_step();")
    }

    // Call encounter check
    if (game.encounterTables.isNotEmpty() || game.zones.any { it.encounterTable != null }) {
        line()
        line("// Check for random encounter")
        line("UINT8 enc = encounter_check_step();")
        line("if (enc != 255u) {")
        indent++
        if (exploration.onStepStatements.isNotEmpty()) {
            line("// Custom encounter handling")
            for (stmt in exploration.onStepStatements) {
                generateStatement(stmt)
            }
        } else {
            line("// Start battle with encounter entry")
            line("_pending_encounter_table = _encounter_table_id;")
            line("_pending_encounter_entry = enc;")
            line("_pending_encounter_valid = 1u;")

            // Find battle scene for transition
            val battleScene =
                game.scenes.values.find { it.name.contains("battle", ignoreCase = true) }
            if (battleScene != null) {
                line("_next_scene = SCENE_${battleScene.name.uppercase()};")
            } else {
                // Default to SCENE_BATTLE, may need manual adjustment
                line("_next_scene = SCENE_BATTLE;")
            }
            line("_scene_changed = 1u;")
        }
        indent--
        line("}")
    } else if (exploration.onStepStatements.isNotEmpty()) {
        line()
        line("// On step callback")
        for (stmt in exploration.onStepStatements) {
            generateStatement(stmt)
        }
    }

    indent--
    line("}")
    line("break;")
    indent--
    line("}")

    // BLOCKED state - handled in start_move
    line("case MOVE_BLOCKED:")
    line("case MOVE_INTERACTING:")
    line("case MOVE_TRANSITIONING:")
    indent++
    line("// These states are transient or handled elsewhere")
    line("break;")
    indent--

    indent--
    line("}")

    // Per-frame gauge update
    val frameDecrementGauges = exploration.gauges.filter { it.decrementPerFrame > 0 }
    if (frameDecrementGauges.isNotEmpty()) {
        line()
        line("// Per-frame gauge updates")
        line("_${name}_update_gauges_frame();")
    }

    indent--
    line("}")
    line()
}

/** Generate exploration helper functions. */
private fun GBDKCodeGenerator.generateExplorationHelpers(exploration: Exploration) {
    val name = exploration.id
    val nameUpper = name.uppercase()

    line("// Enable exploration system")
    line("static void _${name}_enable(void) {")
    indent++
    line("_${name}_active = 1u;")
    line("_${name}_move_state = MOVE_IDLE;")
    indent--
    line("}")
    line()

    line("// Disable exploration system")
    line("static void _${name}_disable(void) {")
    indent++
    line("_${name}_active = 0u;")
    indent--
    line("}")
    line()

    line("// Spawn player at position")
    line("static void _${name}_spawn(UINT8 x, UINT8 y) {")
    indent++
    line("_player_tile_x = x;")
    line("_player_tile_y = y;")
    line("// Initialize pixel position from tile position")
    line("_player_pixel_x = x * ${nameUpper}_TILE_SIZE;")
    line("_player_pixel_y = y * ${nameUpper}_TILE_SIZE;")
    line("_${name}_target_x = x;")
    line("_${name}_target_y = y;")
    line("_${name}_move_state = MOVE_IDLE;")
    line("_${name}_move_dir = DIR_NONE;")
    indent--
    line("}")
    line()

    line("// Get player facing direction")
    line("static UINT8 _${name}_get_facing(void) {")
    indent++
    line("return _${name}_facing;")
    indent--
    line("}")
    line()

    line("// Check if player is moving")
    line("static UINT8 _${name}_is_moving(void) {")
    indent++
    line("return (_${name}_move_state == MOVE_WALKING) ? 1u : 0u;")
    indent--
    line("}")
    line()
}
