// Generated by gbkt
#pragma bank 1

#include <stdio.h>
#include <gbdk/console.h>
#include "game.h"

// Scene: gameover
void gameover_enter(void) BANKED {
    HIDE_SPRITES;
    cls();
    {
        gotoxy(6u, 5u);
        printf("GAME OVER");
    }
    {
        gotoxy(5u, 8u);
        printf("P1:%d    P2:%d", _p1Score, _p2Score);
    }
    {
        gotoxy(5u, 13u);
        printf("PRESS START");
    }
}

void gameover_frame(void) BANKED {
    if (button_pressed(J_START)) {
        _p1Score = 0u;
        _p2Score = 0u;
        navigate_to_scene(SCENE_TITLE);
    }
}

// Scene: game
void game_enter(void) BANKED {
    cls();
    SHOW_SPRITES;
    {
        _ball_x = 80u;
        _ball_y = 72u;
    }
    _ballDx = 1u;
    _ballDy = 1u;
    _p1Score = 0u;
    _p2Score = 0u;
    {
        gotoxy(5u, 1u);
        printf("P1:%d    P2:%d", _p1Score, _p2Score);
    }
}

void game_frame(void) BANKED {
    if (button_held(J_UP)) {
        if (_paddle1_y > 16u) {
            {
                _paddle1_y += -2;
            }
        }
    }
    if (button_held(J_DOWN)) {
        if (_paddle1_y < 112u) {
            {
                _paddle1_y += 2u;
            }
        }
    }
    if (_paddle2_y + 8u > _ball_y) {
        if (_paddle2_y > 16u) {
            {
                _paddle2_y += -2;
            }
        }
    }
    if (_paddle2_y + 8u < _ball_y) {
        if (_paddle2_y < 112u) {
            {
                _paddle2_y += 2u;
            }
        }
    }
    _ball_x += _ballDx;
    _ball_y += _ballDy;
    if (_ball_y < 16u) {
        _ballDy = 1u;
        play_sound_bounceSfx();
    }
    if (_ball_y > 120u) {
        _ballDy = -1;
        play_sound_bounceSfx();
    }
    if (_ball_x < 8u) {
        if (_ball_x >= 2u) {
            if (_ball_y >= _paddle1_y) {
                if (_ball_y < _paddle1_y + 16u) {
                    _ballDx = 1u;
                    play_sound_bounceSfx();
                }
            }
        }
    }
    if (_ball_x > 148u) {
        if (_ball_x < 156u) {
            if (_ball_y >= _paddle2_y) {
                if (_ball_y < _paddle2_y + 16u) {
                    _ballDx = -1;
                    play_sound_bounceSfx();
                }
            }
        }
    }
    if (_ball_x < 2u) {
        _p2Score += 1u;
        play_sound_scoreSfx();
        HIDE_SPRITES;
        {
            gotoxy(5u, 1u);
            printf("P1:%d    P2:%d", _p1Score, _p2Score);
        }
        {
            gotoxy(2u, 9u);
            printf("     SCORE!     ");
        }
        delay_frames(30u);
        {
            gotoxy(2u, 9u);
            printf("                ");
        }
        {
            _ball_x = 80u;
            _ball_y = 72u;
        }
        _ballDx = 1u;
        SHOW_SPRITES;
    }
    if (_ball_x > 156u) {
        _p1Score += 1u;
        play_sound_scoreSfx();
        HIDE_SPRITES;
        {
            gotoxy(5u, 1u);
            printf("P1:%d    P2:%d", _p1Score, _p2Score);
        }
        {
            gotoxy(2u, 9u);
            printf("     SCORE!     ");
        }
        delay_frames(30u);
        {
            gotoxy(2u, 9u);
            printf("                ");
        }
        {
            _ball_x = 80u;
            _ball_y = 72u;
        }
        _ballDx = -1;
        SHOW_SPRITES;
    }
    if (_p1Score >= 5u) {
        play_sound_winSfx();
        navigate_to_scene(SCENE_GAMEOVER);
    }
    if (_p2Score >= 5u) {
        play_sound_winSfx();
        navigate_to_scene(SCENE_GAMEOVER);
    }
}

// Scene: title
void title_enter(void) BANKED {
    HIDE_SPRITES;
    cls();
    {
        gotoxy(8u, 7u);
        printf("PONG");
    }
    {
        gotoxy(5u, 10u);
        printf("PRESS START");
    }
    {
        gotoxy(5u, 13u);
        printf("FIRST TO 5");
    }
}

void title_frame(void) BANKED {
    if (button_pressed(J_START)) {
        navigate_to_scene(SCENE_GAME);
    }
}
