// Generated by gbkt

#include <gb/gb.h>
#include <stdio.h>
#include <stdlib.h>
#include <gbdk/console.h>
#include "game.h"
#include "sprites/paddle.h"
#include "sprites/ball.h"

#define SCENE_GAMEOVER 0
#define SCENE_GAME 1
#define SCENE_TITLE 2

UINT8 _paddle1_x = 0u;
UINT8 _paddle1_y = 64u;
UINT8 _paddle2_x = 152u;
UINT8 _paddle2_y = 64u;
UINT8 _ball_x = 80u;
UINT8 _ball_y = 72u;
UINT8 _p1Score = 0u;
UINT8 _p2Score = 0u;
INT8 _ballDx = 1u;
INT8 _ballDy = 1u;
UINT8 __joypad = 0u;
UINT8 __joypad_prev = 0u;
UINT8 _sound_channels[4] = {0xFF, 0xFF, 0xFF, 0xFF};
UINT8 _sound_priority[4] = {0, 0, 0, 0};
UINT8 _sound_duration[4] = {0, 0, 0, 0};
UINT8 _dialog_speed = 1u;
UINT8 current_scene = SCENE_TITLE;
UINT8 _wait_counter = 0u;
UINT8 _current_tileset_id = 0xFF;

// Input helpers (joypad polling with edge detection)
void update_joypad(void) {
    __joypad_prev = __joypad;
    __joypad = joypad();
}

UINT8 button_pressed(UINT8 mask) {
    return __joypad & mask & ~(__joypad_prev & mask);
}

UINT8 button_held(UINT8 mask) {
    return __joypad & mask;
}

/* Deduplicated: see button_held */

/* Deduplicated: see button_pressed */

UINT8 button_released(UINT8 mask) {
    return (~__joypad & mask) & __joypad_prev & mask;
}

/* Deduplicated: see button_released */

UINT8 dpad_any(void) {
    return __joypad & (J_UP|J_DOWN|J_LEFT|J_RIGHT);
}

// Timing helpers (blocking busy-wait)
void delay_frames(UINT8 n) {
    UINT8 _d;
    for (; _d < n; _d++) {
        wait_vbl_done();
    }
}

// Sprite helpers (real OAM management)
void hide_sprites_range(UINT8 from, UINT8 to) {
    UINT8 i;
    for (i = from; i < to; i++) {
        move_sprite(i, 0, 0);
    }
}

void show_sprites_range(UINT8 from, UINT8 to) {
    // Sprites shown by moving to valid positions via update_sprites()
}

// Sprite OAM sync (called every frame)
void update_sprites(void) {
    move_sprite(0u, _paddle1_x + 8u, _paddle1_y + 16u);
    move_sprite(1u, _paddle1_x + 8u, _paddle1_y + 24u);
    move_sprite(2u, _paddle2_x + 8u, _paddle2_y + 16u);
    move_sprite(3u, _paddle2_x + 8u, _paddle2_y + 24u);
    move_sprite(4u, _ball_x + 8u, _ball_y + 16u);
}

// Sound driver (channel allocation with priority preemption)
void sound_driver_update(void) {
    UINT8 ch;
    for (ch = 0u; ch < 4u; ch++) {
        if (_sound_duration[ch] > 0u) {
            --_sound_duration[ch];
            if (_sound_duration[ch] == 0u) {
                _sound_channels[ch] = 255u;
            }
        }
    }
}

void play_sound(UINT8 sound_id, UINT8 channel, UINT8 priority, UINT8 duration) {
    if (_sound_duration[channel] == 0u || priority >= _sound_priority[channel]) {
        _sound_channels[channel] = sound_id;
        _sound_priority[channel] = priority;
        _sound_duration[channel] = duration;
    }
}

void play_sound_bounceSfx(void) {
    NR41_REG = 0x00u;
    NR42_REG = 0xF2u;
    NR43_REG = 0x40u;
    NR44_REG = 0x80u;
}

void play_sound_scoreSfx(void) {
    NR10_REG = 0x00u;
    NR11_REG = 0x94u;
    NR12_REG = 0xE1u;
    NR13_REG = 0x6Cu;
    NR14_REG = 0xC7u;
}

void play_sound_winSfx(void) {
    NR10_REG = 0x00u;
    NR11_REG = 0x80u;
    NR12_REG = 0xF2u;
    NR13_REG = 0xAEu;
    NR14_REG = 0x87u;
}

// Dialog helpers (window layer rendering)
void _win_print_at(UINT8 x, UINT8 y, const UINT8* str, UINT8 len) {
    UINT8 i = 0u;
    for (; i < len; i++) {
        set_win_tiles(x + i, y, 1u, 1u, (unsigned char*)&str[i]);
    }
}

void _win_clear_region(UINT8 x, UINT8 y, UINT8 w, UINT8 h) {
    UINT8 ry = 0u;
    UINT8 rx = 0u;
    UINT8 blank = 0u;
    for (; ry < h; ry++) {
        for (; rx < w; rx++) {
            set_win_tiles(x + rx, y + ry, 1u, 1u, &blank);
        }
    }
}

void _win_fill_screen(UINT8 tile) {
    UINT8 fy = 0u;
    UINT8 fx = 0u;
    for (; fy < 18u; fy++) {
        for (; fx < 20u; fx++) {
            set_win_tiles(fx, fy, 1u, 1u, &tile);
        }
    }
}

// Fade helpers (palette-based screen fade)
void fade_out(void) {
    BGP_REG = 180u;
    OBP0_REG = 180u;
    wait_vbl_done();
    BGP_REG = 108u;
    OBP0_REG = 108u;
    wait_vbl_done();
    BGP_REG = 36u;
    OBP0_REG = 36u;
    wait_vbl_done();
    BGP_REG = 0u;
    OBP0_REG = 0u;
    wait_vbl_done();
}

void fade_in(void) {
    BGP_REG = 36u;
    OBP0_REG = 36u;
    wait_vbl_done();
    BGP_REG = 108u;
    OBP0_REG = 108u;
    wait_vbl_done();
    BGP_REG = 180u;
    OBP0_REG = 180u;
    wait_vbl_done();
    BGP_REG = 228u;
    OBP0_REG = 228u;
    wait_vbl_done();
}

// Trampoline: gameover_enter (bank 1)
void gameover_enter_trampoline(void) {
    gameover_enter();
}

void gameover_frame_trampoline(void) {
    gameover_frame();
}

// Trampoline: game_enter (bank 1)
void game_enter_trampoline(void) {
    game_enter();
}

void game_frame_trampoline(void) {
    game_frame();
}

// Trampoline: title_enter (bank 1)
void title_enter_trampoline(void) {
    title_enter();
}

void title_frame_trampoline(void) {
    title_frame();
}

// Scene navigation
void navigate_to_scene(UINT8 scene) {
    current_scene = scene;
    switch (scene) {
    case SCENE_GAMEOVER:
        gameover_enter_trampoline();
        break;
    case SCENE_GAME:
        game_enter_trampoline();
        break;
    case SCENE_TITLE:
        title_enter_trampoline();
        break;
    }
}

// Entry point
void main(void) {
    NR52_REG = 128u;
    NR50_REG = 119u;
    NR51_REG = 255u;
    DISPLAY_ON;
    SHOW_BKG;
    SHOW_SPRITES;
    set_sprite_data(0u, 2u, sprites_paddle_tiles);
    set_sprite_data(2u, 2u, sprites_paddle_tiles);
    set_sprite_data(4u, 1u, sprites_ball_tiles);
    set_sprite_tile(0u, 0u);
    move_sprite(0u, _paddle1_x + 8u, _paddle1_y + 16u);
    set_sprite_tile(1u, 1u);
    move_sprite(1u, _paddle1_x + 8u, _paddle1_y + 24u);
    set_sprite_tile(2u, 2u);
    move_sprite(2u, _paddle2_x + 8u, _paddle2_y + 16u);
    set_sprite_tile(3u, 3u);
    move_sprite(3u, _paddle2_x + 8u, _paddle2_y + 24u);
    set_sprite_tile(4u, 4u);
    move_sprite(4u, _ball_x + 8u, _ball_y + 16u);
    title_enter_trampoline();
    while (1) {
        update_joypad();
        switch (current_scene) {
        case SCENE_GAMEOVER:
            gameover_frame_trampoline();
            break;
        case SCENE_GAME:
            game_frame_trampoline();
            break;
        case SCENE_TITLE:
            title_frame_trampoline();
            break;
        }
        update_sprites();
        sound_driver_update();
        wait_vbl_done();
    }
    return;
}
