//AUTOGENERATED FILE FROM png2asset
// Conversion args: checker.png -o checker.c -map -spr8x8 -bpp 2 -noflip

#ifndef METASPRITE_checker_H
#define METASPRITE_checker_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define checker_TILE_ORIGIN 0
#define checker_TILE_W 8
#define checker_TILE_H 8
#define checker_WIDTH 16
#define checker_HEIGHT 16
#define checker_TILE_COUNT 2
#define checker_PALETTE_COUNT 1
#define checker_COLORS_PER_PALETTE 4
#define checker_TOTAL_COLORS 4
#define checker_MAP_ATTRIBUTES 0
extern const unsigned char checker_map[4];
#define checker_map_attributes checker_map

BANKREF_EXTERN(checker)

extern const palette_color_t checker_palettes[4];
extern const uint8_t checker_tiles[32];

#endif
