//AUTOGENERATED FILE FROM png2asset
// Conversion args: oversized.png -o oversized.c -map -spr8x8 -bpp 2 -noflip

#ifndef METASPRITE_oversized_H
#define METASPRITE_oversized_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define oversized_TILE_ORIGIN 0
#define oversized_TILE_W 8
#define oversized_TILE_H 8
#define oversized_WIDTH 256
#define oversized_HEIGHT 256
#define oversized_TILE_COUNT 1
#define oversized_PALETTE_COUNT 1
#define oversized_COLORS_PER_PALETTE 4
#define oversized_TOTAL_COLORS 4
#define oversized_MAP_ATTRIBUTES 0
extern const unsigned char oversized_map[1024];
#define oversized_map_attributes oversized_map

BANKREF_EXTERN(oversized)

extern const palette_color_t oversized_palettes[4];
extern const uint8_t oversized_tiles[16];

#endif
