// Generated by gbkt
#pragma bank 1

#include <stdio.h>
#include <gbdk/console.h>
#include "game.h"

// Scene: gameover
void gameover_enter(void) BANKED {
    HIDE_SPRITES;
    cls();
    {
        gotoxy(5u, 5u);
        printf("GAME OVER");
    }
    {
        gotoxy(5u, 8u);
        printf("SCORE: %d", _score);
    }
    {
        gotoxy(5u, 13u);
        printf("PRESS START");
    }
}

void gameover_frame(void) BANKED {
    if (button_pressed(J_START)) {
        _score = 0u;
        _lives = 3u;
        navigate_to_scene(SCENE_TITLE);
    }
}

// Scene: gameplay
void gameplay_enter(void) BANKED {
    cls();
    SHOW_SPRITES;
    _score = 0u;
    _lives = 3u;
    _scrollY = 0u;
    _shootCooldown = 0u;
    _waveTimer = 0u;
    {
        _player_x = 80u;
        _player_y = 120u;
    }
    {
        UINT8 i;
        for (i = 0u; i < 8u; i++) {
            if (_pool_bulletPool_active[i] != 0u) {
                move_sprite(_pool_bulletPool_oam[i], 0u, 0u);
            }
            _pool_bulletPool_active[i] = 0u;
        }
    }
    {
        UINT8 i;
        for (i = 0u; i < 4u; i++) {
            if (_pool_enemyPool_active[i] != 0u) {
                move_sprite(_pool_enemyPool_oam[i], 0u, 0u);
                move_sprite(_pool_enemyPool_oam[i] + 1u, 0u, 0u);
                move_sprite(_pool_enemyPool_oam[i] + 2u, 0u, 0u);
                move_sprite(_pool_enemyPool_oam[i] + 3u, 0u, 0u);
            }
            _pool_enemyPool_active[i] = 0u;
        }
    }
    {
        gotoxy(0u, 0u);
        printf("SC:%d LV:%d", _score, _lives);
    }
}

void gameplay_frame(void) BANKED {
    _scrollY += 1u;
    if (button_held(J_UP)) {
        if (_player_y > 8u) {
            {
                _player_y += -2;
            }
        }
    }
    if (button_held(J_DOWN)) {
        if (_player_y < 128u) {
            {
                _player_y += 2u;
            }
        }
    }
    if (button_held(J_LEFT)) {
        if (_player_x > 4u) {
            {
                _player_x += -2;
            }
        }
    }
    if (button_held(J_RIGHT)) {
        if (_player_x < 140u) {
            {
                _player_x += 2u;
            }
        }
    }
    if (button_pressed(J_A)) {
        if (_shootCooldown == 0u) {
            pool_bulletPool_spawn(_player_x, _player_y);
            _shootCooldown = 8u;
            play_sound_shootSfx();
        }
    }
    if (_shootCooldown > 0u) {
        _shootCooldown -= 1u;
    }
    {
        UINT8 _bi;
        for (_bi = 0u; _bi < 8u; _bi++) {
            if (_pool_bulletPool_active[_bi]) {
                _pool_bulletPool_y[_bi] -= 4u;
                if (_pool_bulletPool_y[_bi] < 4u) {
                    pool_bulletPool_destroy(_bi);
                }
                if (_pool_bulletPool_active[_bi]) {
                    move_sprite(_pool_bulletPool_oam[_bi], _pool_bulletPool_x[_bi] + 8u, _pool_bulletPool_y[_bi] + 16u);
                }
            }
        }
    }
    _waveTimer += 1u;
    if (_waveTimer >= 60u) {
        pool_enemyPool_spawn(80u, 0u);
        _waveTimer = 0u;
    }
    {
        UINT8 _ei;
        for (_ei = 0u; _ei < 4u; _ei++) {
            if (_pool_enemyPool_active[_ei]) {
                _pool_enemyPool_y[_ei] += 1u;
                if (_pool_enemyPool_y[_ei] > 144u) {
                    pool_enemyPool_destroy(_ei);
                }
                if (_pool_enemyPool_active[_ei]) {
                    move_sprite(_pool_enemyPool_oam[_ei], _pool_enemyPool_x[_ei] + 8u, _pool_enemyPool_y[_ei] + 16u);
                    move_sprite(_pool_enemyPool_oam[_ei] + 1u, _pool_enemyPool_x[_ei] + 16u, _pool_enemyPool_y[_ei] + 16u);
                    move_sprite(_pool_enemyPool_oam[_ei] + 2u, _pool_enemyPool_x[_ei] + 8u, _pool_enemyPool_y[_ei] + 24u);
                    move_sprite(_pool_enemyPool_oam[_ei] + 3u, _pool_enemyPool_x[_ei] + 16u, _pool_enemyPool_y[_ei] + 24u);
                }
            }
        }
    }
    {
        UINT8 _pool_bi;
        for (_pool_bi = 0u; _pool_bi < 8u; _pool_bi++) {
            if (_pool_bulletPool_active[_pool_bi]) {
                UINT8 _pool_ei;
                for (_pool_ei = 0u; _pool_ei < 4u; _pool_ei++) {
                    if (_pool_enemyPool_active[_pool_ei]) {
                        if (_pool_bulletPool_x[_pool_bi] < _pool_enemyPool_x[_pool_ei] + 16u && _pool_bulletPool_x[_pool_bi] + 4u > _pool_enemyPool_x[_pool_ei] && _pool_bulletPool_y[_pool_bi] < _pool_enemyPool_y[_pool_ei] + 16u && _pool_bulletPool_y[_pool_bi] + 8u > _pool_enemyPool_y[_pool_ei]) {
                            _score += 10u;
                            pool_bulletPool_destroy(_pool_bi);
                            pool_enemyPool_destroy(_pool_ei);
                            play_sound_explodeSfx();
                            play_sound_scoreSfx();
                            {
                                gotoxy(0u, 0u);
                                printf("SC:%d LV:%d", _score, _lives);
                            }
                        }
                    }
                }
            }
        }
    }
    {
        UINT8 _pool_ei;
        for (_pool_ei = 0u; _pool_ei < 4u; _pool_ei++) {
            if (_pool_enemyPool_active[_pool_ei]) {
                if (_pool_enemyPool_x[_pool_ei] < _player_x + 12u && _pool_enemyPool_x[_pool_ei] + 16u > _player_x && _pool_enemyPool_y[_pool_ei] < _player_y + 16u && _pool_enemyPool_y[_pool_ei] + 16u > _player_y) {
                    _lives -= 1u;
                    play_sound_hitSfx();
                    {
                        gotoxy(0u, 0u);
                        printf("SC:%d LV:%d", _score, _lives);
                    }
                    if (_lives == 0u) {
                        navigate_to_scene(SCENE_GAMEOVER);
                    }
                }
            }
        }
    }
}

// Scene: title
void title_enter(void) BANKED {
    HIDE_SPRITES;
    cls();
    {
        gotoxy(7u, 6u);
        printf("SHMUP");
    }
    {
        gotoxy(5u, 9u);
        printf("SHOOT-EM-UP");
    }
    {
        gotoxy(5u, 13u);
        printf("PRESS START");
    }
}

void title_frame(void) BANKED {
    if (button_pressed(J_START)) {
        navigate_to_scene(SCENE_GAMEPLAY);
    }
}
