// Generated by gbkt
#ifndef GAME_H
#define GAME_H

#include <gb/gb.h>
#include <stdio.h>
#include <gbdk/console.h>

#define SCENE_GAMEOVER 0
#define SCENE_GAMEPLAY 1
#define SCENE_TITLE 2

extern UINT8 _bullet_x;
extern UINT8 _bullet_y;
extern UINT8 _enemy_x;
extern UINT8 _enemy_y;
extern UINT8 _player_x;
extern UINT8 _player_y;
extern UINT8 _score;
extern UINT8 _lives;
extern UINT8 _scrollY;
extern UINT8 _shootCooldown;
extern UINT8 _waveTimer;
extern UINT8 __joypad;
extern UINT8 __joypad_prev;
extern UINT8 _sound_channels[4];
extern UINT8 _sound_priority[4];
extern UINT8 _sound_duration[4];
extern UINT8 current_scene;
extern UINT8 _wait_counter;
extern UINT8 _pool_bulletPool_active[8];
extern UINT8 _pool_bulletPool_x[8];
extern UINT8 _pool_bulletPool_y[8];
extern UINT8 _pool_bulletPool_oam[8];
extern UINT8 _pool_enemyPool_active[4];
extern UINT8 _pool_enemyPool_x[4];
extern UINT8 _pool_enemyPool_y[4];
extern UINT8 _pool_enemyPool_oam[4];
extern UINT8 _dialog_speed;
extern UINT8 _current_tileset_id;

// Scene: gameover
void gameover_enter(void) BANKED;

void gameover_frame(void) BANKED;

// Scene: gameplay
void gameplay_enter(void) BANKED;

void gameplay_frame(void) BANKED;

// Scene: title
void title_enter(void) BANKED;

void title_frame(void) BANKED;

// Input helpers (joypad polling with edge detection)
void update_joypad(void);

UINT8 button_pressed(UINT8 mask);

UINT8 button_held(UINT8 mask);

UINT8 button_held(UINT8 mask);

UINT8 button_pressed(UINT8 mask);

UINT8 button_released(UINT8 mask);

UINT8 button_released(UINT8 mask);

UINT8 dpad_any(void);

// Timing helpers (blocking busy-wait)
void delay_frames(UINT8 n);

// Sprite helpers (real OAM management)
void hide_sprites_range(UINT8 from, UINT8 to);

void show_sprites_range(UINT8 from, UINT8 to);

// Sprite OAM sync (called every frame)
void update_sprites(void);

// Sound driver (channel allocation with priority preemption)
void sound_driver_update(void);

void play_sound(UINT8 sound_id, UINT8 channel, UINT8 priority, UINT8 duration);

void play_sound_explodeSfx(void);

void play_sound_hitSfx(void);

void play_sound_scoreSfx(void);

void play_sound_shootSfx(void);

// Dialog helpers (window layer rendering)
void _win_print_at(UINT8 x, UINT8 y, const UINT8* str, UINT8 len);

void _win_clear_region(UINT8 x, UINT8 y, UINT8 w, UINT8 h);

void _win_fill_screen(UINT8 tile);

// Fade helpers (palette-based screen fade)
void fade_out(void);

void fade_in(void);

// Actor pool: bulletPool (max=8, oamBase=9, tilesPerEntity=1)
void pool_bulletPool_init(void);

UINT8 pool_bulletPool_spawn(UINT8 x, UINT8 y);

void pool_bulletPool_destroy(UINT8 i);

// Actor pool active count: bulletPool
UINT8 pool_bulletPool_active_count(void);

// Actor pool: enemyPool (max=4, oamBase=17, tilesPerEntity=4)
void pool_enemyPool_init(void);

UINT8 pool_enemyPool_spawn(UINT8 x, UINT8 y);

void pool_enemyPool_destroy(UINT8 i);

// Actor pool active count: enemyPool
UINT8 pool_enemyPool_active_count(void);

// Trampoline: gameover_enter (bank 1)
void gameover_enter_trampoline(void);

void gameover_frame_trampoline(void);

// Trampoline: gameplay_enter (bank 1)
void gameplay_enter_trampoline(void);

void gameplay_frame_trampoline(void);

// Trampoline: title_enter (bank 1)
void title_enter_trampoline(void);

void title_frame_trampoline(void);

// Scene navigation
void navigate_to_scene(UINT8 scene);

#endif // GAME_H
