// Generated by gbkt

#include <gb/gb.h>
#include <stdio.h>
#include <stdlib.h>
#include <gbdk/console.h>
#include "game.h"
#include "_zone__screen_title_tileset.h"

#define SCENE_TITLE 0
#define TILESET__SCREEN_TITLE 1

UINT8 __joypad = 0u;
UINT8 __joypad_prev = 0u;
UINT8 _sound_channels[4] = {0xFF, 0xFF, 0xFF, 0xFF};
UINT8 _sound_priority[4] = {0, 0, 0, 0};
UINT8 _sound_duration[4] = {0, 0, 0, 0};
UINT8 _dialog_speed = 1u;
UINT8 current_scene = SCENE_TITLE;
UINT8 _wait_counter = 0u;
UINT8 _current_tileset_id = 0xFF;

// Input helpers (joypad polling with edge detection)
void update_joypad(void) {
    __joypad_prev = __joypad;
    __joypad = joypad();
}

UINT8 button_pressed(UINT8 mask) {
    return __joypad & mask & ~(__joypad_prev & mask);
}

UINT8 button_held(UINT8 mask) {
    return __joypad & mask;
}

UINT8 dpad_held(UINT8 mask) {
    return __joypad & mask;
}

UINT8 dpad_pressed(UINT8 mask) {
    return __joypad & mask & ~(__joypad_prev & mask);
}

UINT8 button_released(UINT8 mask) {
    return (~__joypad & mask) & __joypad_prev & mask;
}

UINT8 dpad_released(UINT8 mask) {
    return (~__joypad & mask) & __joypad_prev & mask;
}

UINT8 dpad_any(void) {
    return __joypad & (J_UP|J_DOWN|J_LEFT|J_RIGHT);
}

// Timing helpers (blocking busy-wait)
void delay_frames(UINT8 n) {
    UINT8 _d = 0u;
    for (; _d < n; _d++) {
        wait_vbl_done();
    }
}

// Sprite helpers (real OAM management)
void hide_sprites_range(UINT8 from, UINT8 to) {
    UINT8 i;
    for (i = from; i < to; i++) {
        move_sprite(i, 0, 0);
    }
}

void show_sprites_range(UINT8 from, UINT8 to) {
    (void)from;
    (void)to;
    // Sprites shown by moving to valid positions via update_sprites()
}

// Sprite OAM sync (called every frame)
void update_sprites(void) {
}

// Sound driver (channel allocation with priority preemption)
void sound_driver_update(void) {
    UINT8 ch;
    for (ch = 0u; ch < 4u; ch++) {
        if (_sound_duration[ch] > 0u) {
            --_sound_duration[ch];
            if (_sound_duration[ch] == 0u) {
                _sound_channels[ch] = 255u;
            }
        }
    }
}

void play_sound(UINT8 sound_id, UINT8 channel, UINT8 priority, UINT8 duration) {
    if (_sound_duration[channel] == 0u || priority >= _sound_priority[channel]) {
        _sound_channels[channel] = sound_id;
        _sound_priority[channel] = priority;
        _sound_duration[channel] = duration;
    }
}

// Dialog helpers (window layer rendering)
void _win_print_at(UINT8 x, UINT8 y, const UINT8* str, UINT8 len) {
    UINT8 i = 0u;
    for (; i < len; i++) {
        set_win_tiles(x + i, y, 1u, 1u, (unsigned char*)&str[i]);
    }
}

void _win_clear_region(UINT8 x, UINT8 y, UINT8 w, UINT8 h) {
    UINT8 ry = 0u;
    UINT8 rx = 0u;
    UINT8 blank = 0u;
    for (; ry < h; ry++) {
        for (; rx < w; rx++) {
            set_win_tiles(x + rx, y + ry, 1u, 1u, &blank);
        }
    }
}

void _win_fill_screen(UINT8 tile) {
    UINT8 fy = 0u;
    UINT8 fx = 0u;
    for (; fy < 18u; fy++) {
        for (; fx < 20u; fx++) {
            set_win_tiles(fx, fy, 1u, 1u, &tile);
        }
    }
}

// Fade helpers (palette-based screen fade)
void fade_out(void) {
    BGP_REG = 180u;
    OBP0_REG = 180u;
    wait_vbl_done();
    BGP_REG = 108u;
    OBP0_REG = 108u;
    wait_vbl_done();
    BGP_REG = 36u;
    OBP0_REG = 36u;
    wait_vbl_done();
    BGP_REG = 0u;
    OBP0_REG = 0u;
    wait_vbl_done();
}

void fade_in(void) {
    BGP_REG = 36u;
    OBP0_REG = 36u;
    wait_vbl_done();
    BGP_REG = 108u;
    OBP0_REG = 108u;
    wait_vbl_done();
    BGP_REG = 180u;
    OBP0_REG = 180u;
    wait_vbl_done();
    BGP_REG = 228u;
    OBP0_REG = 228u;
    wait_vbl_done();
}

// Plan 07.4-30 / D-N-SWITCHROM-RESTORE: HOME-bank SWITCH_ROM wrapper
void _bkg_tiles_load_banked(UINT8 bank, UINT8 x, UINT8 y, UINT8 w, UINT8 h, const UINT8* tiles) {
    SWITCH_ROM(bank);
    set_bkg_tiles(x, y, w, h, tiles);
    SWITCH_ROM(1);
}

// Scene navigation
void navigate_to_scene(UINT8 scene) {
    current_scene = scene;
    switch (scene) {
    case SCENE_TITLE:
        title_enter();
        break;
    }
}

// Entry point
void main(void) {
    DISPLAY_OFF;
    NR52_REG = 128u;
    NR50_REG = 119u;
    NR51_REG = 255u;
    SHOW_BKG;
    SHOW_SPRITES;
    DISPLAY_ON;
    title_enter();
    while (1) {
        update_joypad();
        switch (current_scene) {
        }
        update_sprites();
        sound_driver_update();
        wait_vbl_done();
    }
}
