// Generated by gbkt
#ifndef GAME_H
#define GAME_H

#include <gb/gb.h>
#include <stdio.h>
#include <gbdk/console.h>

#define SCENE_WIN 0
#define SCENE_GAMEPLAY 1
#define SCENE_TITLE 2

extern UINT8 _player_x;
extern UINT8 _player_y;
extern UINT8 _lives;
extern UINT8 __joypad;
extern UINT8 __joypad_prev;
extern UINT8 _sound_channels[4];
extern UINT8 _sound_priority[4];
extern UINT8 _sound_duration[4];
extern UINT8 current_scene;
extern UINT8 _wait_counter;
extern INT8 _player_vx;
extern INT8 _player_vy;
extern INT8 _plat_vy;
extern UINT8 _plat_grounded;
extern UINT8 _plat_coyote_timer;
extern UINT8 _plat_jump_buffer;
extern INT8 _cam_x;
extern INT8 _cam_y;
extern INT8 _cam_target_x;
extern INT8 _cam_target_y;
extern UINT8 _dialog_speed;
extern UINT8 _current_tileset_id;

// Scene: win
void win_enter(void) BANKED;

void win_frame(void) BANKED;

// Scene: gameplay
void gameplay_enter(void) BANKED;

void gameplay_frame(void) BANKED;

// Scene: title
void title_enter(void) BANKED;

void title_frame(void) BANKED;

// Input helpers (joypad polling with edge detection)
void update_joypad(void);

UINT8 button_pressed(UINT8 mask);

UINT8 button_held(UINT8 mask);

UINT8 button_held(UINT8 mask);

UINT8 button_pressed(UINT8 mask);

UINT8 button_released(UINT8 mask);

UINT8 button_released(UINT8 mask);

UINT8 dpad_any(void);

// Timing helpers (blocking busy-wait)
void delay_frames(UINT8 n);

// Sprite helpers (real OAM management)
void hide_sprites_range(UINT8 from, UINT8 to);

void show_sprites_range(UINT8 from, UINT8 to);

// Sprite OAM sync (called every frame)
void update_sprites(void);

// Per-actor movement: player (PHYSICS, speed=2)
void update_movement_player(void);

// Sound driver (channel allocation with priority preemption)
void sound_driver_update(void);

void play_sound(UINT8 sound_id, UINT8 channel, UINT8 priority, UINT8 duration);

void play_sound_jumpSfx(void);

void play_sound_landSfx(void);

void play_sound_winSfx(void);

// Dialog helpers (window layer rendering)
void _win_print_at(UINT8 x, UINT8 y, const UINT8* str, UINT8 len);

void _win_clear_region(UINT8 x, UINT8 y, UINT8 w, UINT8 h);

void _win_fill_screen(UINT8 tile);

// Fade helpers (palette-based screen fade)
void fade_out(void);

void fade_in(void);

// Platformer physics update
void platformer_physics_update(void);

// Platformer camera update (smooth_follow)
void platformer_camera_update(void);

// Platformer platform collision: ground
void check_platform_collision_ground(UINT8 player_x, UINT8 player_y);

// Platformer platform collision: mid_platform
void check_platform_collision_mid_platform(UINT8 player_x, UINT8 player_y);

// Platformer platform collision: high_platform
void check_platform_collision_high_platform(UINT8 player_x, UINT8 player_y);

// Platformer goal reached callback
void on_goal_reached(void);

// Platformer goal zone check: exit
void check_goal_zone_exit(UINT8 player_x, UINT8 player_y);

// Trampoline: win_enter (bank 1)
void win_enter_trampoline(void);

void win_frame_trampoline(void);

// Trampoline: gameplay_enter (bank 1)
void gameplay_enter_trampoline(void);

void gameplay_frame_trampoline(void);

// Trampoline: title_enter (bank 1)
void title_enter_trampoline(void);

void title_frame_trampoline(void);

// Scene navigation
void navigate_to_scene(UINT8 scene);

#endif // GAME_H
