// Generated by gbkt

#include <gb/gb.h>
#include <stdio.h>
#include <stdlib.h>
#include <gbdk/console.h>
#include "game.h"
#include "sprites/player.h"

#define SCENE_WIN 0
#define SCENE_GAMEPLAY 1
#define SCENE_TITLE 2
#define ACCEL_X_PLAYER 0
#define ACCEL_Y_PLAYER 0
#define GRAVITY_PLAYER 0
#define MAX_FALL_PLAYER 8
#define BOUNCE_PLAYER 0

UINT8 _player_x = 20u;
UINT8 _player_y = 104u;
INT8 _player_vx = 0u;
INT8 _player_vy = 0u;
UINT8 _lives = 3u;
UINT8 __joypad = 0u;
UINT8 __joypad_prev = 0u;
UINT8 _sound_channels[4] = {0xFF, 0xFF, 0xFF, 0xFF};
UINT8 _sound_priority[4] = {0, 0, 0, 0};
UINT8 _sound_duration[4] = {0, 0, 0, 0};
INT8 _plat_vy = 0u;
UINT8 _plat_grounded = 0u;
UINT8 _plat_coyote_timer = 0u;
UINT8 _plat_jump_buffer = 0u;
INT8 _cam_x = 0u;
INT8 _cam_y = 0u;
INT8 _cam_target_x = 0u;
INT8 _cam_target_y = 0u;
UINT8 _dialog_speed = 1u;
UINT8 current_scene = SCENE_TITLE;
UINT8 _wait_counter = 0u;
UINT8 _current_tileset_id = 0xFF;

// Input helpers (joypad polling with edge detection)
void update_joypad(void) {
    __joypad_prev = __joypad;
    __joypad = joypad();
}

UINT8 button_pressed(UINT8 mask) {
    return __joypad & mask & ~(__joypad_prev & mask);
}

UINT8 button_held(UINT8 mask) {
    return __joypad & mask;
}

/* Deduplicated: see button_held */

/* Deduplicated: see button_pressed */

UINT8 button_released(UINT8 mask) {
    return (~__joypad & mask) & __joypad_prev & mask;
}

/* Deduplicated: see button_released */

UINT8 dpad_any(void) {
    return __joypad & (J_UP|J_DOWN|J_LEFT|J_RIGHT);
}

// Timing helpers (blocking busy-wait)
void delay_frames(UINT8 n) {
    UINT8 _d;
    for (; _d < n; _d++) {
        wait_vbl_done();
    }
}

// Sprite helpers (real OAM management)
void hide_sprites_range(UINT8 from, UINT8 to) {
    UINT8 i;
    for (i = from; i < to; i++) {
        move_sprite(i, 0, 0);
    }
}

void show_sprites_range(UINT8 from, UINT8 to) {
    // Sprites shown by moving to valid positions via update_sprites()
}

// Sprite OAM sync (called every frame)
void update_sprites(void) {
    move_sprite(0u, _player_x + 8u, _player_y + 16u);
    move_sprite(1u, _player_x + 8u, _player_y + 24u);
}

// Per-actor movement: player (PHYSICS, speed=2)
void update_movement_player(void) {
    if (button_held(J_LEFT)) {
        _player_vx -= ACCEL_X_PLAYER;
    }
    if (button_held(J_RIGHT)) {
        _player_vx += ACCEL_X_PLAYER;
    }
    if (button_held(J_UP)) {
        _player_vy -= ACCEL_Y_PLAYER;
    }
    if (button_held(J_DOWN)) {
        _player_vy += ACCEL_Y_PLAYER;
    }
    _player_x += (UINT8)_player_vx;
    _player_y += (UINT8)_player_vy;
}

// Sound driver (channel allocation with priority preemption)
void sound_driver_update(void) {
    UINT8 ch;
    for (ch = 0u; ch < 4u; ch++) {
        if (_sound_duration[ch] > 0u) {
            --_sound_duration[ch];
            if (_sound_duration[ch] == 0u) {
                _sound_channels[ch] = 255u;
            }
        }
    }
}

void play_sound(UINT8 sound_id, UINT8 channel, UINT8 priority, UINT8 duration) {
    if (_sound_duration[channel] == 0u || priority >= _sound_priority[channel]) {
        _sound_channels[channel] = sound_id;
        _sound_priority[channel] = priority;
        _sound_duration[channel] = duration;
    }
}

void play_sound_jumpSfx(void) {
    NR41_REG = 0x00u;
    NR42_REG = 0xF2u;
    NR43_REG = 0x40u;
    NR44_REG = 0x80u;
}

void play_sound_landSfx(void) {
    NR41_REG = 0x00u;
    NR42_REG = 0x81u;
    NR43_REG = 0x68u;
    NR44_REG = 0x80u;
}

void play_sound_winSfx(void) {
    NR10_REG = 0x00u;
    NR11_REG = 0x80u;
    NR12_REG = 0xF2u;
    NR13_REG = 0xAEu;
    NR14_REG = 0x87u;
}

// Dialog helpers (window layer rendering)
void _win_print_at(UINT8 x, UINT8 y, const UINT8* str, UINT8 len) {
    UINT8 i = 0u;
    for (; i < len; i++) {
        set_win_tiles(x + i, y, 1u, 1u, (unsigned char*)&str[i]);
    }
}

void _win_clear_region(UINT8 x, UINT8 y, UINT8 w, UINT8 h) {
    UINT8 ry = 0u;
    UINT8 rx = 0u;
    UINT8 blank = 0u;
    for (; ry < h; ry++) {
        for (; rx < w; rx++) {
            set_win_tiles(x + rx, y + ry, 1u, 1u, &blank);
        }
    }
}

void _win_fill_screen(UINT8 tile) {
    UINT8 fy = 0u;
    UINT8 fx = 0u;
    for (; fy < 18u; fy++) {
        for (; fx < 20u; fx++) {
            set_win_tiles(fx, fy, 1u, 1u, &tile);
        }
    }
}

// Fade helpers (palette-based screen fade)
void fade_out(void) {
    BGP_REG = 180u;
    OBP0_REG = 180u;
    wait_vbl_done();
    BGP_REG = 108u;
    OBP0_REG = 108u;
    wait_vbl_done();
    BGP_REG = 36u;
    OBP0_REG = 36u;
    wait_vbl_done();
    BGP_REG = 0u;
    OBP0_REG = 0u;
    wait_vbl_done();
}

void fade_in(void) {
    BGP_REG = 36u;
    OBP0_REG = 36u;
    wait_vbl_done();
    BGP_REG = 108u;
    OBP0_REG = 108u;
    wait_vbl_done();
    BGP_REG = 180u;
    OBP0_REG = 180u;
    wait_vbl_done();
    BGP_REG = 228u;
    OBP0_REG = 228u;
    wait_vbl_done();
}

// Platformer physics update
void platformer_physics_update(void) {
    // Apply gravity
    if (_plat_vy < 12u) {
        _plat_vy += 2u;
    }

    // Decrement coyote timer
    if (_plat_coyote_timer > 0u) {
        --_plat_coyote_timer;
    }

    // Decrement jump buffer
    if (_plat_jump_buffer > 0u) {
        --_plat_jump_buffer;
    }

    // Jump input: set coyote or buffer
    if (button_pressed(J_A)) {
        if (_plat_grounded || _plat_coyote_timer > 0u) {
            _plat_vy = -8;
            _plat_grounded = 0u;
            _plat_coyote_timer = 0u;
        } else {
            _plat_jump_buffer = 8u;
        }
    }

    // Variable-height jump: cut velocity when button released early
    if (button_released(J_A) && _plat_vy < 0u) {
        _plat_vy /= 2u;
    }

    // Set coyote time when on ground, let it expire when airborne
    if (_plat_grounded != 0u) {
        _plat_coyote_timer = 6u;
    }

    // Apply jump buffer on landing
    if (_plat_grounded == 1u && _plat_jump_buffer > 0u) {
        _plat_vy = -8;
        _plat_grounded = 0u;
        _plat_jump_buffer = 0u;
    }
}

// Platformer camera update (smooth_follow)
void platformer_camera_update(void) {
    // Smooth-follow camera with dead zone (16x8)

    // Horizontal dead-zone check
    if (abs(_cam_target_x - _cam_x) > 16u) {
        if (_cam_target_x > _cam_x) {
            _cam_x = _cam_target_x - 16u;
        } else {
            _cam_x = _cam_target_x + 16u;
        }
    }

    // Vertical dead-zone check
    if (abs(_cam_target_y - _cam_y) > 8u) {
        if (_cam_target_y > _cam_y) {
            _cam_y = _cam_target_y - 8u;
        } else {
            _cam_y = _cam_target_y + 8u;
        }
    }

    // Apply camera scroll
    move_bkg(_cam_x, _cam_y);
}

// Platformer platform collision: ground
void check_platform_collision_ground(UINT8 player_x, UINT8 player_y) {
    // Platform collision: ground (type=SOLID)
    // Solid platform: block all directions
    _plat_vy = 0u;
    _plat_grounded = 1u;
}

// Platformer platform collision: mid_platform
void check_platform_collision_mid_platform(UINT8 player_x, UINT8 player_y) {
    // Platform collision: mid_platform (type=ONE_WAY)
    // One-way: only block when player is falling from above
    if (_plat_vy > 0u) {
        // Player falling — resolve solid collision
        _plat_vy = 0u;
        _plat_grounded = 1u;
    }
}

// Platformer platform collision: high_platform
void check_platform_collision_high_platform(UINT8 player_x, UINT8 player_y) {
    // Platform collision: high_platform (type=ONE_WAY)
    // One-way: only block when player is falling from above
    if (_plat_vy > 0u) {
        // Player falling — resolve solid collision
        _plat_vy = 0u;
        _plat_grounded = 1u;
    }
}

// Platformer goal reached callback
void on_goal_reached(void) {
    // Goal reached — game handles navigation in scene frame
}

// Platformer goal zone check: exit
void check_goal_zone_exit(UINT8 player_x, UINT8 player_y) {
    // AABB check: player vs goal zone exit (112,40 16x16)
    if (player_x >= 112u && player_x < 128u && player_y >= 40u && player_y < 56u) {
        on_goal_reached();
    }
}

// Trampoline: win_enter (bank 1)
void win_enter_trampoline(void) {
    win_enter();
}

void win_frame_trampoline(void) {
    win_frame();
}

// Trampoline: gameplay_enter (bank 1)
void gameplay_enter_trampoline(void) {
    gameplay_enter();
}

void gameplay_frame_trampoline(void) {
    gameplay_frame();
}

// Trampoline: title_enter (bank 1)
void title_enter_trampoline(void) {
    title_enter();
}

void title_frame_trampoline(void) {
    title_frame();
}

// Scene navigation
void navigate_to_scene(UINT8 scene) {
    current_scene = scene;
    switch (scene) {
    case SCENE_WIN:
        win_enter_trampoline();
        break;
    case SCENE_GAMEPLAY:
        gameplay_enter_trampoline();
        break;
    case SCENE_TITLE:
        title_enter_trampoline();
        break;
    }
}

// Entry point
void main(void) {
    NR52_REG = 128u;
    NR50_REG = 119u;
    NR51_REG = 255u;
    DISPLAY_ON;
    SHOW_BKG;
    SHOW_SPRITES;
    set_sprite_data(0u, 2u, sprites_player_tiles);
    set_sprite_tile(0u, 0u);
    move_sprite(0u, _player_x + 8u, _player_y + 16u);
    set_sprite_tile(1u, 1u);
    move_sprite(1u, _player_x + 8u, _player_y + 24u);
    title_enter_trampoline();
    while (1) {
        update_joypad();
        switch (current_scene) {
        case SCENE_WIN:
            win_frame_trampoline();
            break;
        case SCENE_GAMEPLAY:
            gameplay_frame_trampoline();
            break;
        case SCENE_TITLE:
            title_frame_trampoline();
            break;
        }
        update_sprites();
        sound_driver_update();
        wait_vbl_done();
    }
    return;
}
