// Generated by gbkt

#include <gb/gb.h>
#include <stdio.h>
#include <stdlib.h>
#include <gbdk/console.h>
#include "game.h"
#include "sprites/ball.h"

#define SCENE_PLAY 0

UINT8 _ball_x = 64u;
UINT8 _ball_y = 64u;
INT16 _posX = 1024u;
INT16 _posY = 1024u;
INT16 _spdX = 0u;
INT16 _spdY = 0u;
UINT8 __joypad = 0u;
UINT8 __joypad_prev = 0u;
UINT8 _sound_channels[4] = {0xFF, 0xFF, 0xFF, 0xFF};
UINT8 _sound_priority[4] = {0, 0, 0, 0};
UINT8 _sound_duration[4] = {0, 0, 0, 0};
UINT8 _dialog_speed = 1u;
UINT8 current_scene = SCENE_PLAY;
UINT8 _wait_counter = 0u;
UINT8 _current_tileset_id = 0xFF;

// Input helpers (joypad polling with edge detection)
void update_joypad(void) {
    __joypad_prev = __joypad;
    __joypad = joypad();
}

UINT8 button_pressed(UINT8 mask) {
    return __joypad & mask & ~(__joypad_prev & mask);
}

UINT8 button_held(UINT8 mask) {
    return __joypad & mask;
}

/* Deduplicated: see button_held */

/* Deduplicated: see button_pressed */

UINT8 button_released(UINT8 mask) {
    return (~__joypad & mask) & __joypad_prev & mask;
}

/* Deduplicated: see button_released */

UINT8 dpad_any(void) {
    return __joypad & (J_UP|J_DOWN|J_LEFT|J_RIGHT);
}

// Timing helpers (blocking busy-wait)
void delay_frames(UINT8 n) {
    UINT8 _d = 0u;
    for (; _d < n; _d++) {
        wait_vbl_done();
    }
}

// Sprite helpers (real OAM management)
void hide_sprites_range(UINT8 from, UINT8 to) {
    UINT8 i;
    for (i = from; i < to; i++) {
        move_sprite(i, 0, 0);
    }
}

void show_sprites_range(UINT8 from, UINT8 to) {
    (void)from;
    (void)to;
    // Sprites shown by moving to valid positions via update_sprites()
}

// Sprite OAM sync (called every frame)
void update_sprites(void) {
    move_sprite(0u, _ball_x + 8u, _ball_y + 16u);
}

// Sound driver (channel allocation with priority preemption)
void sound_driver_update(void) {
    UINT8 ch;
    for (ch = 0u; ch < 4u; ch++) {
        if (_sound_duration[ch] > 0u) {
            --_sound_duration[ch];
            if (_sound_duration[ch] == 0u) {
                _sound_channels[ch] = 255u;
            }
        }
    }
}

void play_sound(UINT8 sound_id, UINT8 channel, UINT8 priority, UINT8 duration) {
    if (_sound_duration[channel] == 0u || priority >= _sound_priority[channel]) {
        _sound_channels[channel] = sound_id;
        _sound_priority[channel] = priority;
        _sound_duration[channel] = duration;
    }
}

// Dialog helpers (window layer rendering)
void _win_print_at(UINT8 x, UINT8 y, const UINT8* str, UINT8 len) {
    UINT8 i = 0u;
    for (; i < len; i++) {
        set_win_tiles(x + i, y, 1u, 1u, (unsigned char*)&str[i]);
    }
}

void _win_clear_region(UINT8 x, UINT8 y, UINT8 w, UINT8 h) {
    UINT8 ry = 0u;
    UINT8 rx = 0u;
    UINT8 blank = 0u;
    for (; ry < h; ry++) {
        for (; rx < w; rx++) {
            set_win_tiles(x + rx, y + ry, 1u, 1u, &blank);
        }
    }
}

void _win_fill_screen(UINT8 tile) {
    UINT8 fy = 0u;
    UINT8 fx = 0u;
    for (; fy < 18u; fy++) {
        for (; fx < 20u; fx++) {
            set_win_tiles(fx, fy, 1u, 1u, &tile);
        }
    }
}

// Fade helpers (palette-based screen fade)
void fade_out(void) {
    BGP_REG = 180u;
    OBP0_REG = 180u;
    wait_vbl_done();
    BGP_REG = 108u;
    OBP0_REG = 108u;
    wait_vbl_done();
    BGP_REG = 36u;
    OBP0_REG = 36u;
    wait_vbl_done();
    BGP_REG = 0u;
    OBP0_REG = 0u;
    wait_vbl_done();
}

void fade_in(void) {
    BGP_REG = 36u;
    OBP0_REG = 36u;
    wait_vbl_done();
    BGP_REG = 108u;
    OBP0_REG = 108u;
    wait_vbl_done();
    BGP_REG = 180u;
    OBP0_REG = 180u;
    wait_vbl_done();
    BGP_REG = 228u;
    OBP0_REG = 228u;
    wait_vbl_done();
}

// Scene navigation
void navigate_to_scene(UINT8 scene) {
    current_scene = scene;
    switch (scene) {
    case SCENE_PLAY:
        play_enter();
        break;
    }
}

// Entry point
void main(void) {
    NR52_REG = 128u;
    NR50_REG = 119u;
    NR51_REG = 255u;
    DISPLAY_ON;
    SHOW_BKG;
    SHOW_SPRITES;
    set_sprite_data(0u, 1u, sprites_ball_tiles);
    set_sprite_tile(0u, 0u);
    move_sprite(0u, _ball_x + 8u, _ball_y + 16u);
    play_enter();
    while (1) {
        update_joypad();
        switch (current_scene) {
        case SCENE_PLAY:
            play_frame();
            break;
        }
        update_sprites();
        sound_driver_update();
        wait_vbl_done();
    }
}

// Scene: play
void play_enter(void) {
    SHOW_SPRITES;
    _posX = 1024u;
    _posY = 1024u;
    _spdX = 0u;
    _spdY = 0u;
}

void play_frame(void) {
    if (button_held(J_UP)) {
        _spdY -= 2u;
        if (_spdY < -64) {
            _spdY = -64;
        }
    }
    if (button_held(J_DOWN)) {
        _spdY += 2u;
        if (_spdY > 64) {
            _spdY = 64u;
        }
    }
    if (button_held(J_LEFT)) {
        _spdX -= 2u;
        if (_spdX < -64) {
            _spdX = -64;
        }
    }
    if (button_held(J_RIGHT)) {
        _spdX += 2u;
        if (_spdX > 64) {
            _spdX = 64u;
        }
    }
    if (button_pressed(J_A)) {
        _spdY = -32;
    }
    _posX += _spdX;
    _posY += _spdY;
    {
        _ball_x = _posX >> 4u;
        _ball_y = _posY >> 4u;
    }
    if (_spdY < 0) {
        _spdY = _spdY + 1u;
    }
    if (_spdY > 0) {
        _spdY = _spdY - 1u;
    }
    if (_spdX < 0) {
        _spdX = _spdX + 1u;
    }
    if (_spdX > 0) {
        _spdX = _spdX - 1u;
    }
}
