// Generated by gbkt
#pragma bank 1

#include <stdio.h>
#include <gbdk/console.h>
#include "game.h"

// Scene: win
void win_enter(void) BANKED {
    HIDE_SPRITES;
    cls();
    {
        gotoxy(6u, 6u);
        printf("YOU WIN!");
    }
    {
        gotoxy(6u, 9u);
        printf("SCORE: %d", _score);
    }
    {
        gotoxy(5u, 13u);
        printf("PRESS START");
    }
}

void win_frame(void) BANKED {
    update_hud_breakout_hud();
    if (button_pressed(J_START)) {
        navigate_to_scene(SCENE_TITLE);
    }
}

// Scene: gameover
void gameover_enter(void) BANKED {
    HIDE_SPRITES;
    cls();
    {
        gotoxy(6u, 6u);
        printf("GAME OVER");
    }
    {
        gotoxy(6u, 9u);
        printf("SCORE: %d", _score);
    }
    {
        gotoxy(5u, 13u);
        printf("PRESS START");
    }
}

/* Deduplicated: see win_frame */

// Scene: game
void game_enter(void) BANKED {
    cls();
    SHOW_SPRITES;
    {
        _paddle_x = 72u;
        _paddle_y = 132u;
    }
    show_hud_breakout_hud();
    {
        _ball_x = 80u;
        _ball_y = 120u;
    }
    _ballDx = 1u;
    _ballDy = -1;
    _score = 0u;
    _lives = 3u;
    _bricksLeft = 30u;
    _bidx = 0u;
    while (_bidx < 30u) {
        _bricks[_bidx] = 1u;
        _bidx += 1u;
    }
    {
        gotoxy(2u, 1u);
        printf("SCORE:%d  LIVES:%d", _score, _lives);
    }
    {
        gotoxy(5u, 3u);
        printf("##########");
    }
    {
        gotoxy(5u, 4u);
        printf("##########");
    }
    {
        gotoxy(5u, 5u);
        printf("##########");
    }
}

void game_frame(void) BANKED {
    update_hud_breakout_hud();
    if (button_held(J_LEFT)) {
        if (_paddle_x > 3u) {
            {
                _paddle_x += -3;
            }
        }
    }
    if (button_held(J_RIGHT)) {
        if (_paddle_x < 136u) {
            {
                _paddle_x += 3u;
            }
        }
    }
    _ball_x += _ballDx;
    _ball_y += _ballDy;
    if (_ball_x < 4u) {
        _ballDx = 1u;
        play_sound_hitSfx();
    }
    if (_ball_x > 152u) {
        _ballDx = -1;
        play_sound_hitSfx();
    }
    if (_ball_y < 16u) {
        _ballDy = 1u;
        play_sound_hitSfx();
    }
    if (_ball_x < _paddle_x + 24u && _ball_x + 8u > _paddle_x && _ball_y < _paddle_y + 8u && _ball_y + 8u > _paddle_y) {
        _ballDy = -1;
        play_sound_hitSfx();
    }
    if (_ball_y > 144u) {
        _lives -= 1u;
        play_sound_loseSfx();
        {
            gotoxy(2u, 1u);
            printf("SCORE:%d  LIVES:%d", _score, _lives);
        }
        HIDE_SPRITES;
        {
            gotoxy(3u, 9u);
            printf("  BALL LOST!  ");
        }
        delay_frames(40u);
        {
            gotoxy(3u, 9u);
            printf("              ");
        }
        SHOW_SPRITES;
        {
            _ball_x = 80u;
            _ball_y = 120u;
        }
        _ballDx = 1u;
        _ballDy = -1;
        if (_lives == 0u) {
            navigate_to_scene(SCENE_GAMEOVER);
        }
    }
    if (_ball_y >= 24u && _ball_y < 48u) {
        if (_ball_x >= 40u && _ball_x < 120u) {
            _bc = _ball_x - 40u >> 3u;
            _brow = _ball_y - 24u >> 3u;
            _bidx = _brow * 10u + _bc;
            if (_bidx < 30u) {
                if (_bricks[_bidx] == 1u) {
                    _bricks[_bidx] = 0u;
                    gotoxy(_bc + 5u, _brow + 3u);
                    {
                        printf(" ");
                    }
                    _bricksLeft -= 1u;
                    _score += 10u;
                    _ballDy *= -1;
                    play_sound_hitSfx();
                    {
                        gotoxy(2u, 1u);
                        printf("SCORE:%d  LIVES:%d", _score, _lives);
                    }
                }
            }
        }
    }
    if (_bricksLeft == 0u) {
        play_sound_winSfx();
        navigate_to_scene(SCENE_WIN);
    }
}

// Scene: title
void title_enter(void) BANKED {
    HIDE_SPRITES;
    cls();
    {
        gotoxy(6u, 6u);
        printf("BREAKOUT");
    }
    {
        gotoxy(5u, 10u);
        printf("PRESS START");
    }
}

void title_frame(void) BANKED {
    update_hud_breakout_hud();
    if (button_pressed(J_START)) {
        navigate_to_scene(SCENE_GAME);
    }
}
