// Generated by gbkt
#ifndef GAME_H
#define GAME_H

#include <gb/gb.h>
#include <stdio.h>
#include <gbdk/console.h>

#define SCENE_WIN 0
#define SCENE_GAMEOVER 1
#define SCENE_GAME 2
#define SCENE_TITLE 3

extern UINT8 _paddle_x;
extern UINT8 _paddle_y;
extern UINT8 _ball_x;
extern UINT8 _ball_y;
extern UINT8 _score;
extern UINT8 _lives;
extern UINT8 _bricksLeft;
extern INT8 _ballDx;
extern INT8 _ballDy;
extern UINT8 _bc;
extern UINT8 _brow;
extern UINT8 _bidx;
extern UINT8 _bricks[30];
extern UINT8 __joypad;
extern UINT8 __joypad_prev;
extern UINT8 _sound_channels[4];
extern UINT8 _sound_priority[4];
extern UINT8 _sound_duration[4];
extern UINT8 current_scene;
extern UINT8 _wait_counter;
extern UINT8 _dialog_speed;
extern UINT8 _hud_breakout_hud_visible;
extern UINT8 _hud_breakout_hud_score_prev;
extern UINT8 _hud_breakout_hud_lives_prev;
extern const UINT8 _hud_full_icon_breakout_hud_lives;
extern const UINT8 _hud_empty_icon_breakout_hud_lives;
extern UINT8 _current_tileset_id;

// Forward declarations for external functions called via callOp()
void delay_frames(UINT8 p0);

// Scene: win
void win_enter(void) BANKED;

void win_frame(void) BANKED;

// Scene: gameover
void gameover_enter(void) BANKED;

void win_frame(void) BANKED;

// Scene: game
void game_enter(void) BANKED;

void game_frame(void) BANKED;

// Scene: title
void title_enter(void) BANKED;

void title_frame(void) BANKED;

// Input helpers (joypad polling with edge detection)
void update_joypad(void);

UINT8 button_pressed(UINT8 mask);

UINT8 button_held(UINT8 mask);

UINT8 button_held(UINT8 mask);

UINT8 button_pressed(UINT8 mask);

UINT8 button_released(UINT8 mask);

UINT8 button_released(UINT8 mask);

UINT8 dpad_any(void);

// Timing helpers (blocking busy-wait)
void delay_frames(UINT8 n);

// Sprite helpers (real OAM management)
void hide_sprites_range(UINT8 from, UINT8 to);

void show_sprites_range(UINT8 from, UINT8 to);

// Sprite OAM sync (called every frame)
void update_sprites(void);

// Sound driver (channel allocation with priority preemption)
void sound_driver_update(void);

void play_sound(UINT8 sound_id, UINT8 channel, UINT8 priority, UINT8 duration);

void play_sound_hitSfx(void);

void play_sound_loseSfx(void);

void play_sound_scoreSfx(void);

void play_sound_winSfx(void);

// Dialog helpers (window layer rendering)
void _win_print_at(UINT8 x, UINT8 y, const UINT8* str, UINT8 len);

void _win_clear_region(UINT8 x, UINT8 y, UINT8 w, UINT8 h);

void _win_fill_screen(UINT8 tile);

// HUD helpers (change-detection rendering)
void _hud_print_u8(UINT8 x, UINT8 y, UINT8 value);

// HUD: breakout_hud
void update_hud_breakout_hud(void);

void show_hud_breakout_hud(void);

void hide_hud_breakout_hud(void);

// Fade helpers (palette-based screen fade)
void fade_out(void);

void fade_in(void);

// Trampoline: win_enter (bank 1)
void win_enter_trampoline(void);

void win_frame_trampoline(void);

// Trampoline: gameover_enter (bank 1)
void gameover_enter_trampoline(void);

void gameover_frame_trampoline(void);

// Trampoline: game_enter (bank 1)
void game_enter_trampoline(void);

void game_frame_trampoline(void);

// Trampoline: title_enter (bank 1)
void title_enter_trampoline(void);

void title_frame_trampoline(void);

// Scene navigation
void navigate_to_scene(UINT8 scene);

#endif // GAME_H
