// Generated by gbkt
#pragma bank 1

#include <stdio.h>
#include <gbdk/console.h>
#include "game.h"

// Scene: gameover
void gameover_enter(void) BANKED {
    HIDE_SPRITES;
    cls();
    {
        gotoxy(6u, 6u);
        printf("GAME OVER");
    }
    {
        gotoxy(5u, 9u);
        printf("LEVEL: %d", _level);
    }
    {
        gotoxy(5u, 13u);
        printf("PRESS START");
    }
}

void gameover_frame(void) BANKED {
    update_hud_game_hud();
    if (button_pressed(J_START)) {
        navigate_to_scene(SCENE_TITLE);
    }
}

// Scene: combat_scene
void combat_scene_enter(void) BANKED {
    HIDE_SPRITES;
    cls();
    {
        gotoxy(3u, 3u);
        printf("GOBLIN APPEARS!");
    }
    delay_frames(60u);
    {
        gotoxy(2u, 6u);
        printf("You attack!  5dmg");
    }
    delay_frames(40u);
    {
        gotoxy(2u, 8u);
        printf("Goblin hits! 3dmg");
    }
    if (_hp > 3u) {
        _hp -= 3u;
    } else {
        _hp = 0u;
    }
    delay_frames(40u);
    {
        gotoxy(3u, 11u);
        printf("Victory! +5 exp");
    }
    delay_frames(60u);
    if (_hp == 0u) {
        navigate_to_scene(SCENE_GAMEOVER);
    }
}

void combat_scene_frame(void) BANKED {
    update_hud_game_hud();
    trigger_combat();
}

// Scene: pause
void pause_enter(void) BANKED {
    HIDE_SPRITES;
    cls();
    show_menu_pause();
}

void pause_frame(void) BANKED {
    update_hud_game_hud();
    if (button_pressed(J_START)) {
        navigate_to_scene(SCENE_GAMEPLAY);
    }
    if (button_pressed(J_B)) {
        navigate_to_scene(SCENE_TITLE);
    }
}

// Scene: gameplay
void gameplay_enter(void) BANKED {
    SHOW_SPRITES;
    cls();
    {
        _player_x = 80u;
        _player_y = 72u;
    }
    show_hud_game_hud();
}

void gameplay_frame(void) BANKED {
    update_hud_game_hud();
    if (button_held(J_UP)) {
        if (_player_y > 16u) {
            {
                _player_y += -2;
            }
        }
    }
    if (button_held(J_DOWN)) {
        if (_player_y < 136u) {
            {
                _player_y += 2u;
            }
        }
    }
    if (button_held(J_LEFT)) {
        if (_player_x > 8u) {
            {
                _player_x += -2;
            }
        }
    }
    if (button_held(J_RIGHT)) {
        if (_player_x < 152u) {
            {
                _player_x += 2u;
            }
        }
    }
    if (dpad_any()) {
        _stepCount += 1u;
    }
    if (_stepCount > 0u && _stepCount & 3u == 0u && _torchLevel > 0u) {
        _torchLevel -= 1u;
    }
    if (button_pressed(J_START)) {
        navigate_to_scene(SCENE_PAUSE);
    }
    if (_stepCount >= 120u) {
        _stepCount = 0u;
        navigate_to_scene(SCENE_COMBAT_SCENE);
    }
    if (_torchLevel == 0u) {
        HIDE_SPRITES;
        show_dialog_torch_warning("Your torch burns out...", 23u);
        delay_frames(60u);
        navigate_to_scene(SCENE_GAMEOVER);
    }
}

void gameplay_exit(void) BANKED {
    hide_hud_game_hud();
}

// Scene: title
void title_enter(void) BANKED {
    HIDE_SPRITES;
    cls();
    {
        gotoxy(6u, 5u);
        printf("EXPLORER");
    }
    {
        gotoxy(3u, 8u);
        printf("A DUNGEON CRAWL");
    }
    {
        gotoxy(5u, 12u);
        printf("PRESS START");
    }
}

void title_frame(void) BANKED {
    update_hud_game_hud();
    if (button_pressed(J_START)) {
        _hp = 20u;
        _torchLevel = 100u;
        _stepCount = 0u;
        _keys = 0u;
        _level = 1u;
        navigate_to_scene(SCENE_GAMEPLAY);
    }
}
