// Generated by gbkt

#include <gb/gb.h>
#include <stdio.h>
#include <stdlib.h>
#include <gbdk/console.h>
#include "game.h"
#include "sprites/player.h"

#define SCENE_GAMEOVER 0
#define SCENE_COMBAT_SCENE 1
#define SCENE_PAUSE 2
#define SCENE_GAMEPLAY 3
#define SCENE_TITLE 4
#define TILESET_FLOOR1 1
#define TILESET_FLOOR2 2
#define MAX_ENTITIES 1
#define MAP_SIZE 129
#define _COMBAT_STATE_INIT 0
#define _COMBAT_STATE_PLAYER_TURN 1
#define _COMBAT_STATE_ENEMY_TURN 2
#define _COMBAT_STATE_VICTORY 3
#define _COMBAT_STATE_DEFEAT 4
#define _COMBAT_STATE_TARGET_SELECT 5
#define _COMBAT_STATE_EXECUTE_ACTION 6
#define _COMBAT_STATE_FLEEING 7
#define _COMBAT_STATE_WAITING 8

UINT8 _player_x = 80u;
UINT8 _player_y = 72u;
UINT8 _hp = 20u;
UINT8 _stepCount = 0u;
UINT8 _keys = 0u;
UINT8 _torchLevel = 100u;
UINT8 _level = 1u;
UINT8 __joypad = 0u;
UINT8 __joypad_prev = 0u;
UINT8 _sound_channels[4] = {0xFF, 0xFF, 0xFF, 0xFF};
UINT8 _sound_priority[4] = {0, 0, 0, 0};
UINT8 _sound_duration[4] = {0, 0, 0, 0};
UINT8 _camera_x = 0u;
UINT8 _camera_y = 0u;
UINT8 _camera_target = 0xFF;
UINT8 _camera_shake_intensity = 0u;
UINT8 _camera_shake_timer = 0u;
UINT8 _current_floor = 0u;
UINT8 _exploration_step_count = 0u;
UINT8 _encounter_safe_steps = 10u;
UINT8 _encounter_triggered = 0u;
UINT8 _encounter_id = 0u;
UINT8 _current_zone_safe = 0u;
UINT8 _current_zone_id = 0xFF;
UINT8 _gauge_torch = 100u;
UINT8 _key_magic_key = 0u;
UINT8 _entity_grid[129];
UINT8 _entity_collision_mode[1] = {0xFF};
UINT8 _entity_collision_shape[1];
UINT8 _entity_tile_x[1] = {0xFF};
UINT8 _entity_tile_y[1] = {0xFF};
UINT8 _entity_count = 0u;
UINT8 _blocking_entity_id = 0xFF;
UINT8 _pushed_entity_id = 0xFF;
UINT8 _push_direction = 0xFF;
UINT8 _entity_tiles_wide[1] = {1};
UINT8 _entity_tiles_high[1] = {1};
UINT8 _entity_push_dir[1] = {0};
UINT8 _entity_push_allowed[1] = {0};
UINT8 _combat_state_combat = 0u;
UINT8 _pending_state_combat = 255u;
UINT8 _dialog_speed = 1u;
UINT8 _hud_game_hud_visible = 0u;
UINT8 _hud_game_hud_hp_prev = 0xFF;
const UINT8 _hud_fill_tile_game_hud_hp = 1u;
const UINT8 _hud_empty_tile_game_hud_hp = 0u;
UINT8 _hud_game_hud_torch_prev = 0xFF;
UINT8 _hud_game_hud_keys_prev = 0xFF;
const UINT8 _hud_full_icon_game_hud_keys = 16u;
const UINT8 _hud_empty_icon_game_hud_keys = 17u;
UINT8 current_scene = SCENE_TITLE;
UINT8 _wait_counter = 0u;
UINT8 _current_tileset_id = 0xFF;
const UINT8 _char_hero_hp = 20u;
const UINT8 _char_hero_sp = 0u;
const UINT8 _char_hero_atk = 5u;
const UINT8 _char_hero_def = 3u;
const UINT8 _char_hero_matk = 0u;
const UINT8 _char_hero_mdef = 0u;
const UINT8 _char_hero_agl = 0u;
UINT8 _char_hero_level = 1u;
UINT16 _char_hero_exp = 0u;
UINT8 _char_active_sp = 0u;
UINT8 _combat_target_idx = 0u;
UINT8 _combat_active_enemy_idx = 0u;
UINT8 _combat_active_ally_idx = 0u;
UINT8 _combat_target_all_enemies = 0u;
UINT8 _combat_target_all_allies = 0u;
UINT8 _combat_target_all = 0u;
UINT8 _flag_metElder = 0u;
UINT8 _flag_hasKey = 0u;
UINT8 _flag_defeatedBoss = 0u;
UINT8 _flag_visitedFloor1 = 0u;
UINT8 _flag_visitedFloor2 = 0u;
UINT8 _combat_difficulty = 1u;
UINT8 _player_level = 1u;
UINT8 _char_target_hp = 0u;
UINT8 _mon_goblin_hp_pct = 100u;
UINT8 _mon_rat_hp_pct = 100u;

// Input helpers (joypad polling with edge detection)
void update_joypad(void) {
    __joypad_prev = __joypad;
    __joypad = joypad();
}

UINT8 button_pressed(UINT8 mask) {
    return __joypad & mask & ~(__joypad_prev & mask);
}

UINT8 button_held(UINT8 mask) {
    return __joypad & mask;
}

/* Deduplicated: see button_held */

/* Deduplicated: see button_pressed */

UINT8 button_released(UINT8 mask) {
    return (~__joypad & mask) & __joypad_prev & mask;
}

/* Deduplicated: see button_released */

UINT8 dpad_any(void) {
    return __joypad & (J_UP|J_DOWN|J_LEFT|J_RIGHT);
}

// Timing helpers (blocking busy-wait)
void delay_frames(UINT8 n) {
    UINT8 _d;
    for (; _d < n; _d++) {
        wait_vbl_done();
    }
}

// Sprite helpers (real OAM management)
void hide_sprites_range(UINT8 from, UINT8 to) {
    UINT8 i;
    for (i = from; i < to; i++) {
        move_sprite(i, 0, 0);
    }
}

void show_sprites_range(UINT8 from, UINT8 to) {
    // Sprites shown by moving to valid positions via update_sprites()
}

// Sprite OAM sync (called every frame)
void update_sprites(void) {
    move_sprite(0u, _player_x + 8u, _player_y + 16u);
    move_sprite(1u, _player_x + 8u, _player_y + 24u);
}

// Sound driver (channel allocation with priority preemption)
void sound_driver_update(void) {
    UINT8 ch;
    for (ch = 0u; ch < 4u; ch++) {
        if (_sound_duration[ch] > 0u) {
            --_sound_duration[ch];
            if (_sound_duration[ch] == 0u) {
                _sound_channels[ch] = 255u;
            }
        }
    }
}

void play_sound(UINT8 sound_id, UINT8 channel, UINT8 priority, UINT8 duration) {
    if (_sound_duration[channel] == 0u || priority >= _sound_priority[channel]) {
        _sound_channels[channel] = sound_id;
        _sound_priority[channel] = priority;
        _sound_duration[channel] = duration;
    }
}

void play_sound_door(void) {
    NR10_REG = 0x00u;
    NR11_REG = 0x94u;
    NR12_REG = 0xE1u;
    NR13_REG = 0x6Cu;
    NR14_REG = 0xC7u;
}

void play_sound_hit(void) {
    NR41_REG = 0x00u;
    NR42_REG = 0xF2u;
    NR43_REG = 0x40u;
    NR44_REG = 0x80u;
}

void play_sound_save(void) {
    NR10_REG = 0x22u;
    NR11_REG = 0x40u;
    NR12_REG = 0xEBu;
    NR13_REG = 0x08u;
    NR14_REG = 0x87u;
}

void play_sound_step(void) {
    NR10_REG = 0x00u;
    NR11_REG = 0x80u;
    NR12_REG = 0xC3u;
    NR13_REG = 0xD6u;
    NR14_REG = 0x86u;
}

// Dialog helpers (window layer rendering)
void _win_print_at(UINT8 x, UINT8 y, const UINT8* str, UINT8 len) {
    UINT8 i = 0u;
    for (; i < len; i++) {
        set_win_tiles(x + i, y, 1u, 1u, (unsigned char*)&str[i]);
    }
}

void _win_clear_region(UINT8 x, UINT8 y, UINT8 w, UINT8 h) {
    UINT8 ry = 0u;
    UINT8 rx = 0u;
    UINT8 blank = 0u;
    for (; ry < h; ry++) {
        for (; rx < w; rx++) {
            set_win_tiles(x + rx, y + ry, 1u, 1u, &blank);
        }
    }
}

void _win_fill_screen(UINT8 tile) {
    UINT8 fy = 0u;
    UINT8 fx = 0u;
    for (; fy < 18u; fy++) {
        for (; fx < 20u; fx++) {
            set_win_tiles(fx, fy, 1u, 1u, &tile);
        }
    }
}

// Dialog: torch_warning
void show_dialog_torch_warning(const UINT8* _text, UINT8 _text_len) {
    UINT8 _pg_off = 0u;
    move_win(7u, 96u);
    SHOW_WIN;
    {
        { UINT8 _border_tile_218 = 218; set_win_tiles(0, 12, 1, 1, &_border_tile_218); }
    }
    {
        { UINT8 _border_tile_191 = 191; set_win_tiles(19, 12, 1, 1, &_border_tile_191); }
    }
    {
        { UINT8 _border_tile_192 = 192; set_win_tiles(0, 15, 1, 1, &_border_tile_192); }
    }
    {
        { UINT8 _border_tile_217 = 217; set_win_tiles(19, 15, 1, 1, &_border_tile_217); }
    }
    {
        { UINT8 _border_tile_196 = 196; set_win_tiles(1, 12, 1, 1, &_border_tile_196); }
    }
    {
        { UINT8 _border_tile_196 = 196; set_win_tiles(2, 12, 1, 1, &_border_tile_196); }
    }
    {
        { UINT8 _border_tile_196 = 196; set_win_tiles(3, 12, 1, 1, &_border_tile_196); }
    }
    {
        { UINT8 _border_tile_196 = 196; set_win_tiles(4, 12, 1, 1, &_border_tile_196); }
    }
    {
        { UINT8 _border_tile_196 = 196; set_win_tiles(5, 12, 1, 1, &_border_tile_196); }
    }
    {
        { UINT8 _border_tile_196 = 196; set_win_tiles(6, 12, 1, 1, &_border_tile_196); }
    }
    {
        { UINT8 _border_tile_196 = 196; set_win_tiles(7, 12, 1, 1, &_border_tile_196); }
    }
    {
        { UINT8 _border_tile_196 = 196; set_win_tiles(8, 12, 1, 1, &_border_tile_196); }
    }
    {
        { UINT8 _border_tile_196 = 196; set_win_tiles(9, 12, 1, 1, &_border_tile_196); }
    }
    {
        { UINT8 _border_tile_196 = 196; set_win_tiles(10, 12, 1, 1, &_border_tile_196); }
    }
    {
        { UINT8 _border_tile_196 = 196; set_win_tiles(11, 12, 1, 1, &_border_tile_196); }
    }
    {
        { UINT8 _border_tile_196 = 196; set_win_tiles(12, 12, 1, 1, &_border_tile_196); }
    }
    {
        { UINT8 _border_tile_196 = 196; set_win_tiles(13, 12, 1, 1, &_border_tile_196); }
    }
    {
        { UINT8 _border_tile_196 = 196; set_win_tiles(14, 12, 1, 1, &_border_tile_196); }
    }
    {
        { UINT8 _border_tile_196 = 196; set_win_tiles(15, 12, 1, 1, &_border_tile_196); }
    }
    {
        { UINT8 _border_tile_196 = 196; set_win_tiles(16, 12, 1, 1, &_border_tile_196); }
    }
    {
        { UINT8 _border_tile_196 = 196; set_win_tiles(17, 12, 1, 1, &_border_tile_196); }
    }
    {
        { UINT8 _border_tile_196 = 196; set_win_tiles(18, 12, 1, 1, &_border_tile_196); }
    }
    {
        { UINT8 _border_tile_196 = 196; set_win_tiles(1, 15, 1, 1, &_border_tile_196); }
    }
    {
        { UINT8 _border_tile_196 = 196; set_win_tiles(2, 15, 1, 1, &_border_tile_196); }
    }
    {
        { UINT8 _border_tile_196 = 196; set_win_tiles(3, 15, 1, 1, &_border_tile_196); }
    }
    {
        { UINT8 _border_tile_196 = 196; set_win_tiles(4, 15, 1, 1, &_border_tile_196); }
    }
    {
        { UINT8 _border_tile_196 = 196; set_win_tiles(5, 15, 1, 1, &_border_tile_196); }
    }
    {
        { UINT8 _border_tile_196 = 196; set_win_tiles(6, 15, 1, 1, &_border_tile_196); }
    }
    {
        { UINT8 _border_tile_196 = 196; set_win_tiles(7, 15, 1, 1, &_border_tile_196); }
    }
    {
        { UINT8 _border_tile_196 = 196; set_win_tiles(8, 15, 1, 1, &_border_tile_196); }
    }
    {
        { UINT8 _border_tile_196 = 196; set_win_tiles(9, 15, 1, 1, &_border_tile_196); }
    }
    {
        { UINT8 _border_tile_196 = 196; set_win_tiles(10, 15, 1, 1, &_border_tile_196); }
    }
    {
        { UINT8 _border_tile_196 = 196; set_win_tiles(11, 15, 1, 1, &_border_tile_196); }
    }
    {
        { UINT8 _border_tile_196 = 196; set_win_tiles(12, 15, 1, 1, &_border_tile_196); }
    }
    {
        { UINT8 _border_tile_196 = 196; set_win_tiles(13, 15, 1, 1, &_border_tile_196); }
    }
    {
        { UINT8 _border_tile_196 = 196; set_win_tiles(14, 15, 1, 1, &_border_tile_196); }
    }
    {
        { UINT8 _border_tile_196 = 196; set_win_tiles(15, 15, 1, 1, &_border_tile_196); }
    }
    {
        { UINT8 _border_tile_196 = 196; set_win_tiles(16, 15, 1, 1, &_border_tile_196); }
    }
    {
        { UINT8 _border_tile_196 = 196; set_win_tiles(17, 15, 1, 1, &_border_tile_196); }
    }
    {
        { UINT8 _border_tile_196 = 196; set_win_tiles(18, 15, 1, 1, &_border_tile_196); }
    }
    {
        { UINT8 _border_tile_179 = 179; set_win_tiles(0, 13, 1, 1, &_border_tile_179); }
    }
    {
        { UINT8 _border_tile_179 = 179; set_win_tiles(0, 14, 1, 1, &_border_tile_179); }
    }
    {
        { UINT8 _border_tile_179 = 179; set_win_tiles(19, 13, 1, 1, &_border_tile_179); }
    }
    {
        { UINT8 _border_tile_179 = 179; set_win_tiles(19, 14, 1, 1, &_border_tile_179); }
    }
    while (1u) {
        if (_pg_off > 0u) {
            _win_clear_region(1u, 1u, 18u, 2u);
        }
        UINT8 _tw_i;
        for (; _tw_i < 36u && _pg_off + _tw_i < _text_len; _tw_i++) {
            set_win_tiles(1u + _tw_i % 18u, 1u + _tw_i / 18u, 1u, 1u, (unsigned char*)&_text[_pg_off + _tw_i]);
            delay_frames(2u);
        }
        _pg_off += 36u;
        while (!(joypad() & J_A)) {
            wait_vbl_done();
        }
        while (joypad() & J_A) {
            wait_vbl_done();
        }
        break;
    }
    HIDE_WIN;
}

// Menu: pause
UINT8 show_menu_pause(void) {
    UINT8 sel = 0u;
    UINT8 joy = 0u;
    move_win(7u, 32u);
    SHOW_WIN;
    _win_print_at(5u, 4u, "Resume", 6u);
    _win_print_at(5u, 5u, "Quit to Title", 13u);
    while (1u) {
        _win_print_at(4u, sel, ">", 1u);
        wait_vbl_done();
        joy = joypad();
        if (joy & J_UP && sel > 0u) {
            _win_print_at(4u, sel, " ", 1u);
            --sel;
            play_sound_step();
        }
        if (joy & J_DOWN && sel < 1u) {
            _win_print_at(4u, sel, " ", 1u);
            ++sel;
            play_sound_step();
        }
        if (joy & J_A) {
            play_sound_door();
            break;
        }
        if (joy & J_B) {
            HIDE_WIN;
            return 255u;
        }
    }
    HIDE_WIN;
    return sel;
}

// HUD helpers (change-detection rendering)
void _hud_print_u8(UINT8 x, UINT8 y, UINT8 value) {
    UINT8 buf[3];
    UINT8 len;
    UINT8 i;
    buf[0u] = 48u + value / 100u;
    buf[1u] = 48u + value / 10u % 10u;
    buf[2u] = 48u + value % 10u;
    len = 3u;
    i = 0u;
    for (; i < len; i++) {
        set_win_tiles(x + i, y, 1u, 1u, &buf[i]);
    }
}

// HUD: game_hud
void update_hud_game_hud(void) {
    if (_hud_game_hud_visible == 0u) {
        return;
    }
    if (_hp != _hud_game_hud_hp_prev) {
        _hud_game_hud_hp_prev = _hp;
        UINT8 _hfi;
        UINT8 _hfilled;
        _hfilled = _hp * 5u / 20u;
        _hfi = 0u;
        for (; _hfi < 5u; _hfi++) {
            if (_hfi < _hfilled) {
                set_win_tiles(0u + _hfi, 0u, 1u, 1u, (unsigned char*)&_hud_fill_tile_game_hud_hp);
            } else {
                set_win_tiles(0u + _hfi, 0u, 1u, 1u, (unsigned char*)&_hud_empty_tile_game_hud_hp);
            }
        }
    }
    if (_torchLevel != _hud_game_hud_torch_prev) {
        _hud_game_hud_torch_prev = _torchLevel;
        _win_print_at(5u, 0u, "T:", 2u);
        _hud_print_u8(7u, 0u, _torchLevel);
    }
    if (_keys != _hud_game_hud_keys_prev) {
        _hud_game_hud_keys_prev = _keys;
        UINT8 _hii;
        _hii = 0u;
        for (; _hii < 5u; _hii++) {
            if (_hii < _keys) {
                set_win_tiles(10u + _hii, 0u, 1u, 1u, (unsigned char*)&_hud_full_icon_game_hud_keys);
            } else {
                set_win_tiles(10u + _hii, 0u, 1u, 1u, (unsigned char*)&_hud_empty_icon_game_hud_keys);
            }
        }
    }
}

void show_hud_game_hud(void) {
}

void hide_hud_game_hud(void) {
    _hud_game_hud_visible = 0u;
    _win_clear_region(0u, 0u, 15u, 1u);
}

// Fade helpers (palette-based screen fade)
void fade_out(void) {
    BGP_REG = 180u;
    OBP0_REG = 180u;
    wait_vbl_done();
    BGP_REG = 108u;
    OBP0_REG = 108u;
    wait_vbl_done();
    BGP_REG = 36u;
    OBP0_REG = 36u;
    wait_vbl_done();
    BGP_REG = 0u;
    OBP0_REG = 0u;
    wait_vbl_done();
}

void fade_in(void) {
    BGP_REG = 36u;
    OBP0_REG = 36u;
    wait_vbl_done();
    BGP_REG = 108u;
    OBP0_REG = 108u;
    wait_vbl_done();
    BGP_REG = 180u;
    OBP0_REG = 180u;
    wait_vbl_done();
    BGP_REG = 228u;
    OBP0_REG = 228u;
    wait_vbl_done();
}

// Stub collision — no scenes have collision data
UINT8 _map_collision(UINT8 x, UINT8 y) {
    return 0u;
}

// Camera system: camera
void update_camera_camera(void) {
    if (_camera_shake_timer > 0u) {
        UINT8 offset = (_camera_shake_timer & 1u != 0u) ? _camera_shake_intensity : 0u;
        SCX_REG = _camera_x + offset;
        SCY_REG = _camera_y + offset;
        --_camera_shake_timer;
    } else {
        SCX_REG = _camera_x;
        SCY_REG = _camera_y;
    }
}

// Save system: explorer_save (slots=1, checksum=false)
void save_game_explorer_save(UINT8 slotIndex) {
    ENABLE_RAM;
    UINT8* sram = (volatile UINT8 *)(0xA000 + (UINT16)slotIndex * 6u);
    sram[0u] = _hp;
    sram[1u] = _stepCount;
    sram[2u] = _keys;
    sram[3u] = _torchLevel;
    sram[4u] = _level;
    sram[5u] = 171u;
    DISABLE_RAM;
}

void load_game_explorer_save(UINT8 slotIndex) {
    ENABLE_RAM;
    UINT8* sram = (volatile UINT8 *)(0xA000 + (UINT16)slotIndex * 6u);
    if (sram[5u] != 171u) {
        DISABLE_RAM;
        return;
    }
    _hp = sram[0u];
    _stepCount = sram[1u];
    _keys = sram[2u];
    _torchLevel = sram[3u];
    _level = sram[4u];
    DISABLE_RAM;
}

// Exploration system: exploration
void exploration_move_exploration(void) {
    UINT8 nx = _player_x;
    UINT8 ny = _player_y;
    UINT8 direction = 255u;
    if (button_held(J_UP) && ny > 0u) {
        --ny;
        direction = 0u;
    }
    if (button_held(J_DOWN) && ny < 31u) {
        ++ny;
        direction = 1u;
    } else {
        if (button_held(J_LEFT) && nx > 0u) {
            --nx;
            direction = 2u;
        } else {
            if (button_held(J_RIGHT) && nx < 31u) {
                ++nx;
                direction = 3u;
            } else {
                return;
            }
        }
    }
    if (_map_collision(nx, ny)) {
        return;
    }
    UINT8 entity_id = _entity_check(nx, ny);
    if (entity_id != 255u) {
        _entity_handle_block(entity_id, nx, ny, direction);
        if (_entity_collision_mode[entity_id] != 3u) {
            return;
        }
    }
    _player_x = nx;
    _player_y = ny;
    exploration_step_exploration();
}

void exploration_step_exploration(void) {
    ++_exploration_step_count;
    if (_gauge_torch > 0u) {
        _gauge_torch -= 1u;
        if (_gauge_torch <= 50u) {
            navigate_to_scene(SCENE_GAMEPLAY);
        }
        if (_gauge_torch == 0u) {
            navigate_to_scene(SCENE_GAMEOVER);
        }
    }
    navigate_to_scene(SCENE_GAMEPLAY);
    exploration_encounter_check_exploration();
    zone_check_edges_exploration();
}

void exploration_encounter_check_exploration(void) {
    if (_current_zone_safe) {
        return;
    }
    if (_exploration_step_count < _encounter_safe_steps) {
        return;
    }
    UINT8 roll;
    roll = rand() % 30u;
    UINT8 acc = 0u;
    if (roll < acc + 30u) {
        _encounter_triggered = 1u;
        _encounter_id = 0u;
        return;
    }
    acc += 30u;
}

/* Deduplicated: see show_hud_game_hud */

void zone_load_exploration(UINT8 zone_id) {
    _current_zone_id = zone_id;
    if (_current_tileset_id != zone_id) {
        // load tileset for zone
        _current_tileset_id = zone_id;
    }
    switch (zone_id) {
    case 0u:
        SWITCH_ROM(2);
        set_bkg_tiles(0u, 0u, 32u, 128u, _zone_floor1_tiles);
        SWITCH_ROM(1);
        break;
    case 1u:
        SWITCH_ROM(2);
        set_bkg_tiles(0u, 0u, 16u, 128u, _zone_floor2_tiles);
        SWITCH_ROM(1);
        break;
    default:
        break;
    }
    switch (zone_id) {
    case 0u:
        navigate_to_scene(SCENE_GAMEPLAY);
        break;
    default:
        break;
    }
    switch (zone_id) {
    case 0u:
        _current_zone_safe = 0u;
        break;
    case 1u:
        _current_zone_safe = 1u;
        break;
    default:
        _current_zone_safe = 0u;
        break;
    }
}

void zone_transition_exploration(UINT8 target_zone_id, UINT8 edge, UINT8 entry_x, UINT8 entry_y) {
    if (entry_x != 255u) {
        _player_x = entry_x;
        _player_y = entry_y;
    } else {
        switch (edge) {
        case 2u:
            _player_x = 0u;
            break;
        case 3u:
            _player_x = 31u;
            break;
        case 0u:
            _player_y = 31u;
            break;
        case 1u:
            _player_y = 0u;
            break;
        default:
            break;
        }
    }
    zone_load_exploration(target_zone_id);
}

void zone_check_edges_exploration(void) {
    switch (_current_zone_id) {
    case 0u:
        if (_player_x == 31u) {
            zone_transition_exploration(1u, 2u, 0u, 15u);
            return;
        }
        break;
    case 1u:
        if (_player_x == 0u) {
            zone_transition_exploration(0u, 3u, 31u, 15u);
            return;
        }
        break;
    default:
        break;
    }
}

// Entity collision functions: exploration
void _entity_register(UINT8 entity_id, UINT8 tile_x, UINT8 tile_y, UINT8 mode) {
    _entity_tile_x[entity_id] = tile_x;
    _entity_tile_y[entity_id] = tile_y;
    _entity_collision_mode[entity_id] = mode;
    _entity_collision_shape[entity_id] = 0u;
    UINT8 dy = 0u;
    for (dy = 0u; dy < _entity_tiles_high[entity_id]; dy++) {
        UINT8 dx = 0u;
        for (dx = 0u; dx < _entity_tiles_wide[entity_id]; dx++) {
            UINT8 idx = tile_y + dy * 32u + tile_x + dx;
            _entity_grid[idx / 8u] |= 1u << idx % 8u;
        }
    }
    ++_entity_count;
}

void _entity_remove(UINT8 entity_id) {
    UINT8 tx = _entity_tile_x[entity_id];
    UINT8 ty = _entity_tile_y[entity_id];
    UINT8 dy = 0u;
    for (dy = 0u; dy < _entity_tiles_high[entity_id]; dy++) {
        UINT8 dx = 0u;
        for (dx = 0u; dx < _entity_tiles_wide[entity_id]; dx++) {
            UINT8 idx = ty + dy * 32u + tx + dx;
            _entity_grid[idx / 8u] &= ~1u << idx % 8u;
        }
    }
    _entity_collision_mode[entity_id] = 0xFF;
    _entity_tile_x[entity_id] = 0xFF;
    _entity_tile_y[entity_id] = 0xFF;
    --_entity_count;
}

UINT8 _entity_check(UINT8 nx, UINT8 ny) {
    UINT8 idx = ny * 32u + nx;
    UINT8 bit = _entity_grid[idx / 8u] & 1u << idx % 8u;
    if (bit != 0u) {
        UINT8 i = 0u;
        for (i = 0u; i < _entity_count; i++) {
            if (_entity_collision_mode[i] == 0xFF) {
                continue;
            }
            if (_entity_collision_shape[i] == 1u) {
                continue;
            }
            if (_entity_tile_x[i] == nx && _entity_tile_y[i] == ny) {
                return i;
            }
        }
    }
    return 0xFF;
}

void _entity_handle_block(UINT8 entity_id, UINT8 nx, UINT8 ny, UINT8 direction) {
    switch (_entity_collision_mode[entity_id]) {
    case 0u:
        // BLOCK: stop movement, emit bump feedback
        _entity_bump_feedback();
        break;
    case 1u:
        break;
    case 2u:
        // BLOCK_AND_TRIGGER: set _blocking_entity_id before callback (Gap 1)
        _blocking_entity_id = entity_id;
        _entity_bump_feedback();
        navigate_to_scene(SCENE_GAMEPLAY);
        break;
    case 3u:
        // OVERLAP_TRIGGER: allow movement, fire overlap callback
        break;
    case 4u:
        // PUSH: try to move entity, set _pushed_entity_id/_push_direction (Gap 1)
        UINT8 push_dir = _entity_push_dir[entity_id];
        if (push_dir == 1u) {
            if (direction == 0u || direction == 1u) {
                _entity_bump_feedback();
                break;
            }
        }
        if (push_dir == 2u) {
            if (direction == 2u || direction == 3u) {
                _entity_bump_feedback();
                break;
            }
        }
        if (push_dir == 3u) {
            if (!_entity_push_allowed[entity_id] & 1u << direction) {
                _entity_bump_feedback();
                break;
            }
        }
        UINT8 ptx = _entity_tile_x[entity_id];
        UINT8 pty = _entity_tile_y[entity_id];
        switch (direction) {
        case 0u:
            --pty;
            break;
        case 1u:
            ++pty;
            break;
        case 2u:
            --ptx;
            break;
        case 3u:
            ++ptx;
            break;
        default:
            break;
        }
        if (!_map_collision(ptx, pty) && _entity_check(ptx, pty) == 0xFF) {
            _entity_remove(entity_id);
            _entity_register(entity_id, ptx, pty, _entity_collision_mode[entity_id]);
            _pushed_entity_id = entity_id;
            _push_direction = direction;
        } else {
            _entity_bump_feedback();
        }
        break;
    default:
        break;
    }
}

void _entity_set_collision_mode(UINT8 entity_id, UINT8 mode) {
    _entity_collision_mode[entity_id] = mode;
}

void _entity_bump_feedback(void) {
    // bump feedback: play sound/visual indicator
}

void combat_request_state_combat(UINT8 s) {
    _pending_state_combat = s;
}

void update_combat_combat(void) {
    if (_pending_state_combat != 255u) {
        _combat_state_combat = _pending_state_combat;
        _pending_state_combat = 255u;
    }
    switch (_combat_state_combat) {
    case 0u:
        combat_request_state_combat(1u);
        break;
    case 1u:
        if (button_pressed(J_A)) {
            combat_request_state_combat(2u);
        }
        break;
    case 2u:
        combat_request_state_combat(1u);
        break;
    case 3u:
        navigate_to_scene(SCENE_GAMEPLAY);
        break;
    case 4u:
        navigate_to_scene(SCENE_GAMEOVER);
        break;
    }
}

UINT8 combat_is_in_state_combat(UINT8 state) {
    return _combat_state_combat == state;
}

void trigger_combat(void) {
    _combat_state_combat = 0u;
    _pending_state_combat = 255u;
}

// Combat engine stubs
void monster_basic_attack(void) {
    // Stub: basic attack — combat engine implementation pending
}

void monster_flee(void) {
    // Stub: flee — combat engine implementation pending
}

UINT8 find_lowest_hp_target(void) {
    return 0u;
    // Stub — returns first target
}

// Trampoline: gameover_enter (bank 1)
void gameover_enter_trampoline(void) {
    gameover_enter();
}

void gameover_frame_trampoline(void) {
    gameover_frame();
}

// Trampoline: combat_scene_enter (bank 1)
void combat_scene_enter_trampoline(void) {
    combat_scene_enter();
}

void combat_scene_frame_trampoline(void) {
    combat_scene_frame();
}

// Trampoline: pause_enter (bank 1)
void pause_enter_trampoline(void) {
    pause_enter();
}

void pause_frame_trampoline(void) {
    pause_frame();
}

// Trampoline: gameplay_enter (bank 1)
void gameplay_enter_trampoline(void) {
    gameplay_enter();
}

void gameplay_frame_trampoline(void) {
    gameplay_frame();
}

void gameplay_exit_trampoline(void) {
    gameplay_exit();
}

// Trampoline: title_enter (bank 1)
void title_enter_trampoline(void) {
    title_enter();
}

void title_frame_trampoline(void) {
    title_frame();
}

// Scene navigation
void navigate_to_scene(UINT8 scene) {
    switch (current_scene) {
    case SCENE_GAMEPLAY:
        gameplay_exit_trampoline();
        break;
    }
    current_scene = scene;
    switch (scene) {
    case SCENE_GAMEOVER:
        gameover_enter_trampoline();
        break;
    case SCENE_COMBAT_SCENE:
        combat_scene_enter_trampoline();
        break;
    case SCENE_PAUSE:
        pause_enter_trampoline();
        break;
    case SCENE_GAMEPLAY:
        gameplay_enter_trampoline();
        break;
    case SCENE_TITLE:
        title_enter_trampoline();
        break;
    }
}

// Entry point
void main(void) {
    NR52_REG = 128u;
    NR50_REG = 119u;
    NR51_REG = 255u;
    DISPLAY_ON;
    SHOW_BKG;
    SHOW_SPRITES;
    set_sprite_data(0u, 2u, sprites_player_tiles);
    set_sprite_tile(0u, 0u);
    move_sprite(0u, _player_x + 8u, _player_y + 16u);
    set_sprite_tile(1u, 1u);
    move_sprite(1u, _player_x + 8u, _player_y + 24u);
    title_enter_trampoline();
    while (1) {
        update_joypad();
        switch (current_scene) {
        case SCENE_GAMEOVER:
            gameover_frame_trampoline();
            break;
        case SCENE_COMBAT_SCENE:
            combat_scene_frame_trampoline();
            break;
        case SCENE_PAUSE:
            pause_frame_trampoline();
            break;
        case SCENE_GAMEPLAY:
            gameplay_frame_trampoline();
            break;
        case SCENE_TITLE:
            title_frame_trampoline();
            break;
        }
        update_sprites();
        sound_driver_update();
        wait_vbl_done();
    }
    return;
}
