/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * Copyright (c) 2026 Michal Svacha
 */
package io.github.gbkt.core.ir

/**
 * IR node representing a game actor (sprite entity).
 *
 * Implements [PlatformAnnotatable] — the backend assigns VRAM/OAM/bank slots during resource
 * allocation. Game authors can override them for explicit hardware control. All annotation fields
 * default to null.
 */
data class ActorIR(
    val id: String,
    val position: PositionDef,
    val sprite: SpriteDef? = null,
    val hitbox: HitboxDef? = null,
    val sourceLocation: SourceLocation? = null,
    override val bankSlot: BankSlot? = null,
    override val vramRange: VRAMRange? = null,
    override val oamSlot: OAMSlot? = null,
    /**
     * Per-actor movement configuration. When non-null, generates update_movement_{id}() function.
     */
    val movementConfig: MovementConfig? = null,
    /**
     * Animation state machine definitions. When non-empty, generates enum + switch-based update.
     */
    val animationStates: List<AnimationStateDef> = emptyList(),
    /** Simple animation frame speed (frames per update). Used when animationStates is empty. */
    val frameSpeed: Int? = null,
    /**
     * Per-actor physics configuration. When non-null, generates velocity variables and #define
     * constants.
     */
    val physicsConfig: PhysicsConfig? = null,
    /**
     * NPC patrol route. When non-null, the actor follows the waypoint sequence via WaypointStep.
     */
    val waypointRoute: WaypointRoute? = null,
    /** ID of the actor to follow (NPC chasing behaviour). Used by PathfindStep. */
    val followTargetId: String? = null,
    /**
     * Per-actor exploration collision configuration. When non-null, the actor participates in the
     * entity collision grid during exploration movement checks.
     *
     * Null means no exploration collision (equivalent to [EntityCollisionMode.PASSTHROUGH]) — all
     * existing actors without collision config are unaffected.
     */
    val entityCollision: EntityCollisionConfig? = null,
    /**
     * Per-actor GBC palette override. When non-null, a [SetPalette] op is emitted in the scene
     * enter handler to load this palette into a SPRITE slot for this actor.
     */
    val palette: GBCPalette? = null,
    /**
     * Per-actor NPC collision configuration. When non-null, the actor participates in NPC-NPC
     * collision checks generated by [CollisionRuleIR] pairs.
     *
     * Null means the actor does not participate in any NPC collision group.
     */
    val npcCollisionConfig: NpcCollisionConfig? = null,
) : PlatformAnnotatable
