/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * Copyright (c) 2026 Michal Svacha
 */
package io.github.gbkt.backend.gbdk.codegen.pipeline

import io.github.gbkt.core.ir.Cartridge
import io.github.gbkt.core.ir.CartridgeConfig
import io.github.gbkt.core.ir.GameIR
import io.github.gbkt.core.ir.GbcTarget
import io.github.gbkt.core.ir.MetaspriteFrame
import io.github.gbkt.core.ir.MetaspriteIR
import io.github.gbkt.core.ir.MetaspriteTile
import io.github.gbkt.core.ir.SceneIR
import io.github.gbkt.core.ir.SpriteMode
import kotlin.test.Test
import kotlin.test.assertFalse
import kotlin.test.assertTrue

// =============================================================================
// Phase 12.9 D2b — GBC-gated set_sprite_palette for metasprites in main()
//
// Root cause (Plan 12.9-08e Diagnose): GBDKPipeline emits set_sprite_data for
// each metasprite but ZERO set_sprite_palette. The metasprite's generated
// <name>_palettes array (from png2asset) is never uploaded to OBJ palette RAM.
// The GBDK runtime default grayscale OBJ palette remains active → the character
// renders with the wrong (grayscale) colors instead of the authored palette.
//
// Fix (D2b): after each metasprite's set_sprite_data in main(), emit a GBC-gated
// set_sprite_palette(<slot>, 1u, <name>_palettes). The <name>_palettes symbol is
// generated by png2asset (one sub-palette of 4 colors for the metasprite). The
// slot counter increments per metasprite (0 for the first, 1 for the second, etc.).
// GBC-gated: emit only when gameIR.config.gbcTarget != GbcTarget.DMG.
//
// RED against HEAD (zero set_sprite_palette in main()). GREEN after D2b fix.
//
// Tests:
//   1. GBC-compatible game with 1 metasprite → main.c emits
//      set_sprite_palette(0u, 1u, player_palettes) (GBC-gated form confirmed by
//      cgb_compatibility() gate context in main()).
//   2. DMG-only game → main.c does NOT emit set_sprite_palette (gate off).
//   3. Game with 0 metasprites → main.c does NOT emit set_sprite_palette.
// =============================================================================

private val minimalMetaspriteFrame =
    MetaspriteFrame(
        tiles =
            listOf(
                MetaspriteTile(relX = 0, relY = 0, tileId = 0),
                MetaspriteTile(relX = 0, relY = 8, tileId = 1),
            )
    )

private fun buildMetaspriteGameIR(target: GbcTarget, metasprites: List<MetaspriteIR>) =
    GameIR(
        name = "MetaspriteSpritePaletteTest",
        config = CartridgeConfig(cartridge = Cartridge.ROM_ONLY, romBanks = 2, gbcTarget = target),
        scenes = listOf(SceneIR(id = "gameplay")),
        metasprites = metasprites,
        startScene = "gameplay",
    )

class MetaspriteSpritePaletteEmissionTest {

    private val pipeline = GBDKPipeline()

    // Brace-walk helper — same pattern as sibling pipeline tests.
    private fun extractFunctionBody(cSource: String, functionSignaturePrefix: String): String {
        val lines = cSource.lines()
        val startIdx = lines.indexOfFirst { it.startsWith(functionSignaturePrefix) }
        if (startIdx == -1) return ""
        val body = StringBuilder()
        var depth = 0
        var started = false
        for (i in startIdx until lines.size) {
            val line = lines[i]
            body.appendLine(line)
            for (ch in line) {
                if (ch == '{') {
                    depth++
                    started = true
                }
                if (ch == '}') depth--
            }
            if (started && depth == 0) break
        }
        return body.toString()
    }

    // =========================================================================
    // Test 1 — GBC game with metasprite → set_sprite_palette emitted, GBC-gated
    //
    // RED: buildAllSpriteDataLoadStatements only emits set_sprite_data → zero
    //      set_sprite_palette in main().
    // GREEN: D2b fix emits GBC-gated set_sprite_palette(<slot>, 1u, <name>_palettes)
    //        after the metasprite's set_sprite_data.
    // =========================================================================

    @Test
    fun `main emits set_sprite_palette for metasprite on GBC target (D2b)`() {
        val gameIR =
            buildMetaspriteGameIR(
                target = GbcTarget.GBC_COMPATIBLE,
                metasprites =
                    listOf(
                        MetaspriteIR(
                            id = "player",
                            frames = listOf(minimalMetaspriteFrame),
                            spriteMode = SpriteMode.SPR8x16,
                        )
                    ),
            )
        val output = pipeline.generate(gameIR)
        val mainC =
            output.files["main.c"] ?: error("main.c not generated. Files: ${output.files.keys}")

        // Brace-walk main() body to lock the assertion inside the right scope.
        val mainBody = extractFunctionBody(mainC, "void main(void)")

        assertTrue(
            mainBody.isNotEmpty(),
            "main() body must be extractable via brace-walk from main.c. " +
                "main.c head:\n${mainC.take(2000)}",
        )

        // D2b positive: set_sprite_palette must be emitted for the "player" metasprite.
        // The palette symbol is player_palettes (png2asset naming convention: <id>_palettes).
        // Slot 0 = first (and only) metasprite. Count = 1u (one 4-color sub-palette per
        // metasprite).
        assertTrue(
            mainBody.contains("set_sprite_palette(") && mainBody.contains("player_palettes"),
            "main() body must contain set_sprite_palette(..., player_palettes) for the player " +
                "metasprite (D2b fix — palette upload after set_sprite_data, GBC-gated). " +
                "main() body:\n${mainBody.take(4000)}",
        )
    }

    // =========================================================================
    // Test 2 — DMG-only game → set_sprite_palette NOT emitted (gate off)
    //
    // Ensures the GBC gate is respected: DMG targets do not have OBJ color palette
    // RAM; emitting set_sprite_palette on DMG is a no-op in libgb, but the test
    // locks the gate to prevent accidental regression.
    // =========================================================================

    @Test
    fun `main does NOT emit set_sprite_palette on DMG-only target (gate off)`() {
        val gameIR =
            buildMetaspriteGameIR(
                target = GbcTarget.DMG,
                metasprites =
                    listOf(
                        MetaspriteIR(
                            id = "player",
                            frames = listOf(minimalMetaspriteFrame),
                            spriteMode = SpriteMode.SPR8x16,
                        )
                    ),
            )
        val output = pipeline.generate(gameIR)
        val mainC = output.files["main.c"] ?: error("main.c not generated")

        assertFalse(
            mainC.contains("set_sprite_palette("),
            "main.c must NOT contain set_sprite_palette on a DMG-only target (OBJ color palette " +
                "RAM only exists on GBC; the D2b gate mirrors the GBC-gated set_bkg_palette path). " +
                "main.c head:\n${mainC.take(2000)}",
        )
    }

    // =========================================================================
    // Test 3 — No metasprites → set_sprite_palette NOT emitted (gate off)
    //
    // Ensures byte-identical emission for actor-only games (Pong, Breakout, etc.)
    // =========================================================================

    @Test
    fun `main does NOT emit set_sprite_palette when no metasprites (back-compat)`() {
        val gameIR =
            buildMetaspriteGameIR(target = GbcTarget.GBC_COMPATIBLE, metasprites = emptyList())
        val output = pipeline.generate(gameIR)
        val mainC = output.files["main.c"] ?: error("main.c not generated")

        assertFalse(
            mainC.contains("set_sprite_palette("),
            "main.c must NOT contain set_sprite_palette when no metasprites are present " +
                "(back-compat gate — actor-only games must remain byte-identical). " +
                "main.c head:\n${mainC.take(2000)}",
        )
    }
}
