/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * Copyright (c) 2026 Michal Svacha
 */
package io.github.gbkt.backend.gbdk.codegen.pipeline

import io.github.gbkt.core.ir.Cartridge
import io.github.gbkt.core.ir.CartridgeConfig
import io.github.gbkt.core.ir.GameIR
import io.github.gbkt.core.ir.GbcTarget
import io.github.gbkt.core.ir.MetaspriteFrame
import io.github.gbkt.core.ir.MetaspriteIR
import io.github.gbkt.core.ir.MetaspriteTile
import io.github.gbkt.core.ir.SceneIR
import kotlin.test.Test
import kotlin.test.assertTrue

// =============================================================================
// SEED-004 ELEPHANT TILE RENDERING -- DIAGNOSTIC TEST (PLAN 10.1-10)
//
// Per D-V1 diagnostic finding (sprite-mode-init-finding.md):
// The metasprites example renders garbled tiles because of a sprite-mode
// mismatch across the gbkt pipeline. One of the two required fixes (Edit 2
// per the finding) is to emit `SPRITES_8x8;` between `cgb_compatibility();`
// and `DISPLAY_ON;` in main() when the GameIR contains at least one
// metasprite.
//
// This test locks the runtime side of the fix. It is RED at Plan 10.1-10's
// close (port currently emits neither SPRITES_8x8 nor SPRITES_8x16 between
// cgb_compatibility() and DISPLAY_ON) and Plan 10.1-11 will turn it GREEN.
//
// Scope -- intentionally NOT exhaustive:
//   - Only locks the runtime-side macro emission (Edit 2).
//   - The asset-pipeline-side fix (Edit 1: ConvertSpritesTask -spr8x8) is
//     locked by a separate test added in Plan 11.
//   - All three locks together (this test + asset-pipeline test + UAT
//     screenshot in Plan 13) close out D-V1.
// =============================================================================

class Seed004ElephantTileRenderingDiagnosticTest {

    private val pipeline = GBDKPipeline()

    // -------------------------------------------------------------------------
    // Build a minimal GameIR with at least one metasprite. Mirrors the shape
    // used by GbcCompatEmissionTest's `buildGbcCompatGameIR(..., withMetasprites = true)`.
    // -------------------------------------------------------------------------
    private fun buildGameIrWithMetasprite(): GameIR =
        GameIR(
            name = "Seed004Diagnostic",
            config =
                CartridgeConfig(
                    cartridge = Cartridge.ROM_ONLY,
                    romBanks = 2,
                    gbcTarget = GbcTarget.GBC_COMPATIBLE,
                ),
            scenes = listOf(SceneIR(id = "play")),
            startScene = "play",
            metasprites =
                listOf(
                    MetaspriteIR(
                        id = "elephant",
                        frames =
                            listOf(
                                MetaspriteFrame(
                                    tiles =
                                        listOf(
                                            MetaspriteTile(relX = 0, relY = 0, tileId = 0),
                                            MetaspriteTile(relX = 8, relY = 0, tileId = 1),
                                        )
                                )
                            ),
                    )
                ),
        )

    // -------------------------------------------------------------------------
    // The single diagnostic assertion.
    //
    // Reads `main.c`, finds the position of `cgb_compatibility();`, `SPRITES_8x8;`,
    // and `DISPLAY_ON;`, then asserts the three positions are strictly ordered:
    //   cgbIdx < spritesIdx < displayIdx
    //
    // At Plan 10.1-10 close: `SPRITES_8x8;` is absent => `spritesIdx == -1` =>
    // the strict-ordering assertion fails with a precise diagnostic message
    // naming the missing macro. That RED is the named-root-cause anchor.
    //
    // After Plan 10.1-11's Edit 2 lands: the macro is emitted between the two
    // bookends and the test flips to GREEN.
    // -------------------------------------------------------------------------
    @Test
    fun main_c_emits_SPRITES_8x8_between_cgb_compatibility_and_DISPLAY_ON_when_metasprites_declared() {
        val gameIR = buildGameIrWithMetasprite()
        val mainSource =
            pipeline.generate(gameIR).files["main.c"]
                ?: error("main.c not generated by GBDKPipeline")

        val cgbIdx = mainSource.indexOf("cgb_compatibility();")
        val spritesIdx = mainSource.indexOf("SPRITES_8x8;")
        val displayIdx = mainSource.indexOf("DISPLAY_ON;")

        assertTrue(
            cgbIdx >= 0 &&
                spritesIdx >= 0 &&
                displayIdx >= 0 &&
                cgbIdx < spritesIdx &&
                spritesIdx < displayIdx,
            buildString {
                appendLine(
                    "Expected SPRITES_8x8; to appear strictly between cgb_compatibility(); " +
                        "and DISPLAY_ON; in main.c when GameIR contains metasprites."
                )
                appendLine("  cgb_compatibility(); index: $cgbIdx")
                appendLine("  SPRITES_8x8;         index: $spritesIdx")
                appendLine("  DISPLAY_ON;          index: $displayIdx")
                appendLine(
                    "  (index = -1 means the substring was not found; per the D-V1 finding " +
                        "this is the expected RED state until Plan 10.1-11 lands Edit 2 in " +
                        "GBDKPipeline.buildMainFunction.)"
                )
            },
        )
    }
}
