/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * Copyright (c) 2026 Michal Svacha
 */
package io.github.gbkt.backend.gbdk.codegen.pipeline

import io.github.gbkt.core.ir.Cartridge
import io.github.gbkt.core.ir.CartridgeConfig
import io.github.gbkt.core.ir.GameIR
import io.github.gbkt.core.ir.GbcTarget
import io.github.gbkt.core.ir.SceneIR
import kotlin.test.Test
import kotlin.test.assertFalse

// =============================================================================
// SEED-004 ELEPHANT TILE RENDERING -- FIX REGRESSION GUARD (PLAN 10.1-11)
//
// Per D-V1 diagnostic finding (sprite-mode-init-finding.md) and Plan 11
// <threat_model> mitigation (1): "Unconditional emission breaks non-metasprite
// games -- mitigation: gameIR.metasprites.isNotEmpty() gate + negative-case
// test in non-metasprite examples (pong, breakout, simple-physics)."
//
// This test is the JVM-tier negative-case regression guard for Edit 2 (runtime
// emission). It locks the conditional gate `if (gameIR.metasprites.isNotEmpty())`
// in GBDKPipeline.buildMainFunction so that a future regression that drops
// the gate (and unconditionally emits `SPRITES_8x8;` for ALL games) is caught.
//
// Why this test (paired with the existing positive-case
// `Seed004ElephantTileRenderingDiagnosticTest`):
//   - Diagnostic test (Plan 10) locks: WHEN metasprites are present, emit
//     SPRITES_8x8; in the correct position (RED -> GREEN in Task 2).
//   - This test locks: WHEN metasprites are absent, DO NOT emit SPRITES_8x8;
//     (passes trivially pre-Task 2, continues to pass post-Task 2 because the
//     conditional gate evaluates `false` for empty metasprite list).
//   - Together they pin down a two-sided contract that no future change can
//     break silently in either direction.
// =============================================================================

class Seed004ElephantTileRenderingFixTest {

    private val pipeline = GBDKPipeline()

    // -------------------------------------------------------------------------
    // Build a minimal GameIR with NO metasprites. Mirrors the shape used by
    // GbcCompatEmissionTest's `buildGbcCompatGameIR(..., withMetasprites = false)`
    // (which is the default). Non-metasprite games (Pong, Breakout,
    // simple-physics) match this shape -- no metasprites, no metasprite IR.
    // -------------------------------------------------------------------------
    private fun buildGameIrWithoutMetasprites(): GameIR =
        GameIR(
            name = "Seed004NegativeCase",
            config =
                CartridgeConfig(
                    cartridge = Cartridge.ROM_ONLY,
                    romBanks = 2,
                    gbcTarget = GbcTarget.GBC_COMPATIBLE,
                ),
            scenes = listOf(SceneIR(id = "play")),
            startScene = "play",
            // metasprites = emptyList() by default
        )

    // -------------------------------------------------------------------------
    // The single regression-guard assertion.
    //
    // Reads `main.c` and asserts that the substring `SPRITES_8x8;` is NOT
    // present anywhere in the file when the GameIR has zero metasprites.
    //
    // Pre-Task 2 (Plan 10.1-11): trivially passes -- no SPRITES_8x8 anywhere
    // in main.c (Edit 2 has not landed yet).
    //
    // Post-Task 2: continues to pass -- the conditional gate
    // `if (gameIR.metasprites.isNotEmpty())` evaluates `false` for empty
    // metasprite list, so SPRITES_8x8; is not emitted.
    //
    // A regression that drops the gate (e.g., a refactor that hoists
    // SPRITES_8x8; out of the `if` block to "simplify" main(), or a
    // copy-paste mistake) would flip this test RED and surface the defect at
    // the JVM tier before any ROM build, before any UAT screenshot, before any
    // user-visible regression in Pong/Breakout/etc.
    // -------------------------------------------------------------------------
    @Test
    fun main_c_does_not_emit_SPRITES_8x8_when_no_metasprites_declared() {
        val gameIR = buildGameIrWithoutMetasprites()
        val mainSource =
            pipeline.generate(gameIR).files["main.c"]
                ?: error("main.c not generated by GBDKPipeline")

        assertFalse(
            mainSource.contains("SPRITES_8x8;"),
            buildString {
                appendLine("Expected NO `SPRITES_8x8;` in main.c when GameIR has zero metasprites.")
                appendLine(
                    "The conditional gate `if (gameIR.metasprites.isNotEmpty())` in " +
                        "GBDKPipeline.buildMainFunction MUST evaluate `false` for an empty " +
                        "metasprite list, otherwise non-metasprite games (Pong, Breakout, " +
                        "simple-physics) will receive an unwanted runtime sprite-mode switch."
                )
                appendLine(
                    "If this test is RED, a regression has dropped the gate. Restore the " +
                        "conditional per Plan 10.1-11 Edit 2 (see " +
                        "evidence/d-v1-diagnostic/sprite-mode-init-finding.md)."
                )
            },
        )
    }
}
