/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * Copyright (c) 2026 Michal Svacha
 */
package io.github.gbkt.backend.gbdk.codegen.pipeline

import io.github.gbkt.core.ir.Cartridge
import io.github.gbkt.core.ir.CartridgeConfig
import io.github.gbkt.core.ir.GameIR
import io.github.gbkt.core.ir.GbcTarget
import io.github.gbkt.core.ir.MetaspriteFrame
import io.github.gbkt.core.ir.MetaspriteIR
import io.github.gbkt.core.ir.MetaspriteTile
import io.github.gbkt.core.ir.SceneIR
import io.github.gbkt.core.ir.SpriteMode
import kotlin.test.Test
import kotlin.test.assertFalse
import kotlin.test.assertTrue

// =============================================================================
// SPR8x16 HARDWARE MODE EMISSION TEST -- Debug session E-02
// (debug/platformer-duck-malformed-blob.md)
//
// Asserts the runtime-side hardware-sprite-mode contract: when a metasprite
// declares `spriteMode = SpriteMode.SPR8x16` (the platformer-template duck
// case), main() MUST emit `SPRITES_8x16;` (NOT `SPRITES_8x8;`) between
// `cgb_compatibility();` and `DISPLAY_ON;`.
//
// Pre-fix (E-02 RED): GBDKPipeline.buildMainFunction unconditionally emitted
// `SPRITES_8x8;` for ALL metasprite games. The elephant example uses SPR8x8
// (correct). The platformer template uses SPR8x16, but the hardware was forced
// into 8x8 mode — each metasprite OAM entry rendered a single 8x8 tile instead
// of an 8x16 pair. Combined with E-03 (frame coord swap) this produced the
// "duck blob" symptom.
//
// Post-fix (E-02 GREEN): the macro is selected from the metasprite spriteMode
// field. SPR8x16 → SPRITES_8x16 macro; SPR8x8 (or null for back-compat with the
// elephant example) → SPRITES_8x8 macro.
//
// Pairs with `Seed004ElephantTileRenderingDiagnosticTest` (elephant SPR8x8
// positive case) and `Seed004ElephantTileRenderingFixTest` (no-metasprite
// negative case). Together the three tests pin down a three-sided contract:
//   - No metasprites             → neither macro emitted
//   - SPR8x8 metasprite          → SPRITES_8x8 emitted
//   - SPR8x16 metasprite present → SPRITES_8x16 emitted
// =============================================================================

class SpriteMode8x16HardwareModeTest {

    private val pipeline = GBDKPipeline()

    /**
     * Build a minimal GameIR with one metasprite declaring `spriteMode = SPR8x16`. Mirrors the
     * shape used by the platformer-template (player duck): 24×32 sprite cut from a PNG with the
     * SPR8x16 png2asset flag. Tile content is irrelevant to this test — only the spriteMode
     * field drives the hardware-mode-macro selection.
     */
    private fun buildGameIrWithSpr8x16Metasprite(): GameIR =
        GameIR(
            name = "Spr8x16Test",
            config =
                CartridgeConfig(
                    cartridge = Cartridge.ROM_ONLY,
                    romBanks = 2,
                    gbcTarget = GbcTarget.GBC_COMPATIBLE,
                ),
            scenes = listOf(SceneIR(id = "play")),
            startScene = "play",
            metasprites =
                listOf(
                    MetaspriteIR(
                        id = "duck",
                        frames =
                            listOf(
                                MetaspriteFrame(
                                    tiles =
                                        listOf(
                                            MetaspriteTile(relX = -12, relY = -6, tileId = 0),
                                            MetaspriteTile(relX = 8, relY = 0, tileId = 2),
                                        )
                                )
                            ),
                        spriteMode = SpriteMode.SPR8x16,
                        pivotX = 12,
                        pivotY = 6,
                        frameWidth = 24,
                        frameHeight = 32,
                    )
                ),
        )

    @Test
    fun `main_c emits SPRITES_8x16 between cgb_compatibility and DISPLAY_ON when SPR8x16 metasprite declared`() {
        val gameIR = buildGameIrWithSpr8x16Metasprite()
        val mainSource =
            pipeline.generate(gameIR).files["main.c"]
                ?: error("main.c not generated by GBDKPipeline")

        val cgbIdx = mainSource.indexOf("cgb_compatibility();")
        val spritesIdx = mainSource.indexOf("SPRITES_8x16;")
        val displayIdx = mainSource.indexOf("DISPLAY_ON;")

        assertTrue(
            cgbIdx >= 0 &&
                spritesIdx >= 0 &&
                displayIdx >= 0 &&
                cgbIdx < spritesIdx &&
                spritesIdx < displayIdx,
            buildString {
                appendLine(
                    "Expected SPRITES_8x16; to appear strictly between cgb_compatibility(); " +
                        "and DISPLAY_ON; in main.c when a metasprite declares spriteMode = SPR8x16."
                )
                appendLine("  cgb_compatibility(); index: $cgbIdx")
                appendLine("  SPRITES_8x16;        index: $spritesIdx")
                appendLine("  DISPLAY_ON;          index: $displayIdx")
                appendLine(
                    "  Pre-E-02-fix expected RED: pipeline unconditionally emitted SPRITES_8x8; " +
                        "for all metasprite games. Post-E-02-fix expected GREEN: SPR8x16 metasprite " +
                        "spriteMode field selects SPRITES_8x16."
                )
            },
        )
    }

    @Test
    fun `main_c does not emit SPRITES_8x8 when SPR8x16 metasprite is the only metasprite`() {
        val gameIR = buildGameIrWithSpr8x16Metasprite()
        val mainSource =
            pipeline.generate(gameIR).files["main.c"]
                ?: error("main.c not generated by GBDKPipeline")

        // Pre-E-02-fix this would be RED — pipeline unconditionally emitted SPRITES_8x8.
        // Post-fix the SPR8x16 metasprite branch selects SPRITES_8x16 and never SPRITES_8x8.
        assertFalse(
            mainSource.contains("SPRITES_8x8;"),
            buildString {
                appendLine(
                    "Expected NO `SPRITES_8x8;` in main.c when the only metasprite declares " +
                        "spriteMode = SPR8x16. Hardware sprite size is a single LCDC bit; emitting " +
                        "SPRITES_8x8 forces each metasprite OAM entry to render as a single 8×8 " +
                        "tile instead of an 8×16 pair (the platformer 'duck blob' symptom)."
                )
            },
        )
    }
}
