// Generated by gbkt
#pragma bank 1

#include <stdio.h>
#include <gbdk/console.h>
#include "game.h"

// Scene: gameover
void gameover_enter(void) BANKED {
    HIDE_SPRITES;
    cls();
    {
        gotoxy(5u, 6u);
        printf("GAME OVER");
    }
    {
        gotoxy(3u, 9u);
        printf("HP: 0  GOLD: %d", _gold);
    }
    {
        gotoxy(5u, 13u);
        printf("PRESS START");
    }
}

void gameover_frame(void) BANKED {
    if (button_pressed(J_START)) {
        navigate_to_scene(SCENE_TITLE);
    }
}

// Scene: dungeon
void dungeon_enter(void) BANKED {
    SHOW_SPRITES;
    cls();
    {
        gotoxy(3u, 1u);
        printf("DUNGEON LV:%d", _dungeonLevel);
    }
    {
        gotoxy(2u, 3u);
        printf("HP:%d  GOLD:%d", _hp, _gold);
    }
    _stepCount = 0u;
}

void dungeon_frame(void) BANKED {
    if (button_held(J_UP)) {
        if (_heroActor_y > 16u) {
            {
                _heroActor_y += -2;
            }
        }
    }
    if (button_held(J_DOWN)) {
        if (_heroActor_y < 128u) {
            {
                _heroActor_y += 2u;
            }
        }
    }
    if (button_held(J_LEFT)) {
        if (_heroActor_x > 8u) {
            {
                _heroActor_x += -2;
            }
        }
    }
    if (button_held(J_RIGHT)) {
        if (_heroActor_x < 152u) {
            {
                _heroActor_x += 2u;
            }
        }
    }
    if (dpad_any()) {
        _stepCount += 1u;
    }
    if (_stepCount >= 60u) {
        _stepCount = 0u;
        play_sound_hitSfx();
        trigger_combat();
    }
    if (_heroActor_x >= 152u) {
        _dungeonLevel += 1u;
        _gold += 3u;
        play_sound_coinSfx();
        {
            _heroActor_x = 8u;
            _heroActor_y = 72u;
        }
    }
    if (button_pressed(J_START)) {
        navigate_to_scene(SCENE_TOWN);
    }
    if (_hp == 0u) {
        play_sound_loseSfx();
        navigate_to_scene(SCENE_GAMEOVER);
    }
}

// Scene: town
void town_enter(void) BANKED {
    SHOW_SPRITES;
    cls();
    {
        gotoxy(8u, 2u);
        printf("TOWN");
    }
    {
        gotoxy(2u, 4u);
        printf("HP:%d  GOLD:%d", _hp, _gold);
    }
    {
        gotoxy(2u, 8u);
        printf("A: ENTER DUNGEON");
    }
    {
        gotoxy(2u, 10u);
        printf("START: HEAL (5G)");
    }
    {
        _heroActor_x = 80u;
        _heroActor_y = 72u;
    }
}

void town_frame(void) BANKED {
    if (button_pressed(J_START)) {
        if (_gold >= 5u) {
            if (_hp < 30u) {
                _gold -= 5u;
                _hp += 10u;
                play_sound_coinSfx();
            }
        }
    }
    if (button_pressed(J_A)) {
        navigate_to_scene(SCENE_DUNGEON);
    }
}

// Scene: title
void title_enter(void) BANKED {
    HIDE_SPRITES;
    cls();
    {
        gotoxy(6u, 5u);
        printf("RPG LITE");
    }
    {
        gotoxy(2u, 8u);
        printf("A MINI ADVENTURE");
    }
    {
        gotoxy(5u, 12u);
        printf("PRESS START");
    }
}

void title_frame(void) BANKED {
    if (button_pressed(J_START)) {
        _hp = 30u;
        _gold = 0u;
        _dungeonLevel = 1u;
        _stepCount = 0u;
        navigate_to_scene(SCENE_TOWN);
    }
}
