// Generated by gbkt
#ifndef GAME_H
#define GAME_H

#include <gb/gb.h>
#include <stdio.h>
#include <gbdk/console.h>

#define SCENE_GAMEOVER 0
#define SCENE_DUNGEON 1
#define SCENE_TOWN 2
#define SCENE_TITLE 3
#define _COMBAT_STATE_INIT 0
#define _COMBAT_STATE_PLAYER_TURN 1
#define _COMBAT_STATE_ENEMY_TURN 2
#define _COMBAT_STATE_VICTORY 3
#define _COMBAT_STATE_DEFEAT 4
#define _COMBAT_STATE_TARGET_SELECT 5
#define _COMBAT_STATE_EXECUTE_ACTION 6
#define _COMBAT_STATE_FLEEING 7
#define _COMBAT_STATE_WAITING 8

extern UINT8 _heroActor_x;
extern UINT8 _heroActor_y;
extern UINT8 _hp;
extern UINT8 _gold;
extern UINT8 _dungeonLevel;
extern UINT8 _stepCount;
extern UINT8 __joypad;
extern UINT8 __joypad_prev;
extern UINT8 _sound_channels[4];
extern UINT8 _sound_priority[4];
extern UINT8 _sound_duration[4];
extern UINT8 _combat_state_combat;
extern UINT8 _pending_state_combat;
extern UINT8 current_scene;
extern UINT8 _wait_counter;
extern UINT8 _char_active_sp;
extern UINT8 _combat_target_idx;
extern UINT8 _combat_active_enemy_idx;
extern UINT8 _combat_active_ally_idx;
extern UINT8 _combat_target_all_enemies;
extern UINT8 _combat_target_all_allies;
extern UINT8 _combat_target_all;
extern UINT8 _dialog_speed;
extern UINT8 _current_tileset_id;
extern UINT8 _char_hero_hp;
extern UINT8 _char_hero_sp;
extern UINT8 _char_hero_atk;
extern UINT8 _char_hero_def;
extern UINT8 _char_hero_matk;
extern UINT8 _char_hero_mdef;
extern UINT8 _char_hero_agl;
extern UINT8 _char_hero_level;
extern UINT16 _char_hero_exp;
extern UINT8 _combat_difficulty;
extern UINT8 _player_level;
extern UINT8 _char_target_hp;
extern UINT8 _mon_slime_hp_pct;
extern UINT8 _mon_bat_hp_pct;

// Scene: gameover
void gameover_enter(void) BANKED;

void gameover_frame(void) BANKED;

// Scene: dungeon
void dungeon_enter(void) BANKED;

void dungeon_frame(void) BANKED;

// Scene: town
void town_enter(void) BANKED;

void town_frame(void) BANKED;

// Scene: title
void title_enter(void) BANKED;

void title_frame(void) BANKED;

// Input helpers (joypad polling with edge detection)
void update_joypad(void);

UINT8 button_pressed(UINT8 mask);

UINT8 button_held(UINT8 mask);

UINT8 button_held(UINT8 mask);

UINT8 button_pressed(UINT8 mask);

UINT8 button_released(UINT8 mask);

UINT8 button_released(UINT8 mask);

UINT8 dpad_any(void);

// Timing helpers (blocking busy-wait)
void delay_frames(UINT8 n);

// Sprite helpers (real OAM management)
void hide_sprites_range(UINT8 from, UINT8 to);

void show_sprites_range(UINT8 from, UINT8 to);

// Sprite OAM sync (called every frame)
void update_sprites(void);

// Sound driver (channel allocation with priority preemption)
void sound_driver_update(void);

void play_sound(UINT8 sound_id, UINT8 channel, UINT8 priority, UINT8 duration);

void play_sound_coinSfx(void);

void play_sound_hitSfx(void);

void play_sound_loseSfx(void);

void play_sound_winSfx(void);

// Dialog helpers (window layer rendering)
void _win_print_at(UINT8 x, UINT8 y, const UINT8* str, UINT8 len);

void _win_clear_region(UINT8 x, UINT8 y, UINT8 w, UINT8 h);

void _win_fill_screen(UINT8 tile);

// Fade helpers (palette-based screen fade)
void fade_out(void);

void fade_in(void);

// RPG ability: Fireball
void use_ability_fireball(void);

void combat_request_state_combat(UINT8 s);

void update_combat_combat(void);

UINT8 combat_is_in_state_combat(UINT8 state);

void trigger_combat(void);

// Combat engine stubs
void monster_basic_attack(void);

void monster_flee(void);

UINT8 find_lowest_hp_target(void);

// Trampoline: gameover_enter (bank 1)
void gameover_enter_trampoline(void);

void gameover_frame_trampoline(void);

// Trampoline: dungeon_enter (bank 1)
void dungeon_enter_trampoline(void);

void dungeon_frame_trampoline(void);

// Trampoline: town_enter (bank 1)
void town_enter_trampoline(void);

void town_frame_trampoline(void);

// Trampoline: title_enter (bank 1)
void title_enter_trampoline(void);

void title_frame_trampoline(void);

// Scene navigation
void navigate_to_scene(UINT8 scene);

#endif // GAME_H
