/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * Copyright (c) 2026 Michal Svacha
 */
package io.github.gbkt.rpg.domain

import io.github.gbkt.core.ir.CombatStateId

// =============================================================================
// PREDEFINED COMBAT STATE CONSTANTS
// =============================================================================

/**
 * Predefined [CombatStateId] constants for the standard turn-based combat state machine.
 *
 * These constants replace magic string literals in game code. Use them in [combatIsInState] calls
 * to get compile-time safety for combat state checks.
 *
 * Usage:
 * ```kotlin
 * scene("battle") {
 *     every.frame {
 *         battleUpdate(combat)
 *         runIf(combatIsInState(CombatStates.VICTORY)) {
 *             navigate(victoryScene)
 *         }
 *         runIf(combatIsInState(CombatStates.DEFEAT)) {
 *             navigate(gameOverScene)
 *         }
 *     }
 * }
 * ```
 *
 * The underlying string IDs correspond to the C constants generated by [CombatVisitor] for the
 * combat state machine: `COMBAT_STATE_INIT`, `COMBAT_STATE_PLAYER_TURN`, etc.
 */
object CombatStates {
    /** Combat has been initialized but no turn has started yet. */
    val INIT = CombatStateId("COMBAT_STATE_INIT")

    /** Waiting for the player to select an action. */
    val PLAYER_TURN = CombatStateId("COMBAT_STATE_PLAYER_TURN")

    /** Player is selecting a target for the chosen action. */
    val TARGET_SELECT = CombatStateId("COMBAT_STATE_TARGET_SELECT")

    /** The selected action is being executed (animation, damage calc). */
    val EXECUTE_ACTION = CombatStateId("COMBAT_STATE_EXECUTE_ACTION")

    /** Enemy AI is selecting and executing an action. */
    val ENEMY_TURN = CombatStateId("COMBAT_STATE_ENEMY_TURN")

    /** All enemies have been defeated. Victory ops are executed. */
    val VICTORY = CombatStateId("COMBAT_STATE_VICTORY")

    /** All player characters have been defeated. Defeat ops are executed. */
    val DEFEAT = CombatStateId("COMBAT_STATE_DEFEAT")

    /** Player has chosen the Run action and escape roll is in progress. */
    val FLEEING = CombatStateId("COMBAT_STATE_FLEEING")

    /** Waiting for a dialog/animation to complete before advancing state. */
    val WAITING = CombatStateId("COMBAT_STATE_WAITING")
}
