// Generated by gbkt
#pragma bank 1

#include <stdio.h>
#include <gbdk/console.h>
#include "game.h"

// Scene: results
void results_enter(void) BANKED {
    HIDE_SPRITES;
    cls();
    {
        gotoxy(4u, 4u);
        printf("RACE COMPLETE");
    }
    {
        gotoxy(4u, 7u);
        printf("POSITION: %d", _position);
    }
    {
        gotoxy(4u, 9u);
        printf("TIME: %d", _raceTime);
    }
    {
        gotoxy(5u, 13u);
        printf("PRESS START");
    }
}

void results_frame(void) BANKED {
    if (button_pressed(J_START)) {
        _raceTime = 0u;
        _position = 1u;
        navigate_to_scene(SCENE_TITLE);
    }
}

// Scene: race
void race_enter(void) BANKED {
    _camera_target = 0u;
    set_bkg_data(0, 3, _racing_track1_tileset);
    _bkg_tiles_load_banked(2u, 0, 0, 19u, 19u, _zone_track1_tiles);
    DISPLAY_ON;
    _current_tileset_id = 1u;
    pool_carAi_spawn(80u, 96u);
    {
        HIDE_SPRITES;
        _win_clear_region(0u, 0u, 20u, 18u);
    }
    SHOW_SPRITES;
    _raceTime = 0u;
    _position = 1u;
    _win_print_at(1u, 1u, "LAP:", 4u);
}

void race_frame(void) BANKED {
    racing_tick_track1();
    _raceTime += 1u;
    if (_racing_lap_count_track1 >= 3u) {
        play_sound_winSfx();
        navigate_to_scene(SCENE_RESULTS);
    }
}

// Scene: title
void title_enter(void) BANKED {
    HIDE_SPRITES;
    cls();
    {
        gotoxy(8u, 5u);
        printf("RACER");
    }
    {
        gotoxy(3u, 8u);
        printf("TOP-DOWN RACING");
    }
    {
        gotoxy(5u, 12u);
        printf("PRESS START");
    }
    {
        gotoxy(4u, 14u);
        printf("3 LAPS TO WIN");
    }
}

void title_frame(void) BANKED {
    if (button_pressed(J_START)) {
        navigate_to_scene(SCENE_RACE);
    }
}
