// Generated by gbkt
#ifndef GAME_H
#define GAME_H

#include <gb/gb.h>
#include <stdio.h>
#include <gbdk/console.h>

#define SCENE_RESULTS 0
#define SCENE_RACE 1
#define SCENE_TITLE 2

extern UINT8 _car_x;
extern UINT8 _car_y;
extern UINT8 _rival_x;
extern UINT8 _rival_y;
extern UINT8 _raceTime;
extern UINT8 _position;
extern UINT8 __joypad;
extern UINT8 __joypad_prev;
extern UINT8 _sound_channels[4];
extern UINT8 _sound_priority[4];
extern UINT8 _sound_duration[4];
extern const UINT8 _zone_track1_tiles[361];
extern UINT8 current_scene;
extern UINT8 _wait_counter;
extern UINT8 _pool_carAi_active[1];
extern UINT8 _pool_carAi_x[1];
extern UINT8 _pool_carAi_y[1];
extern UINT8 _pool_carAi_oam[1];
extern UINT8 _camera_x;
extern UINT8 _camera_y;
extern UINT8 _camera_target;
extern UINT8 _camera_shake_intensity;
extern UINT8 _camera_shake_timer;
extern UINT8 _vehicle_carPlayer_speed_cur;
extern UINT8 _vehicle_carPlayer_heading;
extern UINT8 _racing_lap_count_track1;
extern UINT8 _racing_visited_track1;
extern UINT8 _racing_checkpoint_idx_track1;
extern UINT8 _racing_cp_x_track1[2];
extern UINT8 _racing_cp_y_track1[2];
extern UINT8 _racing_wp_x_track1[4];
extern UINT8 _racing_wp_y_track1[4];
extern UINT8 _pool_carAi_wp_idx[1];
extern UINT8 _pool_carAi_speed_cur[1];
extern UINT8 _pool_carAi_heading[1];
extern const UINT8 _racing_track1_tileset[48];
extern UINT8 _dialog_speed;
extern UINT8 _current_tileset_id;

// Scene: results
void results_enter(void) BANKED;

void results_frame(void) BANKED;

// Scene: race
void race_enter(void) BANKED;

void race_frame(void) BANKED;

// Scene: title
void title_enter(void) BANKED;

void title_frame(void) BANKED;

// Input helpers (joypad polling with edge detection)
void update_joypad(void);

UINT8 button_pressed(UINT8 mask);

UINT8 button_held(UINT8 mask);

UINT8 button_held(UINT8 mask);

UINT8 button_pressed(UINT8 mask);

UINT8 button_released(UINT8 mask);

UINT8 button_released(UINT8 mask);

UINT8 dpad_any(void);

// Timing helpers (blocking busy-wait)
void delay_frames(UINT8 n);

// Sprite helpers (real OAM management)
void hide_sprites_range(UINT8 from, UINT8 to);

void show_sprites_range(UINT8 from, UINT8 to);

// Sprite OAM sync (called every frame)
void update_sprites(void);

// Sound driver (channel allocation with priority preemption)
void sound_driver_update(void);

void play_sound(UINT8 sound_id, UINT8 channel, UINT8 priority, UINT8 duration);

void play_sound_lapSfx(void);

void play_sound_winSfx(void);

// Dialog helpers (window layer rendering)
void _win_print_at(UINT8 x, UINT8 y, const UINT8* str, UINT8 len);

void _win_clear_region(UINT8 x, UINT8 y, UINT8 w, UINT8 h);

void _win_fill_screen(UINT8 tile);

// Fade helpers (palette-based screen fade)
void fade_out(void);

void fade_in(void);

// Actor pool: carAi (max=1, oamBase=4, tilesPerEntity=2)
void pool_carAi_init(void);

UINT8 pool_carAi_spawn(UINT8 x, UINT8 y);

void pool_carAi_destroy(UINT8 i);

// Actor pool active count: carAi
UINT8 pool_carAi_active_count(void);

// Camera system: camera
void update_camera_camera(void);

// Racing system: track1 — per-frame physics + lap state machine
void racing_tick_track1(void);

// Racing system: track1 — finish/lap detection
void racing_check_finish_track1(void);

// Plan 07.4-30 / D-N-SWITCHROM-RESTORE: HOME-bank SWITCH_ROM wrapper
void _bkg_tiles_load_banked(UINT8 bank, UINT8 x, UINT8 y, UINT8 w, UINT8 h, const UINT8* tiles);

// Trampoline: results_enter (bank 1)
void results_enter_trampoline(void);

void results_frame_trampoline(void);

// Trampoline: race_enter (bank 1)
void race_enter_trampoline(void);

void race_frame_trampoline(void);

// Trampoline: title_enter (bank 1)
void title_enter_trampoline(void);

void title_frame_trampoline(void);

// Scene navigation
void navigate_to_scene(UINT8 scene);

#endif // GAME_H
