// Generated by gbkt

#include <gb/gb.h>
#include <stdio.h>
#include <stdlib.h>
#include <gbdk/console.h>
#include "game.h"
#include "sprites/car.h"

#define SCENE_RESULTS 0
#define SCENE_RACE 1
#define SCENE_TITLE 2
#define TILESET_TRACK1 1

UINT8 _car_x = 80u;
UINT8 _car_y = 80u;
UINT8 _rival_x = 80u;
UINT8 _rival_y = 96u;
UINT8 _raceTime = 0u;
UINT8 _position = 1u;
UINT8 __joypad = 0u;
UINT8 __joypad_prev = 0u;
UINT8 _sound_channels[4] = {0xFF, 0xFF, 0xFF, 0xFF};
UINT8 _sound_priority[4] = {0, 0, 0, 0};
UINT8 _sound_duration[4] = {0, 0, 0, 0};
UINT8 _camera_x = 0u;
UINT8 _camera_y = 0u;
UINT8 _camera_target = 0xFF;
UINT8 _camera_shake_intensity = 0u;
UINT8 _camera_shake_timer = 0u;
UINT8 _vehicle_carPlayer_speed_cur = 0u;
UINT8 _vehicle_carPlayer_heading = 0u;
UINT8 _racing_lap_count_track1 = 0u;
UINT8 _racing_visited_track1 = 0u;
UINT8 _racing_checkpoint_idx_track1 = 0u;
UINT8 _racing_cp_x_track1[2] = {40u, 120u};
UINT8 _racing_cp_y_track1[2] = {40u, 120u};
UINT8 _racing_wp_x_track1[4] = {40u, 120u, 120u, 40u};
UINT8 _racing_wp_y_track1[4] = {40u, 40u, 120u, 120u};
UINT8 _pool_carAi_wp_idx[1] = {0u};
UINT8 _pool_carAi_speed_cur[1] = {0u};
UINT8 _pool_carAi_heading[1] = {0u};
const UINT8 _racing_track1_tileset[48] = { 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0xFF, 0x00, 0xFF, 0x00, 0xFF, 0x00, 0xFF, 0x00, 0xFF, 0x00, 0xFF, 0x00, 0xFF, 0x00, 0x00, 0xAA, 0x00, 0x55, 0x00, 0xAA, 0x00, 0x55, 0x00, 0xAA, 0x00, 0x55, 0x00, 0xAA, 0x00, 0x55 };
UINT8 _dialog_speed = 1u;
UINT8 current_scene = SCENE_TITLE;
UINT8 _wait_counter = 0u;
UINT8 _current_tileset_id = 0xFF;
UINT8 _pool_carAi_active[1];
UINT8 _pool_carAi_x[1];
UINT8 _pool_carAi_y[1];
UINT8 _pool_carAi_oam[1];

// Input helpers (joypad polling with edge detection)
void update_joypad(void) {
    __joypad_prev = __joypad;
    __joypad = joypad();
}

UINT8 button_pressed(UINT8 mask) {
    return __joypad & mask & ~(__joypad_prev & mask);
}

UINT8 button_held(UINT8 mask) {
    return __joypad & mask;
}

/* Deduplicated: see button_held */

/* Deduplicated: see button_pressed */

UINT8 button_released(UINT8 mask) {
    return (~__joypad & mask) & __joypad_prev & mask;
}

/* Deduplicated: see button_released */

UINT8 dpad_any(void) {
    return __joypad & (J_UP|J_DOWN|J_LEFT|J_RIGHT);
}

// Timing helpers (blocking busy-wait)
void delay_frames(UINT8 n) {
    UINT8 _d;
    for (; _d < n; _d++) {
        wait_vbl_done();
    }
}

// Sprite helpers (real OAM management)
void hide_sprites_range(UINT8 from, UINT8 to) {
    UINT8 i;
    for (i = from; i < to; i++) {
        move_sprite(i, 0, 0);
    }
}

void show_sprites_range(UINT8 from, UINT8 to) {
    // Sprites shown by moving to valid positions via update_sprites()
}

// Sprite OAM sync (called every frame)
void update_sprites(void) {
    move_sprite(0u, _car_x + 8u, _car_y + 16u);
    move_sprite(1u, _car_x + 8u, _car_y + 24u);
}

// Sound driver (channel allocation with priority preemption)
void sound_driver_update(void) {
    UINT8 ch;
    for (ch = 0u; ch < 4u; ch++) {
        if (_sound_duration[ch] > 0u) {
            --_sound_duration[ch];
            if (_sound_duration[ch] == 0u) {
                _sound_channels[ch] = 255u;
            }
        }
    }
}

void play_sound(UINT8 sound_id, UINT8 channel, UINT8 priority, UINT8 duration) {
    if (_sound_duration[channel] == 0u || priority >= _sound_priority[channel]) {
        _sound_channels[channel] = sound_id;
        _sound_priority[channel] = priority;
        _sound_duration[channel] = duration;
    }
}

void play_sound_lapSfx(void) {
    NR10_REG = 0x00u;
    NR11_REG = 0x94u;
    NR12_REG = 0xE1u;
    NR13_REG = 0x6Cu;
    NR14_REG = 0xC7u;
}

void play_sound_winSfx(void) {
    NR10_REG = 0x00u;
    NR11_REG = 0x80u;
    NR12_REG = 0xF2u;
    NR13_REG = 0xAEu;
    NR14_REG = 0x87u;
}

// Dialog helpers (window layer rendering)
void _win_print_at(UINT8 x, UINT8 y, const UINT8* str, UINT8 len) {
    UINT8 i = 0u;
    for (; i < len; i++) {
        set_win_tiles(x + i, y, 1u, 1u, (unsigned char*)&str[i]);
    }
}

void _win_clear_region(UINT8 x, UINT8 y, UINT8 w, UINT8 h) {
    UINT8 ry = 0u;
    UINT8 rx = 0u;
    UINT8 blank = 0u;
    for (; ry < h; ry++) {
        for (; rx < w; rx++) {
            set_win_tiles(x + rx, y + ry, 1u, 1u, &blank);
        }
    }
}

void _win_fill_screen(UINT8 tile) {
    UINT8 fy = 0u;
    UINT8 fx = 0u;
    for (; fy < 18u; fy++) {
        for (; fx < 20u; fx++) {
            set_win_tiles(fx, fy, 1u, 1u, &tile);
        }
    }
}

// Fade helpers (palette-based screen fade)
void fade_out(void) {
    BGP_REG = 180u;
    OBP0_REG = 180u;
    wait_vbl_done();
    BGP_REG = 108u;
    OBP0_REG = 108u;
    wait_vbl_done();
    BGP_REG = 36u;
    OBP0_REG = 36u;
    wait_vbl_done();
    BGP_REG = 0u;
    OBP0_REG = 0u;
    wait_vbl_done();
}

void fade_in(void) {
    BGP_REG = 36u;
    OBP0_REG = 36u;
    wait_vbl_done();
    BGP_REG = 108u;
    OBP0_REG = 108u;
    wait_vbl_done();
    BGP_REG = 180u;
    OBP0_REG = 180u;
    wait_vbl_done();
    BGP_REG = 228u;
    OBP0_REG = 228u;
    wait_vbl_done();
}

// Actor pool: carAi (max=1, oamBase=4, tilesPerEntity=2)
void pool_carAi_init(void) {
    UINT8 i;
    for (i = 0u; i < 1u; i++) {
        _pool_carAi_active[i] = 0u;
        _pool_carAi_oam[i] = 4u + i * 2u;
    }
}

UINT8 pool_carAi_spawn(UINT8 x, UINT8 y) {
    UINT8 i;
    for (i = 0u; i < 1u; i++) {
        if (_pool_carAi_active[i] == 0u) {
            goto pool_carAi_found;
        }
    }
    return 0xFF;
    pool_carAi_found:
    _pool_carAi_x[i] = x;
    _pool_carAi_y[i] = y;
    _pool_carAi_active[i] = 1u;
    move_sprite(_pool_carAi_oam[i], x + 8u, y + 16u);
    move_sprite(_pool_carAi_oam[i] + 1u, x + 8u, y + 24u);
    return i;
}

void pool_carAi_destroy(UINT8 i) {
    if (i >= 1u) {
        return;
    }
    move_sprite(_pool_carAi_oam[i], 0u, 0u);
    move_sprite(_pool_carAi_oam[i] + 1u, 0u, 0u);
    _pool_carAi_active[i] = 0u;
}

// Actor pool active count: carAi
UINT8 pool_carAi_active_count(void) {
    UINT8 count = 0u;
    UINT8 i;
    for (i = 0u; i < 1u; i++) {
        if (_pool_carAi_active[i]) {
            ++count;
        }
    }
    return count;
}

// Camera system: camera
void update_camera_camera(void) {
    INT16 rawX = (INT16)_car_x - 80u;
    INT16 rawY = (INT16)_car_y - 72u;
    _camera_x = (UINT8)((rawX < 0u) ? 0u : (rawX > 0u) ? 0u : rawX);
    _camera_y = (UINT8)((rawY < 0u) ? 0u : (rawY > 8u) ? 8u : rawY);
    if (_camera_shake_timer > 0u) {
        UINT8 offset = (_camera_shake_timer & 1u != 0u) ? _camera_shake_intensity : 0u;
        SCX_REG = _camera_x + offset;
        SCY_REG = _camera_y + offset;
        --_camera_shake_timer;
    } else {
        SCX_REG = _camera_x;
        SCY_REG = _camera_y;
    }
}

// Racing system: track1 — per-frame physics + lap state machine
void racing_tick_track1(void) {
    // C.1 — throttle/steer ramp using player stats (D-07)
    if (button_held(J_UP)) {
        _vehicle_carPlayer_speed_cur = (_vehicle_carPlayer_speed_cur + 11u < 200u) ? _vehicle_carPlayer_speed_cur + 11u : 200u;
    } else {
        if (button_held(J_DOWN)) {
            _vehicle_carPlayer_speed_cur = (_vehicle_carPlayer_speed_cur > 255u) ? _vehicle_carPlayer_speed_cur - 255u : 0u;
        } else {
            _vehicle_carPlayer_speed_cur = (_vehicle_carPlayer_speed_cur > 1u) ? _vehicle_carPlayer_speed_cur - 1u : 0u;
        }
    }
    // C.2 — steer (cardinal: 0=N, 1=E, 2=S, 3=W; rising-edge dpad)
    if (button_pressed(J_LEFT)) {
        _vehicle_carPlayer_heading = _vehicle_carPlayer_heading + 3u & 3u;
    }
    if (button_pressed(J_RIGHT)) {
        _vehicle_carPlayer_heading = _vehicle_carPlayer_heading + 1u & 3u;
    }
    // C.3 — delta = speed_cur >> 5; switch on heading; write back to actor
    UINT8 delta = _vehicle_carPlayer_speed_cur >> 5u;
    INT8 vx = 0u;
    INT8 vy = 0u;
    switch (_vehicle_carPlayer_heading) {
    case 0u:
        vy = -(INT8)delta;
        break;
    case 1u:
        vx = (INT8)delta;
        break;
    case 2u:
        vy = (INT8)delta;
        break;
    case 3u:
        vx = -(INT8)delta;
        break;
    }
    {
    INT16 propXs = (INT16)_car_x + (INT16)vx;
    INT16 propYs = (INT16)_car_y + (INT16)vy;
    if (propXs >= 0 && propXs < 144 && propYs >= 0 && propYs < 136) {
        UINT8 propX = (UINT8)propXs;
        UINT8 propY = (UINT8)propYs;
        if (((((propX) >> 3) < 19u && ((propY) >> 3) < 19u && _zone_track1_tiles[((propY) >> 3) * 19u + ((propX) >> 3)] != 0u) || (((propX + 7u) >> 3) < 19u && ((propY) >> 3) < 19u && _zone_track1_tiles[((propY) >> 3) * 19u + ((propX + 7u) >> 3)] != 0u) || (((propX) >> 3) < 19u && ((propY + 15u) >> 3) < 19u && _zone_track1_tiles[((propY + 15u) >> 3) * 19u + ((propX) >> 3)] != 0u) || (((propX + 7u) >> 3) < 19u && ((propY + 15u) >> 3) < 19u && _zone_track1_tiles[((propY + 15u) >> 3) * 19u + ((propX + 7u) >> 3)] != 0u))) {
            _car_x = propX;
            _car_y = propY;
        }
    }
}
    // C.4 — camera follow (D-06)
    update_camera_camera();
    // C.5 — checkpoint state machine via mask_below (D-15, D-17)
    if (_racing_checkpoint_idx_track1 < 2u) {
        UINT8 cp_x = _racing_cp_x_track1[_racing_checkpoint_idx_track1];
        UINT8 cp_y = _racing_cp_y_track1[_racing_checkpoint_idx_track1];
        UINT8 dx = (_car_x > cp_x) ? _car_x - cp_x : cp_x - _car_x;
        UINT8 dy = (_car_y > cp_y) ? _car_y - cp_y : cp_y - _car_y;
        if (dx < 8u && dy < 8u) {
            UINT8 mask_below = (1u << _racing_checkpoint_idx_track1) - 1u;
            if (_racing_visited_track1 & mask_below == mask_below) {
                _racing_visited_track1 |= (1u << _racing_checkpoint_idx_track1);
                _racing_checkpoint_idx_track1 += 1u;
            }
        }
    }
    UINT8 cp0_x = _racing_cp_x_track1[0u];
    UINT8 cp0_y = _racing_cp_y_track1[0u];
    UINT8 dx0 = (_car_x > cp0_x) ? _car_x - cp0_x : cp0_x - _car_x;
    UINT8 dy0 = (_car_y > cp0_y) ? _car_y - cp0_y : cp0_y - _car_y;
    if (dx0 < 8u && dy0 < 8u && _racing_visited_track1 == 3u) {
        _racing_lap_count_track1 += 1u;
        _racing_visited_track1 = 1u;
        _racing_checkpoint_idx_track1 = 1u;
    }
    // C.6 — AI loop for pool 'carAi' (D-09)
    for (UINT8 i_carAi = 0u; i_carAi < 1u; i_carAi++) {
        if (_pool_carAi_active[i_carAi] == 0u) {
            continue;
        }
        UINT8 tgt_x_carAi = _racing_wp_x_track1[_pool_carAi_wp_idx[i_carAi]];
        UINT8 tgt_y_carAi = _racing_wp_y_track1[_pool_carAi_wp_idx[i_carAi]];
        UINT8 dx_carAi = (_pool_carAi_x[i_carAi] > tgt_x_carAi) ? _pool_carAi_x[i_carAi] - tgt_x_carAi : tgt_x_carAi - _pool_carAi_x[i_carAi];
        UINT8 dy_carAi = (_pool_carAi_y[i_carAi] > tgt_y_carAi) ? _pool_carAi_y[i_carAi] - tgt_y_carAi : tgt_y_carAi - _pool_carAi_y[i_carAi];
        {
    UINT8 ai_primary;
    UINT8 ai_fallback;
    if (dx_carAi >= dy_carAi) {
        ai_primary = (_pool_carAi_x[i_carAi] < tgt_x_carAi) ? 1u : 3u;
        ai_fallback = (_pool_carAi_y[i_carAi] < tgt_y_carAi) ? 2u : 0u;
    } else {
        ai_primary = (_pool_carAi_y[i_carAi] < tgt_y_carAi) ? 2u : 0u;
        ai_fallback = (_pool_carAi_x[i_carAi] < tgt_x_carAi) ? 1u : 3u;
    }
    UINT8 ai_delta_probe = _pool_carAi_speed_cur[i_carAi] >> 5;
    if (ai_delta_probe == 0u) ai_delta_probe = 1u;
    UINT8 cd;
    UINT8 blocked[4];
    for (cd = 0u; cd < 4u; cd++) {
        INT8 pvx = 0;
        INT8 pvy = 0;
        switch (cd) {
            case 0u: pvy = -(INT8)ai_delta_probe; break;
            case 1u: pvx = (INT8)ai_delta_probe; break;
            case 2u: pvy = (INT8)ai_delta_probe; break;
            case 3u: pvx = -(INT8)ai_delta_probe; break;
        }
        INT16 pXs = (INT16)_pool_carAi_x[i_carAi] + (INT16)pvx;
        INT16 pYs = (INT16)_pool_carAi_y[i_carAi] + (INT16)pvy;
        UINT8 b = 1u;
        if (pXs >= 0 && pXs < 144 && pYs >= 0 && pYs < 136) {
            UINT8 sX = (UINT8)pXs + 4u;
            UINT8 sY = (UINT8)pYs + 8u;
            UINT8 tCol = sX >> 3;
            UINT8 tRow = sY >> 3;
            if (tCol < 19u && tRow < 19u) {
                UINT8 t = _zone_track1_tiles[tRow * 19u + tCol];
                if (t != 0u) b = 0u;
            }
        }
        blocked[cd] = b;
    }
    UINT8 primary_blocked = blocked[ai_primary];
    UINT8 fallback_blocked = blocked[ai_fallback];
    UINT8 both_blocked = (primary_blocked && fallback_blocked) ? 1u : 0u;
    UINT8 ai_prev_heading = _pool_carAi_heading[i_carAi];
    /* prev-perpendicular-commit: when primary is blocked, prefer the
     * previous heading IF it is perpendicular to primary AND still
     * unblocked. This breaks the degenerate oscillation where the AI
     * alternates between fallback (E) and anti-fallback (W) without
     * making progress along the corridor — committing to the perp
     * escape direction lets the AI traverse narrow corridors that
     * require multiple lateral steps before primary unblocks. The
     * axis-bit is bit-0: N=0/S=2 are vertical (bit-0 == 0); E=1/W=3
     * are horizontal (bit-0 == 1). Two headings are perpendicular iff
     * their bit-0 differs. */
    UINT8 ai_prev_is_perp = ((ai_prev_heading & 1u) != (ai_primary & 1u)) ? 1u : 0u;
    if (!primary_blocked) {
        _pool_carAi_heading[i_carAi] = ai_primary;
    } else if (ai_prev_is_perp && !blocked[ai_prev_heading]) {
        _pool_carAi_heading[i_carAi] = ai_prev_heading;
    } else if (!fallback_blocked) {
        _pool_carAi_heading[i_carAi] = ai_fallback;
    } else {
        UINT8 ai_tertiary = 0xFFu;
        for (cd = 0u; cd < 4u; cd++) {
            if (cd == ai_primary || cd == ai_fallback) continue;
            if (!blocked[cd]) { ai_tertiary = cd; break; }
        }
        if (ai_tertiary != 0xFFu) {
            _pool_carAi_heading[i_carAi] = ai_tertiary;
        }
        (void)both_blocked;
    }
}
        _pool_carAi_speed_cur[i_carAi] = (_pool_carAi_speed_cur[i_carAi] + 10u < 252u) ? _pool_carAi_speed_cur[i_carAi] + 10u : 252u;
        UINT8 ai_delta_carAi = _pool_carAi_speed_cur[i_carAi] >> 5u;
        INT8 ai_vx_carAi = 0u;
        INT8 ai_vy_carAi = 0u;
        switch (_pool_carAi_heading[i_carAi]) {
        case 0u:
            ai_vy_carAi = -(INT8)ai_delta_carAi;
            break;
        case 1u:
            ai_vx_carAi = (INT8)ai_delta_carAi;
            break;
        case 2u:
            ai_vy_carAi = (INT8)ai_delta_carAi;
            break;
        case 3u:
            ai_vx_carAi = -(INT8)ai_delta_carAi;
            break;
        }
        {
    INT16 propXs = (INT16)_pool_carAi_x[i_carAi] + (INT16)ai_vx_carAi;
    INT16 propYs = (INT16)_pool_carAi_y[i_carAi] + (INT16)ai_vy_carAi;
    if (propXs >= 0 && propXs < 144 && propYs >= 0 && propYs < 136) {
        UINT8 propX = (UINT8)propXs;
        UINT8 propY = (UINT8)propYs;
        if (((((propX) >> 3) < 19u && ((propY) >> 3) < 19u && _zone_track1_tiles[((propY) >> 3) * 19u + ((propX) >> 3)] != 0u) || (((propX + 7u) >> 3) < 19u && ((propY) >> 3) < 19u && _zone_track1_tiles[((propY) >> 3) * 19u + ((propX + 7u) >> 3)] != 0u) || (((propX) >> 3) < 19u && ((propY + 15u) >> 3) < 19u && _zone_track1_tiles[((propY + 15u) >> 3) * 19u + ((propX) >> 3)] != 0u) || (((propX + 7u) >> 3) < 19u && ((propY + 15u) >> 3) < 19u && _zone_track1_tiles[((propY + 15u) >> 3) * 19u + ((propX + 7u) >> 3)] != 0u))) {
            _pool_carAi_x[i_carAi] = propX;
            _pool_carAi_y[i_carAi] = propY;
        }
    }
}
        if (dx_carAi < 8u && dy_carAi < 8u) {
            _pool_carAi_wp_idx[i_carAi] = (_pool_carAi_wp_idx[i_carAi] + 1u >= 4u) ? 0u : _pool_carAi_wp_idx[i_carAi] + 1u;
        }
    }
}

// Racing system: track1 — finish/lap detection
void racing_check_finish_track1(void) {
    // Race finish: 3 laps required
    if (_racing_lap_count_track1 >= 3u) {
        // race_complete_track1: handle finish event in scene
    }
}

// Plan 07.4-30 / D-N-SWITCHROM-RESTORE: HOME-bank SWITCH_ROM wrapper
void _bkg_tiles_load_banked(UINT8 bank, UINT8 x, UINT8 y, UINT8 w, UINT8 h, const UINT8* tiles) {
    SWITCH_ROM(bank);
    set_bkg_tiles(x, y, w, h, tiles);
    SWITCH_ROM(1);
}

// Trampoline: results_enter (bank 1)
void results_enter_trampoline(void) {
    results_enter();
}

void results_frame_trampoline(void) {
    results_frame();
}

// Trampoline: race_enter (bank 1)
void race_enter_trampoline(void) {
    race_enter();
}

void race_frame_trampoline(void) {
    race_frame();
}

// Trampoline: title_enter (bank 1)
void title_enter_trampoline(void) {
    title_enter();
}

void title_frame_trampoline(void) {
    title_frame();
}

// Scene navigation
void navigate_to_scene(UINT8 scene) {
    current_scene = scene;
    switch (scene) {
    case SCENE_RESULTS:
        results_enter_trampoline();
        break;
    case SCENE_RACE:
        race_enter_trampoline();
        break;
    case SCENE_TITLE:
        title_enter_trampoline();
        break;
    }
}

// Entry point
void main(void) {
    NR52_REG = 128u;
    NR50_REG = 119u;
    NR51_REG = 255u;
    DISPLAY_ON;
    SHOW_BKG;
    SHOW_SPRITES;
    set_sprite_data(0u, 2u, sprites_car_tiles);
    set_sprite_data(2u, 2u, sprites_car_tiles);
    set_sprite_tile(0u, 0u);
    move_sprite(0u, _car_x + 8u, _car_y + 16u);
    set_sprite_tile(1u, 1u);
    move_sprite(1u, _car_x + 8u, _car_y + 24u);
    pool_carAi_init();
    title_enter_trampoline();
    while (1) {
        update_joypad();
        switch (current_scene) {
        case SCENE_RESULTS:
            results_frame_trampoline();
            break;
        case SCENE_RACE:
            race_frame_trampoline();
            break;
        case SCENE_TITLE:
            title_frame_trampoline();
            break;
        }
        update_sprites();
        sound_driver_update();
        wait_vbl_done();
    }
    return;
}
