/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * Copyright (c) 2026 Michal Svacha
 */
package io.github.gbkt.backend.gbdk.codegen.visitor

import io.github.gbkt.backend.gbdk.codegen.pipeline.GBDKPipeline
import io.github.gbkt.core.dsl.asset
import io.github.gbkt.core.dsl.game
import io.github.gbkt.core.ir.Cartridge
import io.github.gbkt.core.ir.PositionDef
import io.github.gbkt.genre.sport.dsl.racing
import io.github.gbkt.genre.sport.dsl.vehicle
import kotlin.test.Test
import kotlin.test.assertFalse
import kotlin.test.assertTrue

/**
 * RED tests for Plan 07.4-19 — locks the architectural rule that the DSL `print(...)` keyword, when
 * invoked inside a scene that has a background tilemap (either via `tileset(...)` on the scene OR
 * via a genre plugin's `enterOps` splice such as the racing track painter), MUST NOT lower to
 * `gotoxy() + printf()` in the generated C — those are background-layer text writes that corrupt
 * the BG tilemap.
 *
 * **Why this exists:** Per CLAUDE.md "Window-Layer UI" (project-locked rule):
 *
 * > All UI text (dialogs, menus, battle UI, status bars) renders on the GBDK window layer via
 * > `_win_*` helpers generated by `WindowTextCodegen`. This prevents text from corrupting the
 * > background tile layer when using custom tilesets. Zero `gotoxy`/`printf` calls remain in UI
 * > code.
 *
 * Currently `ScriptOpVisitor.visitPrintOp` (gbkt-backend-gbdk/.../ScriptOpVisitor.kt:909) lowers
 * `PrintOp` to `gotoxy() + printf()` unconditionally — a violation of the locked rule when the
 * scene has a BG tilemap. Plan 20 must make `visitPrintOp` scene-aware (or universally route
 * through `_win_print_at`).
 *
 * **Cross-bug awareness:** if `clear()` is fixed but `print()` is not (or vice versa), the
 * race_enter would still corrupt the painted track. The two RED tests in this plan are INDEPENDENT
 * forcing functions — Plan 20 must close BOTH.
 */
class PrintOpSceneAwareTest {

    /**
     * Test #1 — locks the DSL `print(...)` invariant for scenes that explicitly bind a tileset via
     * `tileset("path/to.png")`. The `tilesetRef != null` branch is the most direct signal that the
     * scene paints a BG tilemap.
     *
     * **Expected at HEAD:** FAIL. `print(..., position = ...)` lowers to `gotoxy(); printf();` in
     * the generated `zone_enter` body, which writes to the BG layer.
     *
     * **Expected after Plan 20:** PASS. The DSL `print()` will lower to `_win_print_at(...)` for
     * scenes with a BG tilemap, per the CLAUDE.md window-layer-UI rule.
     */
    @Test
    fun `dsl print in scene with tilesetRef does not emit gotoxy or printf`() {
        val gameIR =
            game("PrintOpTilesetFixture") {
                    config {
                        cartridge(Cartridge.ROM_ONLY)
                        romBanks(2)
                    }
                    val zoneScene =
                        scene("zone") {
                            tileset("tilesets/dungeon.png")
                            enter { print("HUD", position = PositionDef(1, 1)) }
                            frame { /* no-op */ }
                        }
                    start = zoneScene
                }
                .build()

        val output = GBDKPipeline().generate(gameIR)
        val bank1 =
            output.files["bank1.c"] ?: error("bank1.c not generated; got: ${output.files.keys}")
        val zoneEnterBody = extractFunctionBody(bank1, "zone_enter")

        assertFalse(
            zoneEnterBody.contains("gotoxy("),
            "Plan 07.4-19/20 RED: scene 'zone' has a BG tilemap (via tileset(\"...\"))." +
                " The DSL print() keyword must NOT lower to gotoxy() — that writes to the BG" +
                " layer and corrupts the tilemap. CLAUDE.md 'Window-Layer UI': Zero gotoxy/printf" +
                " calls in UI code. The DSL print() in a scene with a BG tilemap must lower to" +
                " _win_print_at.\n\nzone_enter body:\n$zoneEnterBody",
        )
        assertFalse(
            zoneEnterBody.contains("printf("),
            "Plan 07.4-19/20 RED: scene 'zone' has a BG tilemap. The DSL print() keyword must" +
                " NOT lower to printf() — that writes to the BG layer. See CLAUDE.md" +
                " 'Window-Layer UI'.\n\nzone_enter body:\n$zoneEnterBody",
        )
        assertTrue(
            zoneEnterBody.contains("_win_print_at("),
            "Plan 07.4-19/20 RED: scene 'zone' has a BG tilemap. The DSL print() keyword MUST" +
                " lower to _win_print_at(...) (the window-layer helper from WindowTextCodegen)" +
                " per CLAUDE.md 'Window-Layer UI'.\n\nzone_enter body:\n$zoneEnterBody",
        )
    }

    /**
     * Test #2 — locks the DSL `print(...)` invariant for the EXACT racer pattern: a `race` scene
     * with no `tilesetRef` of its own, where the racing genre's `SportVisitor` splices `enterOps`
     * (set_bkg_data + set_bkg_tiles) into `race_enter`. The race scene's user `print("LAP:",
     * position = (1,1))` currently lowers to `gotoxy(1, 1); printf("LAP:");` which writes to column
     * (1, 1) of the BG layer — corrupting the painted track.
     *
     * **Expected at HEAD:** FAIL. `race_enter` contains `gotoxy(1, 1); printf("LAP:");`. **Expected
     * after Plan 20:** PASS.
     */
    @Test
    fun `dsl print in race scene with genre splice does not emit gotoxy or printf`() {
        val gameIR =
            game("RacerLikePrintFixture") {
                    config {
                        cartridge(Cartridge.ROM_ONLY)
                        romBanks(2)
                    }
                    val car by actor {
                        position(80, 80)
                        sprite(asset("sprites/car.png")) {
                            size(8, 16)
                            hitbox(0, 0, 8, 16)
                        }
                    }
                    val rival by actor {
                        position(80, 96)
                        sprite(asset("sprites/car.png")) {
                            size(8, 16)
                            hitbox(0, 0, 8, 16)
                        }
                    }
                    val carPlayer by vehicle {
                        actor(car)
                        stats {
                            speed(200)
                            acceleration(160)
                            handling(180)
                        }
                    }
                    val carAi by vehicle {
                        actor(rival)
                        stats {
                            speed(180)
                            acceleration(150)
                            handling(200)
                        }
                    }
                    @Suppress("UNUSED_VARIABLE")
                    val track1 by racing {
                        laps(3)
                        player(carPlayer)
                        aiOpponents(carAi)
                        track {
                            waypoint(x = 5, y = 5, checkpoint = true)
                            waypoint(x = 15, y = 5)
                            waypoint(x = 15, y = 15, checkpoint = true)
                            waypoint(x = 5, y = 15)
                        }
                    }
                    val raceScene =
                        scene("race") {
                            enter { print("LAP:", position = PositionDef(1, 1)) }
                            frame { /* empty */ }
                        }
                    start = raceScene
                }
                .build()

        val output = GBDKPipeline().generate(gameIR)
        val bank1 =
            output.files["bank1.c"] ?: error("bank1.c not generated; got: ${output.files.keys}")
        val raceEnterBody = extractFunctionBody(bank1, "race_enter")

        assertFalse(
            raceEnterBody.contains("gotoxy("),
            "Plan 07.4-19/20 RED: scene 'race' has a BG tilemap (genre racing splice paints" +
                " _zone_track1_tiles). The DSL print() keyword must NOT lower to gotoxy() — that" +
                " writes to the BG layer and corrupts the painted track. See CLAUDE.md" +
                " 'Window-Layer UI'.\n\nrace_enter body:\n$raceEnterBody",
        )
        assertFalse(
            raceEnterBody.contains("printf("),
            "Plan 07.4-19/20 RED: scene 'race' has a BG tilemap. The DSL print() keyword must" +
                " NOT lower to printf() — that writes to the BG layer. See CLAUDE.md" +
                " 'Window-Layer UI'.\n\nrace_enter body:\n$raceEnterBody",
        )
        assertTrue(
            raceEnterBody.contains("_win_print_at("),
            "Plan 07.4-19/20 RED: scene 'race' has a BG tilemap. The DSL print() keyword MUST" +
                " lower to _win_print_at(...) (the window-layer helper) per CLAUDE.md" +
                " 'Window-Layer UI'.\n\nrace_enter body:\n$raceEnterBody",
        )
    }

    /**
     * Test #3 — back-compat branch for scenes WITHOUT a BG tilemap (no `tilesetRef`, no genre
     * `enterOps` splice).
     *
     * Plan 07.4-20's REVISED back-compat decision (per its `<decision>` block, option (a)) is
     * **scene-aware PrintOp**: keep `gotoxy(...) + printf(...)` for non-BG scenes (title, results,
     * gameover) and swap to `_win_print_at(...)` only for BG scenes (where the window-layer-UI rule
     * applies most stringently).
     *
     * Rationale (regression-vs-purity tradeoff):
     * - `sprintf` IS available in GBDK-2020 (verified at
     *   `/Users/michalsvacha/gbdk/include/stdio.h:55`), so a universal `_win_print_at` swap is
     *   technically feasible — but exercising sprintf
     *     + `_win_print_at` across all 5 non-racer example games' title screens introduces
     *       untested-rewrite risk for zero observable benefit (those titles draw on an empty BG
     *       where `printf` cannot corrupt anything).
     * - CLAUDE.md "Window-Layer UI" applies most stringently to scenes WITH a custom BG tilemap.
     *   For BG-less scenes, the architectural-purity argument loses to the regression-risk
     *   argument.
     *
     * **What this test locks (Plan 20 Task 2):** the back-compat shape for a non-BG scene MUST
     * contain `gotoxy(` AND `printf(`, and MUST NOT contain `_win_print_at(`. If a future change
     * accidentally widens the BG-scene swap to ALL scenes, this test fails loudly (preventing
     * silent cross-ROM regression across 5 example games' title screens).
     */
    @Test
    fun `dsl print in scene without BG tilemap back compat branch`() {
        val gameIR =
            game("PrintOpTitleFixture") {
                    config {
                        cartridge(Cartridge.ROM_ONLY)
                        romBanks(2)
                    }
                    val titleScene =
                        scene("title") {
                            enter { print("HI", position = PositionDef(1, 1)) }
                            frame { /* no-op */ }
                        }
                    start = titleScene
                }
                .build()

        val output = GBDKPipeline().generate(gameIR)
        val bank1 =
            output.files["bank1.c"] ?: error("bank1.c not generated; got: ${output.files.keys}")
        val titleEnterBody = extractFunctionBody(bank1, "title_enter")

        // Plan 20 chose option (a) — scene-aware. Non-BG scene → keep gotoxy + printf.
        assertTrue(
            titleEnterBody.contains("gotoxy("),
            "Plan 07.4-20 (revised back-compat option (a)): scene 'title' has NO BG tilemap." +
                " The DSL print() keyword MUST preserve back-compat by emitting gotoxy(...)" +
                " + printf(...) — same byte-for-byte shape as before Plan 20." +
                "\n\ntitle_enter body:\n$titleEnterBody",
        )
        assertTrue(
            titleEnterBody.contains("printf("),
            "Plan 07.4-20 (revised back-compat option (a)): scene 'title' has NO BG tilemap." +
                " The DSL print() keyword MUST preserve back-compat by emitting printf(...)." +
                "\n\ntitle_enter body:\n$titleEnterBody",
        )
        assertFalse(
            titleEnterBody.contains("_win_print_at("),
            "Plan 07.4-20 (revised back-compat option (a)): scene 'title' has NO BG tilemap." +
                " The DSL print() keyword MUST NOT lower to _win_print_at(...) for non-BG" +
                " scenes — that path is reserved for BG scenes only (regression-vs-purity" +
                " tradeoff). If you intend to widen the scope, update the Plan 20 <decision>" +
                " block first and exercise the sprintf+_win_print_at path against all 5" +
                " non-racer example games' titles." +
                "\n\ntitle_enter body:\n$titleEnterBody",
        )
    }

    /**
     * Walks the C source from `void <funcName>(void)` to the matching closing brace, tracking
     * nested braces. Mirrors the helper in `ScreenClearSceneAwareTest` — kept inline rather than
     * extracted to a shared fixture to avoid a Wave-0 file dance for two tests.
     */
    private fun extractFunctionBody(cSource: String, funcName: String): String {
        val signatureIdx = cSource.indexOf("void $funcName(void)")
        require(signatureIdx >= 0) {
            "Function 'void $funcName(void)' not found in C source.\n\n" +
                "First 1500 chars of C source:\n${cSource.take(1500)}"
        }
        val openBrace = cSource.indexOf('{', signatureIdx)
        require(openBrace >= 0) { "Open brace for $funcName not found" }
        var depth = 1
        var i = openBrace + 1
        while (i < cSource.length && depth > 0) {
            when (cSource[i]) {
                '{' -> depth++
                '}' -> depth--
            }
            i++
        }
        return cSource.substring(openBrace + 1, i - 1)
    }
}
