// Generated by gbkt
#pragma bank 1

#include <stdio.h>
#include <gbdk/console.h>
#include "game.h"

// Scene: gameover
void gameover_enter(void) BANKED {
    HIDE_SPRITES;
    cls();
    {
        gotoxy(5u, 6u);
        printf("GAME OVER");
    }
    {
        gotoxy(3u, 9u);
        printf("TORCH EXPIRED");
    }
    {
        gotoxy(5u, 13u);
        printf("PRESS START");
    }
}

void gameover_frame(void) BANKED {
    update_hud_game_hud();
    if (button_pressed(J_START)) {
        _torchLevel = 255u;
        _keys = 0u;
        _steps = 0u;
        navigate_to_scene(SCENE_TITLE);
    }
}

// Scene: battle
void battle_enter(void) BANKED {
    HIDE_SPRITES;
    cls();
    {
        gotoxy(5u, 4u);
        printf("ENCOUNTER!");
    }
    play_sound_hitSfx();
    delay_frames(30u);
}

void battle_frame(void) BANKED {
    update_hud_game_hud();
    trigger_combat();
}

// Scene: gameplay
void gameplay_enter(void) BANKED {
    SHOW_SPRITES;
    cls();
    {
        _player_x = 64u;
        _player_y = 64u;
    }
    show_hud_game_hud();
}

void gameplay_frame(void) BANKED {
    update_hud_game_hud();
    if (button_held(J_UP)) {
        if (_player_y > 16u) {
            {
                _player_y += -8;
            }
        }
    }
    if (button_held(J_DOWN)) {
        if (_player_y < 128u) {
            {
                _player_y += 8u;
            }
        }
    }
    if (button_held(J_LEFT)) {
        if (_player_x > 8u) {
            {
                _player_x += -8;
            }
        }
    }
    if (button_held(J_RIGHT)) {
        if (_player_x < 152u) {
            {
                _player_x += 8u;
            }
        }
    }
    if (dpad_any()) {
        _steps += 1u;
    }
    if (_steps > 0u && _steps & 3u == 0u && _torchLevel > 0u) {
        _torchLevel -= 1u;
    }
    if (_torchLevel == 50u) {
        show_dialog_torch_warning("Torch dimming...", 16u);
    }
    if (_torchLevel == 0u) {
        HIDE_SPRITES;
        show_dialog_torch_warning("Your torch burns out!", 21u);
        delay_frames(60u);
        navigate_to_scene(SCENE_GAMEOVER);
    }
    if (_steps >= 120u) {
        _steps = 0u;
        navigate_to_scene(SCENE_BATTLE);
    }
}

void gameplay_exit(void) BANKED {
    hide_hud_game_hud();
}

// Scene: title
void title_enter(void) BANKED {
    HIDE_SPRITES;
    cls();
    {
        gotoxy(6u, 4u);
        printf("DUNGEON");
    }
    {
        gotoxy(2u, 7u);
        printf("A TORCH CRAWLER");
    }
    {
        gotoxy(5u, 12u);
        printf("PRESS START");
    }
}

void title_frame(void) BANKED {
    update_hud_game_hud();
    if (button_pressed(J_START)) {
        _torchLevel = 255u;
        _keys = 0u;
        _steps = 0u;
        navigate_to_scene(SCENE_GAMEPLAY);
    }
}
