// Generated by gbkt
#ifndef GAME_H
#define GAME_H

#include <gb/gb.h>
#include <stdio.h>
#include <gbdk/console.h>

#define SCENE_GAMEOVER 0
#define SCENE_BATTLE 1
#define SCENE_GAMEPLAY 2
#define SCENE_TITLE 3
#define _COMBAT_STATE_INIT 0
#define _COMBAT_STATE_PLAYER_TURN 1
#define _COMBAT_STATE_ENEMY_TURN 2
#define _COMBAT_STATE_VICTORY 3
#define _COMBAT_STATE_DEFEAT 4
#define _COMBAT_STATE_TARGET_SELECT 5
#define _COMBAT_STATE_EXECUTE_ACTION 6
#define _COMBAT_STATE_FLEEING 7
#define _COMBAT_STATE_WAITING 8

extern UINT8 _player_x;
extern UINT8 _player_y;
extern UINT8 _torchLevel;
extern UINT8 _keys;
extern UINT8 _steps;
extern UINT8 __joypad;
extern UINT8 __joypad_prev;
extern UINT8 _sound_channels[4];
extern UINT8 _sound_priority[4];
extern UINT8 _sound_duration[4];
extern UINT8 _combat_state_combat;
extern UINT8 _pending_state_combat;
extern const UINT8 _zone_floor1_tiles[1];
extern UINT8 current_scene;
extern UINT8 _wait_counter;
extern UINT8 _char_active_sp;
extern UINT8 _combat_target_idx;
extern UINT8 _combat_active_enemy_idx;
extern UINT8 _combat_active_ally_idx;
extern UINT8 _combat_target_all_enemies;
extern UINT8 _combat_target_all_allies;
extern UINT8 _combat_target_all;
extern UINT8 _camera_x;
extern UINT8 _camera_y;
extern UINT8 _camera_target;
extern UINT8 _camera_shake_intensity;
extern UINT8 _camera_shake_timer;
extern UINT8 _current_floor;
extern UINT8 _exploration_step_count;
extern UINT8 _encounter_safe_steps;
extern UINT8 _encounter_triggered;
extern UINT8 _encounter_id;
extern UINT8 _current_zone_safe;
extern UINT8 _current_zone_id;
extern UINT8 _gauge_torch;
extern UINT8 _key_room_key;
extern UINT8 _dialog_speed;
extern UINT8 _hud_game_hud_visible;
extern UINT8 _hud_game_hud_torch_prev;
extern UINT8 _hud_game_hud_keys_prev;
extern const UINT8 _hud_full_icon_game_hud_keys;
extern const UINT8 _hud_empty_icon_game_hud_keys;
extern UINT8 _current_tileset_id;
extern UINT8 _char_adventurer_hp;
extern UINT8 _char_adventurer_sp;
extern UINT8 _char_adventurer_atk;
extern UINT8 _char_adventurer_def;
extern UINT8 _char_adventurer_matk;
extern UINT8 _char_adventurer_mdef;
extern UINT8 _char_adventurer_agl;
extern UINT8 _char_adventurer_level;
extern UINT16 _char_adventurer_exp;
extern UINT8 _flag_bossDefeated;
extern UINT8 _flag_gotTreasure;
extern UINT8 _flag_foundKey;
extern UINT8 _combat_difficulty;
extern UINT8 _player_level;
extern UINT8 _char_target_hp;
extern UINT8 _mon_bat_hp_pct;
extern UINT8 _mon_skeleton_hp_pct;

// Forward declarations for external functions called via callOp()
void delay_frames(UINT8 p0);

// Scene: gameover
void gameover_enter(void) BANKED;

void gameover_frame(void) BANKED;

// Scene: battle
void battle_enter(void) BANKED;

void battle_frame(void) BANKED;

// Scene: gameplay
void gameplay_enter(void) BANKED;

void gameplay_frame(void) BANKED;

void gameplay_exit(void) BANKED;

// Scene: title
void title_enter(void) BANKED;

void title_frame(void) BANKED;

// Input helpers (joypad polling with edge detection)
void update_joypad(void);

UINT8 button_pressed(UINT8 mask);

UINT8 button_held(UINT8 mask);

UINT8 button_held(UINT8 mask);

UINT8 button_pressed(UINT8 mask);

UINT8 button_released(UINT8 mask);

UINT8 button_released(UINT8 mask);

UINT8 dpad_any(void);

// Timing helpers (blocking busy-wait)
void delay_frames(UINT8 n);

// Sprite helpers (real OAM management)
void hide_sprites_range(UINT8 from, UINT8 to);

void show_sprites_range(UINT8 from, UINT8 to);

// Sprite OAM sync (called every frame)
void update_sprites(void);

// Sound driver (channel allocation with priority preemption)
void sound_driver_update(void);

void play_sound(UINT8 sound_id, UINT8 channel, UINT8 priority, UINT8 duration);

void play_sound_bumpSfx(void);

void play_sound_hitSfx(void);

void play_sound_keySfx(void);

void play_sound_stepSfx(void);

// Dialog helpers (window layer rendering)
void _win_print_at(UINT8 x, UINT8 y, const UINT8* str, UINT8 len);

void _win_clear_region(UINT8 x, UINT8 y, UINT8 w, UINT8 h);

void _win_fill_screen(UINT8 tile);

// Dialog: torch_warning
void show_dialog_torch_warning(const UINT8* _text, UINT8 _text_len);

// HUD helpers (change-detection rendering)
void _hud_print_u8(UINT8 x, UINT8 y, UINT8 value);

// HUD: game_hud
void update_hud_game_hud(void);

void show_hud_game_hud(void);

void hide_hud_game_hud(void);

// Fade helpers (palette-based screen fade)
void fade_out(void);

void fade_in(void);

// Stub collision — no scenes have collision data
UINT8 _map_collision(UINT8 x, UINT8 y);

// Camera system: camera
void update_camera_camera(void);

// Save system: dungeon_save (slots=1, checksum=false)
void save_game_dungeon_save(UINT8 slotIndex);

void load_game_dungeon_save(UINT8 slotIndex);

// Exploration system: exploration
void exploration_move_exploration(void);

void exploration_step_exploration(void);

void exploration_encounter_check_exploration(void);

void show_hud_game_hud(void);

void zone_load_exploration(UINT8 zone_id);

void zone_transition_exploration(UINT8 target_zone_id, UINT8 edge, UINT8 entry_x, UINT8 entry_y);

void combat_request_state_combat(UINT8 s);

void update_combat_combat(void);

UINT8 combat_is_in_state_combat(UINT8 state);

void trigger_combat(void);

// Combat engine stubs
void monster_basic_attack(void);

void monster_flee(void);

UINT8 find_lowest_hp_target(void);

// Trampoline: gameover_enter (bank 1)
void gameover_enter_trampoline(void);

void gameover_frame_trampoline(void);

// Trampoline: battle_enter (bank 1)
void battle_enter_trampoline(void);

void battle_frame_trampoline(void);

// Trampoline: gameplay_enter (bank 1)
void gameplay_enter_trampoline(void);

void gameplay_frame_trampoline(void);

void gameplay_exit_trampoline(void);

// Trampoline: title_enter (bank 1)
void title_enter_trampoline(void);

void title_frame_trampoline(void);

// Scene navigation
void navigate_to_scene(UINT8 scene);

#endif // GAME_H
