/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * Copyright (c) 2026 Michal Svacha
 */
package io.github.gbkt.backend.gbdk.codegen.emit

import io.github.gbkt.backend.gbdk.codegen.ast.*
import io.github.gbkt.backend.gbdk.codegen.pipeline.SourceMapCollector

// =============================================================================
// C EMITTER
// Single pretty-printer that converts CFile AST nodes to C source strings.
//
// Architecture rule: This is the ONLY file in the new pipeline that calls
// buildString or appendLine to produce C text. All other codegen files produce
// typed C AST nodes.
//
// Output style:
//   - 4-space indentation
//   - K&R braces ({ on same line as statement)
//   - Blank lines between functions
//   - GBDK-specific: #pragma bank N, BANKED keyword
// =============================================================================

/**
 * Single pretty-printer that converts a typed [CFile] AST to a C source string.
 *
 * This is the ONLY place where C strings are assembled from C AST nodes. All other codegen code
 * produces typed [CStatement], [CExpr], and [CType] nodes.
 *
 * Uses exhaustive [when] matching on all sealed hierarchies — no [else] branch ensures the Kotlin
 * compiler will catch unhandled subtypes at compile time.
 */
object CEmitter {

    /**
     * Line-tracking wrapper around [StringBuilder] that counts newlines and optionally records DSL
     * source-location mappings via [SourceMapCollector].
     *
     * All state is local to each [emit] call — the [CEmitter] object itself has no mutable fields.
     */
    private class LineTrackingBuilder(
        private val sb: StringBuilder = StringBuilder(),
        val collector: SourceMapCollector?,
        var lineNumber: Int = 1,
    ) {
        /** Append a line and increment the line counter. */
        fun appendLine(s: String = "") {
            sb.appendLine(s)
            lineNumber++
        }

        /** Append text without incrementing the line counter. */
        fun append(s: String) {
            sb.append(s)
        }

        /**
         * Record a mapping from the current line to a DSL source location.
         *
         * No-op when [collector] is null or when [stmt]'s sourceLocation is null.
         */
        fun recordMapping(stmt: CStatement, irNodeType: String? = null, symbol: String? = null) {
            collector?.record(lineNumber, stmt.sourceLocation, irNodeType, symbol)
        }

        override fun toString(): String = sb.toString()
    }

    /**
     * Emit a complete C source file from a typed [CFile] AST.
     *
     * When [collector] is non-null, each emitted statement that carries a non-null
     * [CStatement.sourceLocation] is recorded in the collector as a (cLine, SourceLocation) pair.
     *
     * Output includes:
     * - `// Generated by gbkt` header
     * - `#pragma bank N` when [CFile.bank] > 0
     * - `#include` directives
     * - `#define` macros
     * - typedef declarations
     * - File-level variable declarations
     * - Function definitions (with optional section comments and blank lines between)
     */
    fun emit(file: CFile, collector: SourceMapCollector? = null): String {
        val ltb = LineTrackingBuilder(collector = collector)

        // Generated header
        ltb.appendLine("// Generated by gbkt")

        // Include guard open (for header files)
        val guardName =
            if (file.isHeader) {
                file.name.uppercase().replace('.', '_').replace('-', '_')
            } else {
                null
            }
        if (guardName != null) {
            ltb.appendLine("#ifndef $guardName")
            ltb.appendLine("#define $guardName")
        }

        // Bank pragma — GBDK requires this at top of banked files
        if (file.bank > 0) {
            ltb.appendLine("#pragma bank ${file.bank}")
        }

        // Includes
        if (file.includes.isNotEmpty()) {
            ltb.appendLine()
            for (include in file.includes) {
                ltb.appendLine("#include $include")
            }
        }

        // Defines
        if (file.defines.isNotEmpty()) {
            ltb.appendLine()
            for (define in file.defines) {
                if (define.value != null) {
                    ltb.appendLine("#define ${define.name} ${define.value}")
                } else {
                    ltb.appendLine("#define ${define.name}")
                }
            }
        }

        // Typedefs
        if (file.typedefs.isNotEmpty()) {
            ltb.appendLine()
            for (typedef in file.typedefs) {
                ltb.appendLine("typedef ${typedef.definition} ${typedef.name};")
            }
        }

        // File-level variables
        if (file.variables.isNotEmpty()) {
            ltb.appendLine()
            for (variable in file.variables) {
                ltb.recordMapping(variable, irNodeType = "CVarDecl")
                ltb.appendLine(emitVarDecl(variable, indent = 0))
            }
        }

        // Raw file-scope sections (e.g. collection data declarations)
        for (rawSection in file.rawSections) {
            ltb.appendLine()
            for (line in rawSection.lines()) {
                ltb.appendLine(line)
            }
        }

        // Functions — separated by blank lines
        for ((index, fn) in file.functions.withIndex()) {
            ltb.appendLine()
            if (fn.sectionComment != null) {
                ltb.appendLine("// ${fn.sectionComment}")
            }
            ltb.append(emitFunction(fn, ltb))
            if (index < file.functions.size - 1) {
                // Blank line between functions is handled by the leading appendLine()
                // on the next iteration. The trailing newline from emitFunction plus
                // the leading appendLine() at top of next iteration gives the blank line.
            }
        }

        // Include guard close (for header files)
        if (guardName != null) {
            ltb.appendLine()
            ltb.appendLine("#endif // $guardName")
        }

        return ltb.toString()
    }

    // =========================================================================
    // Function emission
    // =========================================================================

    private fun emitFunction(fn: CFunction, ltb: LineTrackingBuilder): String = buildString {
        // Signature
        val static = if (fn.isStatic) "static " else ""
        val returnType = emitType(fn.returnType)
        val params =
            if (fn.params.isEmpty()) {
                "void"
            } else {
                fn.params.joinToString(", ") { "${emitType(it.type)} ${it.name}" }
            }
        val banked = if (fn.isBanked) " BANKED" else ""

        if (fn.isPrototype) {
            // Prototype: emit signature ending in semicolon — no body
            appendLine("$static$returnType ${fn.name}($params)$banked;")
            ltb.lineNumber++
        } else {
            appendLine("$static$returnType ${fn.name}($params)$banked {")
            ltb.lineNumber++

            // Body
            for (stmt in fn.body) {
                val stmtStr = emitStatement(stmt, indent = 1, ltb = ltb)
                appendLine(stmtStr)
                // Count newlines produced by emitStatement (multi-line stmts like if/for/while)
                ltb.lineNumber += stmtStr.count { it == '\n' }
            }

            appendLine("}")
            ltb.lineNumber++
        }
    }

    // =========================================================================
    // Function emission (public convenience for unit tests)
    // =========================================================================

    /**
     * Emit a single [CFunction] to a C source string.
     *
     * Convenience overload used by tests that need to render individual functions without wrapping
     * them in a [CFile]. The [CEmitter.emit] function is the primary public API.
     */
    fun emitFunction(fn: CFunction): String {
        val ltb = LineTrackingBuilder(collector = null)
        return emitFunction(fn, ltb)
    }

    // =========================================================================
    // Statement emission
    // =========================================================================

    /**
     * Emit a single [CStatement] to a C source string at indent level 0.
     *
     * Convenience overload used by tests that need to render individual statements without wrapping
     * them in a [CFile]. The [CEmitter.emit] function is the primary public API — this overload is
     * provided for unit-testing individual codegen visitors.
     */
    fun emitStatement(stmt: CStatement): String = emitStatement(stmt, indent = 0)

    /**
     * Emit a single [CStatement] to a C source string at the given indent level.
     *
     * When [ltb] is provided with a non-null collector, records the mapping for statements that
     * carry a [CStatement.sourceLocation].
     *
     * Exhaustive [when] — no [else] branch. The Kotlin compiler enforces that all [CStatement]
     * sealed subtypes are handled.
     */
    private fun emitStatement(
        stmt: CStatement,
        indent: Int,
        ltb: LineTrackingBuilder? = null,
    ): String {
        // Record mapping before emitting: the current line in ltb is the statement's start line
        ltb?.recordMapping(stmt, irNodeType = stmt::class.simpleName)

        return when (stmt) {
            is CIf -> emitIf(stmt, indent, ltb)
            is CFor -> emitFor(stmt, indent, ltb)
            is CWhile -> emitWhile(stmt, indent, ltb)
            is CSwitch -> emitSwitch(stmt, indent, ltb)
            is CReturn -> emitReturn(stmt, indent)
            is CBlock -> emitBlock(stmt, indent, ltb)
            is CVarDecl -> emitVarDecl(stmt, indent)
            is CExprStatement -> "${pad(indent)}${emitExpr(stmt.expr)};"
            is CRawCode -> "${pad(indent)}${stmt.code}"
            is CComment -> "${pad(indent)}// ${stmt.text}"
            is CBlankLine -> ""
            is CBreak -> "${pad(indent)}break;"
            is CContinue -> "${pad(indent)}continue;"
        }
    }

    private fun emitIf(stmt: CIf, indent: Int, ltb: LineTrackingBuilder? = null): String =
        buildString {
            appendLine("${pad(indent)}if (${emitExpr(stmt.condition)}) {")
            ltb?.lineNumber++
            for (s in stmt.thenBody) {
                val stmtStr = emitStatement(s, indent + 1, ltb)
                appendLine(stmtStr)
                ltb?.lineNumber += stmtStr.count { it == '\n' }
            }
            if (stmt.elseBody.isEmpty()) {
                append("${pad(indent)}}")
            } else {
                appendLine("${pad(indent)}} else {")
                ltb?.lineNumber++
                for (s in stmt.elseBody) {
                    val stmtStr = emitStatement(s, indent + 1, ltb)
                    appendLine(stmtStr)
                    ltb?.lineNumber += stmtStr.count { it == '\n' }
                }
                append("${pad(indent)}}")
            }
        }

    private fun emitFor(stmt: CFor, indent: Int, ltb: LineTrackingBuilder? = null): String =
        buildString {
            val init = stmt.init?.let { emitForInit(it) } ?: ""
            val cond = stmt.condition?.let { emitExpr(it) } ?: ""
            val incr = stmt.increment?.let { emitExprForIncrement(it) } ?: ""
            appendLine("${pad(indent)}for ($init; $cond; $incr) {")
            ltb?.lineNumber++
            for (s in stmt.body) {
                val stmtStr = emitStatement(s, indent + 1, ltb)
                appendLine(stmtStr)
                ltb?.lineNumber += stmtStr.count { it == '\n' }
            }
            append("${pad(indent)}}")
        }

    private fun emitWhile(stmt: CWhile, indent: Int, ltb: LineTrackingBuilder? = null): String =
        buildString {
            appendLine("${pad(indent)}while (${emitExpr(stmt.condition)}) {")
            ltb?.lineNumber++
            for (s in stmt.body) {
                val stmtStr = emitStatement(s, indent + 1, ltb)
                appendLine(stmtStr)
                ltb?.lineNumber += stmtStr.count { it == '\n' }
            }
            append("${pad(indent)}}")
        }

    private fun emitSwitch(stmt: CSwitch, indent: Int, ltb: LineTrackingBuilder? = null): String =
        buildString {
            appendLine("${pad(indent)}switch (${emitExpr(stmt.expr)}) {")
            ltb?.lineNumber++
            for (case in stmt.cases) {
                if (case.value != null) {
                    appendLine("${pad(indent)}case ${emitExpr(case.value)}:")
                } else {
                    appendLine("${pad(indent)}default:")
                }
                ltb?.lineNumber++
                for (s in case.body) {
                    val stmtStr = emitStatement(s, indent + 1, ltb)
                    appendLine(stmtStr)
                    ltb?.lineNumber += stmtStr.count { it == '\n' }
                }
            }
            append("${pad(indent)}}")
        }

    private fun emitReturn(stmt: CReturn, indent: Int): String =
        if (stmt.value != null) {
            "${pad(indent)}return ${emitExpr(stmt.value)};"
        } else {
            "${pad(indent)}return;"
        }

    private fun emitBlock(stmt: CBlock, indent: Int, ltb: LineTrackingBuilder? = null): String =
        buildString {
            appendLine("${pad(indent)}{")
            ltb?.lineNumber++
            for (s in stmt.statements) {
                val stmtStr = emitStatement(s, indent + 1, ltb)
                appendLine(stmtStr)
                ltb?.lineNumber += stmtStr.count { it == '\n' }
            }
            append("${pad(indent)}}")
        }

    private fun emitVarDecl(stmt: CVarDecl, indent: Int): String {
        val extern = if (stmt.isExtern) "extern " else ""
        val static = if (stmt.isStatic) "static " else ""
        val const = if (stmt.isConst) "const " else ""
        val type = emitType(stmt.type)
        val init = stmt.initializer?.let { " = ${emitExpr(it)}" } ?: ""
        // For array types we need to handle the array size in the name
        return if (stmt.type is CArray) {
            val arrType = stmt.type
            val size = arrType.size?.toString() ?: ""
            "${pad(indent)}$extern$static$const${emitType(arrType.elementType)} ${stmt.name}[$size]$init;"
        } else {
            "${pad(indent)}$extern$static$const$type ${stmt.name}$init;"
        }
    }

    /**
     * Emit the init part of a for loop (without the trailing semicolon — the for loop template adds
     * the semicolons).
     */
    private fun emitForInit(stmt: CStatement): String =
        when (stmt) {
            is CVarDecl -> {
                val static = if (stmt.isStatic) "static " else ""
                val const = if (stmt.isConst) "const " else ""
                val type = emitType(stmt.type)
                val init = stmt.initializer?.let { " = ${emitExpr(it)}" } ?: ""
                "$static$const$type ${stmt.name}$init"
            }
            is CExprStatement -> emitExpr(stmt.expr)
            else -> emitStatement(stmt, 0).trim().trimEnd(';')
        }

    /** Emit the increment part of a for loop (expression only, no semicolon). */
    private fun emitExprForIncrement(expr: CExpr): String =
        when (expr) {
            is CUnaryExpr -> {
                // Handle post-increment/decrement: i++ is UnaryExpr("++", CVar("i"))
                "${emitExpr(expr.operand)}${expr.op}"
            }
            else -> emitExpr(expr)
        }

    // =========================================================================
    // Expression emission
    // =========================================================================

    /**
     * Emit a single [CExpr] to a C expression string.
     *
     * Exhaustive [when] — no [else] branch. The Kotlin compiler enforces that all [CExpr] sealed
     * subtypes are handled.
     */
    private fun emitExpr(expr: CExpr): String =
        when (expr) {
            is CLiteral -> if (expr.value >= 0) "${expr.value}u" else "${expr.value}"
            is CStringLiteral -> "\"${expr.value}\""
            is CVar -> expr.name
            is CBinaryExpr -> "${emitExpr(expr.left)} ${expr.op} ${emitExpr(expr.right)}"
            is CUnaryExpr -> "${expr.op}${emitExpr(expr.operand)}"
            is CCall -> "${expr.function}(${expr.args.joinToString(", ") { emitExpr(it) }})"
            is CTernary ->
                "(${emitExpr(expr.condition)}) ? ${emitExpr(expr.thenExpr)} : ${emitExpr(expr.elseExpr)}"
            is CArrayAccess -> "${emitExpr(expr.array)}[${emitExpr(expr.index)}]"
            is CCast -> "(${emitType(expr.type)})${emitExpr(expr.expr)}"
            is CRawExpr -> expr.code
        }

    // =========================================================================
    // Type emission
    // =========================================================================

    /**
     * Emit a [CType] to its C type string.
     *
     * Exhaustive [when] — no [else] branch. The Kotlin compiler enforces that all [CType] sealed
     * subtypes are handled.
     */
    private fun emitType(type: CType): String =
        when (type) {
            CU8 -> "UINT8"
            CU16 -> "UINT16"
            CI8 -> "INT8"
            CI16 -> "INT16"
            CVoid -> "void"
            is CPointer -> "${emitType(type.pointedType)}*"
            is CArray -> emitType(type.elementType) // Array size is emitted at the declaration site
            is CConst -> "const ${emitType(type.inner)}"
        }

    // =========================================================================
    // Helpers
    // =========================================================================

    /** Returns [indent] repetitions of 4 spaces. */
    private fun pad(indent: Int): String = "    ".repeat(indent)
}
