/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * Copyright (c) 2026 Michal Svacha
 */
package io.github.gbkt.emulator

import java.io.File

/**
 * Configuration for creating a [GbEmulator] instance.
 *
 * @param romFile Path to the Game Boy ROM file (.gb or .gbc). Must exist and be readable.
 * @param headless When true, the emulator runs without creating a display window. Frame buffer is
 *   still updated on each frame for programmatic inspection.
 * @param scale Window scale factor when running with a display (1 = 160x144, 4 = 640x576). Ignored
 *   in headless mode.
 * @param sourceMapsDir Directory containing .gbkt.map source map files generated by the gbkt Gradle
 *   plugin. When provided, debug log entries are annotated with Kotlin source file and line numbers
 *   (kotlinFile, kotlinLine). If null, only C line numbers are captured.
 * @param logFile Optional file path for persisting the debug log. When set, log entries are written
 *   to this file in addition to the in-memory buffer. If null, only in-memory logging is performed.
 * @param maxLogEntries Maximum number of entries retained in the in-memory debug log. Older entries
 *   are evicted when the limit is reached (circular buffer). Default: 10,000.
 * @param gbcMode When true, the emulator is configured for GBC (Game Boy Color) mode. Use for ROMs
 *   compiled with `-Wm-yc` or `-Wm-yC` flags. Default: false (DMG mode).
 */
data class EmulatorConfig(
    val romFile: File,
    val headless: Boolean = false,
    val scale: Int = 4,
    val sourceMapsDir: File? = null,
    val logFile: File? = null,
    val maxLogEntries: Int = 10_000,
    val gbcMode: Boolean = false,
) {
    init {
        require(scale in 1..8) { "scale must be between 1 and 8, got $scale" }
        require(maxLogEntries in 1..1_000_000) {
            "maxLogEntries must be between 1 and 1,000,000, got $maxLogEntries"
        }
    }
}
