// Generated by gbkt

#include <gb/gb.h>
#include <stdio.h>
#include <stdlib.h>
#include <gbdk/console.h>
#include "game.h"
#include "_zone_gameplayZone1_tileset.h"
#include "_zone_gameplayZone2_tileset.h"

#define SCENE_TITLE 0
#define SCENE_GAMEPLAY 1
#define SCENE_GAMEPLAY2 2
#define SCENE_NEXTLEVELSCENE 3
#define TILESET_GAMEPLAYZONE1 1
#define TILESET_GAMEPLAYZONE2 2

UINT8 __joypad = 0u;
UINT8 __joypad_prev = 0u;
UINT8 _sound_channels[4] = {0xFF, 0xFF, 0xFF, 0xFF};
UINT8 _sound_priority[4] = {0, 0, 0, 0};
UINT8 _sound_duration[4] = {0, 0, 0, 0};
INT8 _plat_vy = 0u;
INT8 _plat_vx = 0u;
UINT8 _plat_grounded = 0u;
UINT8 _plat_coyote_timer = 0u;
UINT8 _plat_jump_buffer = 0u;
UINT8 _dialog_speed = 1u;
UINT8 current_scene = SCENE_TITLE;
UINT8 _wait_counter = 0u;
UINT8 _current_tileset_id = 0xFF;
UINT8 _current_area_bank = 0u;
const UINT8* _current_level_map = (const UINT8*)0;
UINT16 _current_level_width_in_tiles = 0u;
UINT16 _current_level_height = 0u;
UINT8 _current_level_non_solid_tile_count = 0u;
UINT8 _current_level = 0u;
UINT8 _next_level = 0u;
UINT16 _current_level_width = 0u;

// Phase 12 D-12a — is_tile_solid() HOME-bank NONBANKED helper
// SWITCH_ROM wrapper; mirrors buildBkgTilesLoadBankedHelper pattern (line 1938).
// Called from the tilemap-physics branch in PlatformerVisitor (5-point AABB probe — Plan 12-11).
UINT8 is_tile_solid(UINT16 world_x, UINT16 world_y) NONBANKED {
    UINT8 _previous_bank = CURRENT_BANK;
    SWITCH_ROM(_current_area_bank);
    UINT16 column = world_x >> 3u;
    UINT16 row = world_y >> 3u;
    if (row > (_current_level_height >> 3u) || column >= _current_level_width_in_tiles) {
        SWITCH_ROM(_previous_bank);
        return TRUE;
    }
    UINT8 tile = _current_level_map[column + row * _current_level_width_in_tiles];
    SWITCH_ROM(_previous_bank);
    return tile < _current_level_non_solid_tile_count;
}

// Phase 12 D-13 — _bkg_set_level_submap_banked() HOME-bank NONBANKED helper
// (called from platformer_camera_update column-scroll branch — Plan 12-11 wires the call site).
// SWITCH_ROM wrapper around set_bkg_submap(); mirrors buildBkgTilesLoadBankedHelper / is_tile_solid
// pattern. Lives in HOME bank so MBC remap of 0x4000-0x7FFF cannot affect instruction fetches.
void _bkg_set_level_submap_banked(UINT8 x, UINT8 y, UINT8 w, UINT8 h) NONBANKED {
    UINT8 _previous_bank = CURRENT_BANK;
    SWITCH_ROM(_current_area_bank);
    set_bkg_submap(x, y, w, h, _current_level_map, (UINT8)_current_level_width_in_tiles);
    SWITCH_ROM(_previous_bank);
}

// Phase 12.6 D-06 — per-level spawn position tables (closes DEFECT-2).
// setup_current_level() reads these to write <posXSym>/<posYSym> on every level switch,
// fixing the same-frame level-end-trigger re-fire that occurred when _playerX was preserved
// across level switches. Indices match the gameplay-zone order in setup_current_level()'s
// switch cases (same filter — title/nextLevel/next_level scenes excluded).
const UINT8 _level_spawn_x[] = { 40u, 40u };
const UINT8 _level_spawn_y[] = { 120u, 120u };

// Phase 12 D-02 / D-08 anchor 5 — setup_current_level() HOME-bank NONBANKED function
// (Plan 12-17 Task 2). Switches on (_current_level % <zoneCount>) and binds the
// per-zone tilemap metadata to the canonical _current_level_* globals. Called by the
// main()-loop level-switch guard (after the NextLevel card scene returns to gameplay).
//
// SHAPE LOCK (Plan 12-09b anchor 5 emission test): the function MUST start with
// `void setup_current_level` and MUST contain `switch (_current_level`.
//
// Per-case body is a Plan 12-17 STUB referencing the canonical `_zone_<id>_tilemap`
// symbol + `_zone_<id>_tilemap_WIDTH` / `_HEIGHT` size constants. Plan 12-18's
// ConvertZoneTilesetsTask + GenerateCTask resolve these symbols at buildRom time.
void setup_current_level(void) NONBANKED {
    _current_level = _next_level;
    DISPLAY_OFF;
    switch (_current_level % 2u) {
case 0:  // zone: gameplayZone1
    // PLAN-12-18: populate _current_area_bank / _current_level_map / width / height
    // from `_zone_gameplayZone1_tilemap` symbol + per-zone metadata. The Gradle
    // task `ConvertZoneTilesetsTask` emits the symbol at buildRom time (Plan 11.1-17
    // Phase C path), so the assignments below currently reference symbols that only
    // resolve when ConvertZoneTilesetsTask runs (Plan 12-18 first buildRom).
    _current_area_bank = 2u;  // Defect-6 fix: literal bank from bankAllocation (option c-prime)
    _current_level_map = _zone_gameplayZone1_tilemap;
    _current_level_width_in_tiles = _zone_gameplayZone1_tilemap_WIDTH;
    _current_level_height = _zone_gameplayZone1_tilemap_HEIGHT * 8u;
    _current_level_width = _zone_gameplayZone1_tilemap_WIDTH * 8u;
    _current_level_non_solid_tile_count = 17u;
    // Plan 12-19 deviation [Rule 1 - Bug]: load this zone's tileset graphics into BG
    // VRAM tile 0+ and write its tilemap to the BG tilemap. Without these calls, the
    // gameplay scene renders whatever tileset+tilemap the prior scene (title) loaded —
    // the gameplay tilemap pointer is set in `_current_level_map` but never pushed
    // to VRAM. Matches the Banks Phase-11 contract (bank1.c title_enter:13-14) and
    // the reference's `set_native_tile_data(0, ..._TILE_COUNT, ..._tiles)` call inside
    // SetupCurrentLevel (level.c:93). The tileset symbol lives in HOME bank
    // (verified via .noi: `___bank__zone_<id>_tileset = 0x0`), so `set_bkg_data` reads
    // it without SWITCH_ROM. The tilemap lives in bank 2u (per `#pragma bank` in
    // the tilemap .c file), so `_bkg_tiles_load_banked` switches to that bank, calls
    // `set_bkg_tiles`, and restores bank 1 — exactly the same helper used by
    // title_enter and nextLevel_enter, so the contract is consistent across all
    // scenes (title, nextLevel card, gameplay).
    set_bkg_data(0u, _zone_gameplayZone1_tileset_count, _zone_gameplayZone1_tileset);
    // Phase 12.9 RC-1 fix (Plan 12.9-08b) — upload THIS zone's authored palette right after
    // its tile data. Without it, gameplay zones inherit the title scene's BG palette RAM
    // (RC-1 palette inversion: sky renders WHITE, ground near-black). W5's SceneVisitor
    // palette fix is blind to this path because the gameplay scene has empty scene.zoneRefs
    // (cEmit("setup_current_level();"), not zone(...)) — RESEARCH Pitfall 7. The
    // _zone_<id>_tileset_PALETTE_COUNT macro + _zone_<id>_tileset_palettes extern + <gb/cgb.h>
    // include are all provided by W4's ConvertZoneTilesetsTask, so no header work is needed.
    // Emitted unconditionally to mirror the set_bkg_data line above and the main() startup
    // _gbkt_default_bg_pal upload — cgb_compatibility() makes set_bkg_palette a no-op on DMG
    // (RESEARCH RC-1d). Mirrors the reference level.c setBKGPalettes-after-tileset-load order.
    set_bkg_palette(0u, _zone_gameplayZone1_tileset_PALETTE_COUNT, _zone_gameplayZone1_tileset_palettes);
    // Phase 12.6 D-08 (debug 12-6-07 CYCLE 3) — windowed submap write replaces full-tilemap write.
    // The previous `_bkg_tiles_load_banked(bank, 0, 0, WIDTH, HEIGHT, tilemap)` wrote the ENTIRE
    // ZONE_WIDTH x ZONE_HEIGHT tilemap (e.g. 60x18 for level-1/level-2) starting at BG (0,0).
    // The GB BG map is 32x32 cells, and `set_bkg_tiles` WRAPS at the 32-cell boundary — so
    // columns 32..59 of the tilemap overwrote columns 0..27 of the BG map. At camera_x=0 the
    // visible window (cols 0..19) showed tilemap[32..51, r] instead of tilemap[0..19, r]:
    // chimera of right-side tiles wrapped to the left, plus untouched leftover cells from the
    // previous level's BG map content (rows the level-N write never reached). Empirically
    // verified via live MCP capture of frame 1208 — bgText row 16 showed level-1's floor
    // pattern (`$!"#$!"#%67676767676`) at the level-2 spawn position.
    //
    // Reference (gbdk/examples/.../platformer_template/src/main.c:43-50): SetupCurrentLevel
    // loads tileset only, then `SetCu