/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * Copyright (c) 2026 Michal Svacha
 */
package io.github.gbkt.gradle.tasks

import io.github.gbkt.gradle.internal.ErrorEnhancer
import io.github.gbkt.gradle.internal.GbdkErrorParser
import io.github.gbkt.gradle.internal.GbdkToolchain
import io.github.gbkt.gradle.internal.SourceMapLoader
import java.io.ByteArrayOutputStream
import java.io.File
import javax.inject.Inject
import org.gradle.api.DefaultTask
import org.gradle.api.GradleException
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.ListProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.*
import org.gradle.process.ExecOperations

/**
 * Task that compiles generated C code to a Game Boy ROM using GBDK.
 *
 * This task invokes GBDK's lcc compiler to produce a .gb ROM file.
 */
@CacheableTask
abstract class CompileRomTask @Inject constructor(private val execOperations: ExecOperations) :
    DefaultTask() {

    /** Path to GBDK installation directory. */
    @get:Input abstract val gbdkHome: Property<String>

    /** Input directory containing C source files to compile (one per bank). */
    @get:InputDirectory
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val cSourceDir: DirectoryProperty

    /** Additional compiler flags for lcc. */
    @get:Input @get:Optional abstract val compilerFlags: ListProperty<String>

    /** Generate debug files (.map, .sym). */
    @get:Input abstract val generateDebugFiles: Property<Boolean>

    /** GBC mode: DISABLED, COMPATIBLE, or ONLY. Adds appropriate -Wm-yc or -Wm-yC flags. */
    @get:Input @get:Optional abstract val gbcMode: Property<String>

    /** Number of RAM banks. Adds -Wl-ya<N> flag when > 0. */
    @get:Input @get:Optional abstract val ramBanks: Property<Int>

    /** Output ROM file. */
    @get:OutputFile abstract val outputRom: RegularFileProperty

    /** Output map file (optional, for debugging). */
    @get:OutputFile @get:Optional abstract val outputMap: RegularFileProperty

    /** Output symbol file (optional, for debugging). */
    @get:OutputFile @get:Optional abstract val outputSym: RegularFileProperty

    init {
        description = "Compile C code to Game Boy ROM using GBDK"
        group = "gbkt"
    }

    @TaskAction
    fun compile() {
        val gbdkDir = File(gbdkHome.get())
        val lcc = GbdkToolchain.getLcc(gbdkDir)
        val sourceDir = cSourceDir.get().asFile
        val romFile = outputRom.get().asFile

        // Find all .c source files: main.c and bank*.c in root, plus sprites/*.c from
        // subdirectories
        val rootSourceFiles =
            sourceDir
                .listFiles { file -> file.extension == "c" }
                ?.sortedBy { file ->
                    // Sort with main.c first, then by bank number
                    when {
                        file.name == "main.c" -> 0
                        file.name.startsWith("bank") -> {
                            file.name.removePrefix("bank").removeSuffix(".c").toIntOrNull() ?: 999
                        }
                        else -> 1000
                    }
                } ?: emptyList()

        // Include sprite asset .c files from subdirectories (generated by ConvertSpritesTask)
        val subDirSourceFiles =
            sourceDir
                .walkTopDown()
                .filter { it.isFile && it.extension == "c" && it.parentFile != sourceDir }
                .sortedBy { it.relativeTo(sourceDir).path }
                .toList()

        val sourceFiles = rootSourceFiles + subDirSourceFiles

        if (sourceFiles.isEmpty()) {
            throw GradleException("No C source files found in ${sourceDir.absolutePath}")
        }

        // Ensure output directory exists
        romFile.parentFile.mkdirs()

        // Build lcc command
        val args = mutableListOf<String>()

        // Standard GBDK flags for Game Boy
        args.add("-Wa-l") // Generate assembly listing
        args.add("-Wl-m") // Generate map file
        args.add("-Wl-j") // Generate symbol file

        // Add user-provided flags
        compilerFlags.getOrElse(emptyList()).forEach { flag -> args.add(flag) }

        // Auto-detect banking requirements from generated source files
        val maxBank = detectMaxBank(sourceFiles)
        if (maxBank > 0) {
            // Compute required number of banks (next power of 2 >= maxBank + 1)
            var numBanks = 2
            while (numBanks <= maxBank) numBanks *= 2
            args.add("-Wm-yo$numBanks") // ROM bank count

            // Determine MBC type from build metadata or derive from configuration
            val mbcType = readMbcType(sourceDir)
            args.add("-Wm-yt$mbcType")
            logger.lifecycle("Banking: $numBanks banks (highest bank: $maxBank), MBC: $mbcType")
        }

        // Add RAM bank flag if configured
        val ramBankCount = ramBanks.getOrElse(0)
        if (ramBankCount > 0) {
            args.add("-Wl-ya$ramBankCount")
            logger.lifecycle("RAM banks: $ramBankCount")
        }

        // Add GBC mode flags — user-set task property takes precedence; fall back to
        // gbkt-build.properties
        val mode =
            if (gbcMode.isPresent) {
                gbcMode.get()
            } else {
                readGbcModeFromMetadata(sourceDir) ?: "DISABLED"
            }
        when (mode.uppercase()) {
            "COMPATIBLE" -> {
                args.add("-Wm-yc") // CGB compatible (works on both DMG and CGB)
                logger.lifecycle("Building with GBC COMPATIBLE mode")
            }
            "ONLY" -> {
                args.add("-Wm-yC") // CGB only (won't run on DMG)
                logger.lifecycle("Building with GBC ONLY mode")
            }
            "DISABLED" -> {
                // No special flags needed for DMG-only mode
            }
            else -> {
                logger.warn("Unknown gbcMode: $mode, using DISABLED")
            }
        }

        // Output file
        args.add("-o")
        args.add(romFile.absolutePath)

        // Add all source files (main.c first, then bank files)
        sourceFiles.forEach { file -> args.add(file.absolutePath) }

        logger.lifecycle("Compiling ROM: ${sourceFiles.size} source files -> ${romFile.name}")
        sourceFiles.forEach { file -> logger.info("  - ${file.name}") }
        logger.info("GBDK: ${gbdkDir.absolutePath}")
        logger.info("Command: ${lcc.absolutePath} ${args.joinToString(" ")}")

        // Capture output for error reporting
        val stdout = ByteArrayOutputStream()
        val stderr = ByteArrayOutputStream()

        try {
            val result =
                execOperations.exec {
                    executable = lcc.absolutePath
                    setArgs(args)
                    standardOutput = stdout
                    errorOutput = stderr
                    isIgnoreExitValue = true

                    // Set GBDK environment
                    environment["GBDK_DIR"] = gbdkDir.absolutePath
                }

            val stdoutText = stdout.toString().trim()
            val stderrText = stderr.toString().trim()

            if (stdoutText.isNotEmpty()) {
                logger.info(stdoutText)
            }

            if (result.exitValue != 0) {
                // Combine stdout and stderr for error parsing
                val combinedOutput =
                    buildString {
                            if (stderrText.isNotEmpty()) appendLine(stderrText)
                            if (stdoutText.isNotEmpty()) appendLine(stdoutText)
                        }
                        .trim()

                // Use main.c as the primary source file for error enhancement
                val mainSourceFile =
                    sourceFiles.firstOrNull { it.name == "main.c" } ?: sourceFiles.first()

                // Try to enhance errors with source map
                val errorMessage =
                    try {
                        enhanceErrorMessage(combinedOutput, mainSourceFile)
                    } catch (e: Exception) {
                        // If enhancement fails, fall back to basic error message
                        logger.warn("Source map error enhancement failed: ${e.message}")
                        logger.warn(
                            "Error locations may not map to Kotlin source. Check generated C code."
                        )
                        logger.info("Full exception: ", e)
                        buildBasicErrorMessage(combinedOutput, mainSourceFile, result.exitValue)
                    }

                throw GradleException(errorMessage)
            }

            // Verify ROM was created
            if (!romFile.exists()) {
                throw GradleException("ROM file was not created: ${romFile.absolutePath}")
            }

            val romSize = romFile.length()
            logger.lifecycle("ROM created: ${romFile.name} (${formatSize(romSize)})")

            // Handle debug files if generated
            if (generateDebugFiles.getOrElse(true)) {
                handleDebugFiles(romFile)
            }
        } catch (e: GradleException) {
            throw e
        } catch (e: Exception) {
            throw GradleException("Failed to execute GBDK compiler: ${e.message}", e)
        }
    }

    /**
     * Read MBC type from build metadata written by GenerateCTask, or derive a sensible default.
     *
     * The metadata file `gbkt-build.properties` contains the cartridge type from the game's DSL
     * config, mapped to the GBDK `-Wm-yt` hex code.
     *
     * When banking is detected but the game config says ROM_ONLY (0x00), the MBC type is
     * automatically upgraded to at least MBC5 since banking requires a memory bank controller.
     */
    private fun readMbcType(sourceDir: File): String {
        val propsFile = File(sourceDir, "gbkt-build.properties")
        if (propsFile.exists()) {
            val props = java.util.Properties()
            propsFile.inputStream().use { props.load(it) }
            val mbcType = props.getProperty("mbcType")
            if (mbcType != null) {
                // Banking requires at least MBC5 — upgrade ROM_ONLY automatically
                if (mbcType == "0x00") {
                    val hasRam = ramBanks.getOrElse(0) > 0
                    val upgraded = if (hasRam) "0x1B" else "0x19"
                    logger.lifecycle("Cartridge upgraded from ROM_ONLY to MBC5 (banking detected)")
                    return upgraded
                }
                return mbcType
            }
        }

        // Fallback: derive from RAM banks configuration
        val hasRam = ramBanks.getOrElse(0) > 0
        return if (hasRam) "0x1B" else "0x19" // MBC5+RAM+Battery or MBC5
    }

    /**
     * Read `gbcMode` from `gbkt-build.properties` as a fallback when the Gradle task property is
     * not explicitly set.
     *
     * This allows DSL-level `config { target(GbcTarget.GBC_COMPATIBLE) }` to automatically produce
     * the correct `-Wm-yc` flag without requiring a separate `gbkt { gbcMode.set("COMPATIBLE") }`
     * in the user's `build.gradle.kts`. The user-level `gbcMode` task property always takes
     * precedence (see the [compile] function).
     *
     * Returns null if the metadata file does not exist or does not contain a `gbcMode` entry.
     */
    private fun readGbcModeFromMetadata(sourceDir: File): String? {
        val propsFile = File(sourceDir, "gbkt-build.properties")
        if (!propsFile.exists()) return null
        val props = java.util.Properties()
        propsFile.inputStream().use { props.load(it) }
        return props.getProperty("gbcMode")
    }

    /** Scan source files for `#pragma bank N` to find the highest bank number used. */
    private fun detectMaxBank(sourceFiles: List<File>): Int {
        val bankPattern = Regex("""#pragma\s+bank\s+(\d+)""")
        var maxBank = 0
        for (file in sourceFiles) {
            file.useLines { lines ->
                for (line in lines) {
                    bankPattern.find(line)?.let { match ->
                        val bank = match.groupValues[1].toIntOrNull() ?: 0
                        if (bank > maxBank) maxBank = bank
                    }
                }
            }
        }
        return maxBank
    }

    private fun handleDebugFiles(romFile: File) {
        val baseName = romFile.nameWithoutExtension
        val romDir = romFile.parentFile

        // GBDK generates .map and .sym files alongside the ROM
        val mapFile = File(romDir, "$baseName.map")
        val symFile = File(romDir, "$baseName.sym")

        if (mapFile.exists()) {
            logger.info("Map file: ${mapFile.name}")
        }

        if (symFile.exists()) {
            logger.info("Symbol file: ${symFile.name}")
        }
    }

    private fun formatSize(bytes: Long): String =
        when {
            bytes < 1024 -> "$bytes bytes"
            bytes < 1024 * 1024 -> "${bytes / 1024} KB"
            else -> "${bytes / (1024 * 1024)} MB"
        }

    /** Enhance error message with source map mappings and suggestions. */
    private fun enhanceErrorMessage(compilerOutput: String, sourceFile: File): String {
        // Parse errors from compiler output
        val errors = GbdkErrorParser.parseErrors(compilerOutput, sourceFile)

        if (errors.isEmpty()) {
            // No parseable errors, return basic message
            return buildBasicErrorMessage(compilerOutput, sourceFile, 1)
        }

        // Load all source maps from the generated directory for multi-file support
        val allMaps = SourceMapLoader.loadAllMaps(sourceFile.parentFile)

        if (allMaps.isEmpty()) {
            // Fall back to single-file source map lookup
            val sourceMapFile = SourceMapLoader.findSourceMapFile(sourceFile)
            val sourceMap = SourceMapLoader.load(sourceMapFile)

            if (sourceMap == null) {
                logger.warn("Source map not found: ${sourceMapFile.name}")
                logger.warn("Error line numbers refer to generated C code, not Kotlin source.")
                logger.info("Expected source map at: ${sourceMapFile.absolutePath}")
            }

            // Enhance errors with single source map (backward-compatible path)
            val enhancedErrors = ErrorEnhancer.enhanceErrors(errors, sourceMap)
            return ErrorEnhancer.formatEnhancedErrors(enhancedErrors, sourceFile)
        }

        logger.info(
            "Loaded ${allMaps.size} source map(s) for error enhancement: ${allMaps.keys.joinToString()}"
        )

        // Enhance errors using per-file source maps (v2 multi-file path)
        val enhancedErrors = ErrorEnhancer.enhanceErrorsMultiFile(errors, allMaps)

        // Format enhanced errors
        return ErrorEnhancer.formatEnhancedErrors(enhancedErrors, sourceFile)
    }

    /** Build a basic error message when enhancement is not possible. */
    private fun buildBasicErrorMessage(
        compilerOutput: String,
        sourceFile: File,
        exitCode: Int,
    ): String {
        return buildString {
            appendLine("GBDK compilation failed (exit code: $exitCode)")
            appendLine()
            appendLine("Compiler output:")
            appendLine(compilerOutput)
            appendLine()
            appendLine("Source file: ${sourceFile.absolutePath}")
            appendLine()
            appendLine("To debug, inspect the generated C code and fix any issues.")
        }
    }
}
