/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * Copyright (c) 2026 Michal Svacha
 */
package io.github.gbkt.gradle.tasks

import javax.inject.Inject
import org.gradle.api.DefaultTask
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.InputFile
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.PathSensitive
import org.gradle.api.tasks.PathSensitivity
import org.gradle.api.tasks.TaskAction
import org.json.JSONObject

/**
 * Generates a type-safe `GameConstants.kt` object from `game_metadata.json`.
 *
 * The generated object contains nested objects for Scenes, Actors, Variables, and Texts, allowing
 * tests to reference game identifiers without magic strings.
 *
 * ## Generated Output
 *
 * ```kotlin
 * // Generated by gbkt — do not edit.
 * package com.example.mygame
 *
 * object GameConstants {
 *     object Scenes {
 *         const val TITLE = "title"
 *     }
 *     object Actors {
 *         const val BALL = "ball"
 *     }
 *     object Variables {
 *         const val BALL_DX = "ballDx"
 *     }
 *     object Texts {
 *         const val PONG = "PONG"
 *     }
 * }
 * ```
 */
@CacheableTask
abstract class GenerateGameConstantsTask @Inject constructor() : DefaultTask() {

    /** Input metadata JSON file produced by `generateC`. */
    @get:InputFile
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val metadataFile: RegularFileProperty

    /** Output Kotlin file for the generated GameConstants object. */
    @get:OutputFile abstract val outputFile: RegularFileProperty

    /** Package name for the generated GameConstants class. */
    @get:Input abstract val packageName: Property<String>

    init {
        description = "Generate type-safe GameConstants object from game metadata"
        group = "gbkt"
    }

    @TaskAction
    fun generate() {
        val metadata = metadataFile.get().asFile
        if (!metadata.exists()) {
            logger.warn(
                "Metadata file not found: ${metadata.absolutePath} — skipping GameConstants generation"
            )
            return
        }

        val json = JSONObject(metadata.readText())
        val pkg = packageName.get()

        // Collect scenes
        val scenes = mutableListOf<Pair<String, String>>() // constantName → originalValue
        val scenesJson = json.optJSONObject("scenes")
        if (scenesJson != null) {
            for (key in scenesJson.keys().asSequence().sorted()) {
                scenes.add(toConstantName(key) to key)
            }
        }

        // Collect actors
        val actors = mutableListOf<Pair<String, String>>()
        val actorsJson = json.optJSONArray("actors")
        if (actorsJson != null) {
            for (i in 0 until actorsJson.length()) {
                val name = actorsJson.getJSONObject(i).getString("name")
                actors.add(toConstantName(name) to name)
            }
        }

        // Collect variables (from metadata JSON variables array + actor position vars +
        // current_scene)
        val variableSet = linkedMapOf<String, String>() // constantName → originalValue
        // System variable
        variableSet[toConstantName("current_scene")] = "current_scene"
        // DSL-declared variables
        val variablesJson = json.optJSONArray("variables")
        if (variablesJson != null) {
            for (i in 0 until variablesJson.length()) {
                val name = variablesJson.getJSONObject(i).getString("name")
                variableSet[toConstantName(name)] = name
            }
        }
        // Actor position variables
        if (actorsJson != null) {
            for (i in 0 until actorsJson.length()) {
                val vars = actorsJson.getJSONObject(i).optJSONObject("vars")
                if (vars != null) {
                    val xVar = vars.optString("x", "")
                    val yVar = vars.optString("y", "")
                    if (xVar.isNotBlank()) variableSet[toConstantName(xVar)] = xVar
                    if (yVar.isNotBlank()) variableSet[toConstantName(yVar)] = yVar
                }
            }
        }

        // Collect texts (skip entries whose text produces an empty constant name,
        // e.g. "##########" or ">" — purely decorative strings with no alphanumeric chars)
        val texts = mutableListOf<Pair<String, String>>()
        val textsJson = json.optJSONArray("texts")
        if (textsJson != null) {
            for (i in 0 until textsJson.length()) {
                val text = textsJson.getString(i)
                val constName = toConstantName(text)
                if (constName.isNotEmpty()) {
                    texts.add(constName to text)
                }
            }
        }

        // Collect controls: per-scene button mappings → {SCENE}_{BUTTON} = "BUTTON"
        val controls = mutableListOf<Pair<String, String>>()
        val controlsJson = json.optJSONObject("controls")
        if (controlsJson != null) {
            for (sceneKey in controlsJson.keys().asSequence().sorted()) {
                val scenePart = toConstantName(sceneKey)
                val mappingsArray = controlsJson.optJSONArray(sceneKey)
                if (mappingsArray != null) {
                    for (i in 0 until mappingsArray.length()) {
                        val mapping = mappingsArray.getJSONObject(i)
                        val button = mapping.getString("button")
                        val constName = "${scenePart}_${toConstantName(button)}"
                        controls.add(constName to button)
                    }
                }
            }
        }

        // Collect transitions: scene navigation edges → {FROM}_TO_{TO} = "from->to"
        val transitions = mutableListOf<Pair<String, String>>()
        val transitionsJson = json.optJSONArray("transitions")
        if (transitionsJson != null) {
            for (i in 0 until transitionsJson.length()) {
                val edge = transitionsJson.getJSONObject(i)
                val from = edge.getString("from")
                val to = edge.getString("to")
                val constName = "${toConstantName(from)}_TO_${toConstantName(to)}"
                transitions.add(constName to "$from->$to")
            }
        }

        // Handle collisions in each group
        val resolvedScenes = resolveCollisions(scenes)
        val resolvedActors = resolveCollisions(actors)
        val resolvedVariables = resolveCollisions(variableSet.entries.map { it.key to it.value })
        val resolvedTexts = resolveCollisions(texts)
        val resolvedControls = resolveCollisions(controls)
        val resolvedTransitions = resolveCollisions(transitions)

        // Generate Kotlin
        val code = buildString {
            appendLine("// Generated by gbkt — do not edit.")
            appendLine("package $pkg")
            appendLine()
            appendLine("object GameConstants {")

            if (resolvedScenes.isNotEmpty()) {
                appendLine()
                appendLine("    object Scenes {")
                for ((constName, value) in resolvedScenes) {
                    appendLine("        const val $constName = \"$value\"")
                }
                appendLine("    }")
            }

            if (resolvedActors.isNotEmpty()) {
                appendLine()
                appendLine("    object Actors {")
                for ((constName, value) in resolvedActors) {
                    appendLine("        const val $constName = \"$value\"")
                }
                appendLine("    }")
            }

            if (resolvedVariables.isNotEmpty()) {
                appendLine()
                appendLine("    object Variables {")
                for ((constName, value) in resolvedVariables) {
                    appendLine("        const val $constName = \"$value\"")
                }
                appendLine("    }")
            }

            if (resolvedTexts.isNotEmpty()) {
                appendLine()
                appendLine("    object Texts {")
                for ((constName, value) in resolvedTexts) {
                    appendLine("        const val $constName = \"${value.replace("\"", "\\\"")}\"")
                }
                appendLine("    }")
            }

            if (resolvedControls.isNotEmpty()) {
                appendLine()
                appendLine("    object Controls {")
                for ((constName, value) in resolvedControls) {
                    appendLine("        const val $constName = \"$value\"")
                }
                appendLine("    }")
            }

            if (resolvedTransitions.isNotEmpty()) {
                appendLine()
                appendLine("    object Transitions {")
                for ((constName, value) in resolvedTransitions) {
                    appendLine("        const val $constName = \"$value\"")
                }
                appendLine("    }")
            }

            appendLine("}")
        }

        val output = outputFile.get().asFile
        output.parentFile.mkdirs()
        output.writeText(code)

        logger.lifecycle("Generated: ${output.absolutePath}")
    }

    companion object {
        /**
         * Convert a string to a SCREAMING_SNAKE_CASE constant name.
         * 1. Replace spaces with `_`
         * 2. Insert `_` before uppercase in camelCase (`ballDx` → `ball_Dx`)
         * 3. Strip non-alphanumeric chars except `_`
         * 4. Collapse repeated `_`, trim trailing `_`
         * 5. Uppercase everything
         * 6. Prefix `_` if starts with digit
         */
        internal fun toConstantName(s: String): String {
            var result = s.replace(" ", "_")
            // Insert _ before uppercase letters in camelCase sequences
            result = result.replace(Regex("([a-z0-9])([A-Z])"), "$1_$2")
            // Strip non-alphanumeric except _
            result = result.replace(Regex("[^A-Za-z0-9_]"), "")
            // Collapse repeated _
            result = result.replace(Regex("_+"), "_")
            // Trim leading/trailing _
            result = result.trim('_')
            // Uppercase
            result = result.uppercase()
            // Prefix _ if starts with digit
            if (result.firstOrNull()?.isDigit() == true) {
                result = "_$result"
            }
            return result
        }

        /** If two strings produce the same constant name, append `_2`, `_3`, etc. */
        internal fun resolveCollisions(
            pairs: List<Pair<String, String>>
        ): List<Pair<String, String>> {
            val seen = mutableMapOf<String, Int>()
            return pairs.map { (constName, value) ->
                val count = seen.getOrDefault(constName, 0)
                seen[constName] = count + 1
                if (count == 0) {
                    constName to value
                } else {
                    "${constName}_${count + 1}" to value
                }
            }
        }
    }
}
