/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * Copyright (c) 2026 Michal Svacha
 */
package io.github.gbkt.analysis

import io.github.gbkt.analysis.config.AnalysisConfig
import io.github.gbkt.core.AssetManifest
import io.github.gbkt.core.constraints.TargetProfile
import io.github.gbkt.core.ir.BankSlot
import io.github.gbkt.core.ir.GameIR
import io.github.gbkt.core.ir.OAMSlot
import io.github.gbkt.core.ir.VRAMRange

/**
 * RAM usage summary computed by the RAM layout analysis pass.
 *
 * @property wramUsed Working RAM bytes consumed (WRAM: 8 KB for DMG, 32 KB for CGB).
 * @property hramUsed High RAM bytes consumed (HRAM: 127 bytes, interrupt-safe).
 * @property sramUsed Save RAM bytes consumed (SRAM: battery-backed, if present).
 */
data class RAMLayout(val wramUsed: Int, val hramUsed: Int, val sramUsed: Int)

/**
 * Inventory of game resources counted during the resource inventory pass.
 *
 * These counts drive the VRAM, OAM, and bank budget checks in subsequent passes.
 *
 * @property totalActors Total actor definitions in the game.
 * @property totalScenes Total scene definitions in the game.
 * @property totalVariables Total global variable definitions.
 * @property totalAssets Total asset references declared in the game.
 * @property spriteTileCounts Per-actor tile count: actorId -> tile count (width/8 * height/8).
 * @property variableBytes Total WRAM bytes required for all variables (U8/I8=1, U16/I16=2).
 * @property collectionBytes Total WRAM bytes for all collection instances (hash tables, pools, ring
 *   buffers, fixed slots). Computed by [ResourceInventoryPass] from the [GameIR] collection fields
 *   added in Plan 06-06. Non-zero when any collections are declared in the game.
 * @property perSceneActorCounts Per-scene actor count: sceneId -> number of actorIds in that scene.
 */
data class ResourceInventory(
    val totalActors: Int = 0,
    val totalScenes: Int = 0,
    val totalVariables: Int = 0,
    val totalAssets: Int = 0,
    val spriteTileCounts: Map<String, Int> = emptyMap(),
    val variableBytes: Int = 0,
    val collectionBytes: Int = 0,
    val perSceneActorCounts: Map<String, Int> = emptyMap(),
)

/**
 * Immutable snapshot of accumulated analysis state passed between [AnalysisPass] instances.
 *
 * Each pass receives the context from the previous pass, computes new annotations or diagnostics,
 * and returns an updated copy via [withDiagnostics], [withBankAssignment], or [copy]. The original
 * context is never mutated.
 *
 * @property game The root game IR being analyzed.
 * @property profile Hardware constraints for the target platform.
 * @property config Configurable thresholds and MBC bank limits.
 * @property bankAssignments Mapping of game-element IDs to assigned ROM bank slots.
 * @property vramAssignments Mapping of tileset/sprite IDs to VRAM tile ranges.
 * @property oamAssignments Mapping of actor IDs to OAM sprite slots.
 * @property ramLayout RAM usage summary computed by the RAM layout pass (null until computed).
 * @property inventory Resource inventory counts (null until the inventory pass runs).
 * @property diagnostics All diagnostics accumulated so far from preceding passes.
 * @property budgetReport ASCII table budget report generated by [BudgetAuditPass] (null until the
 *   audit pass runs). Printed to the terminal during every build per locked developer UX decision.
 * @property assetManifest Optional asset manifest produced by the asset pipeline. When non-null,
 *   analysis passes can read actual tile counts and asset metadata instead of falling back to
 *   heuristic estimates. Passes such as [VRAMLayoutPass] use this for accurate BG tile estimation.
 * @property optimizationReport Accumulated per-pass optimization summaries. IR-level optimization
 *   passes append their [PassOptimizationSummary] here. Written to disk by [BudgetAuditPass].
 * @property outputDirectory Build output directory. When non-null, [BudgetAuditPass] writes
 *   `optimization-report.json` here. Wired from GBDKPipelineV2 or set in tests.
 */
data class PassContext(
    val game: GameIR,
    val profile: TargetProfile,
    val config: AnalysisConfig,
    val bankAssignments: Map<String, BankSlot> = emptyMap(),
    val vramAssignments: Map<String, VRAMRange> = emptyMap(),
    val oamAssignments: Map<String, OAMSlot> = emptyMap(),
    val ramLayout: RAMLayout? = null,
    val inventory: ResourceInventory? = null,
    val diagnostics: List<Diagnostic> = emptyList(),
    val budgetReport: String? = null,
    val assetManifest: AssetManifest? = null,
    val optimizationReport: OptimizationReport = OptimizationReport(),
    val outputDirectory: java.io.File? = null,
) {
    /**
     * Returns a copy of this context with [newDiagnostics] appended to the existing list. The
     * original context is unchanged.
     */
    fun withDiagnostics(newDiagnostics: List<Diagnostic>): PassContext =
        copy(diagnostics = diagnostics + newDiagnostics)

    /**
     * Returns a copy of this context with a bank assignment added for [id]. Existing assignments
     * are preserved; if [id] was already assigned, the new [slot] replaces it.
     */
    fun withBankAssignment(id: String, slot: BankSlot): PassContext =
        copy(bankAssignments = bankAssignments + (id to slot))
}
