// Generated by gbkt
#pragma bank 1

#include <stdio.h>
#include <gbdk/console.h>
#include "game.h"

// Scene: win
void win_enter(void) BANKED {
    HIDE_SPRITES;
    cls();
    play_sound_winSfx();
    {
        gotoxy(6u, 6u);
        printf("YOU WIN!");
    }
    {
        gotoxy(5u, 10u);
        printf("PRESS START");
    }
}

void win_frame(void) BANKED {
    update_movement_player();
    if (button_pressed(J_START)) {
        navigate_to_scene(SCENE_TITLE);
    }
}

// Scene: gameplay
void gameplay_enter(void) BANKED {
    SHOW_SPRITES;
    cls();
    {
        _player_x = 20u;
        _player_y = 104u;
    }
    _lives = 3u;
}

void gameplay_frame(void) BANKED {
    update_movement_player();
    if (button_held(J_LEFT)) {
        {
            _player_x += -2;
        }
    }
    if (button_held(J_RIGHT)) {
        {
            _player_x += 2u;
        }
    }
    if (button_pressed(J_A)) {
        play_sound_jumpSfx();
    }
    if (_player_y > 136u) {
        _lives -= 1u;
        play_sound_landSfx();
        {
            _player_x = 20u;
            _player_y = 104u;
        }
        if (_lives == 0u) {
            navigate_to_scene(SCENE_TITLE);
        }
    }
    if (_player_x >= 112u) {
        if (_player_x < 128u) {
            if (_player_y >= 24u) {
                if (_player_y < 56u) {
                    navigate_to_scene(SCENE_WIN);
                }
            }
        }
    }
}

// Scene: title
void title_enter(void) BANKED {
    HIDE_SPRITES;
    cls();
    {
        gotoxy(3u, 6u);
        printf("PLATFORMER GBC");
    }
    {
        gotoxy(5u, 10u);
        printf("PRESS START");
    }
    {
        gotoxy(6u, 13u);
        printf("LIVES: 3");
    }
}

void title_frame(void) BANKED {
    update_movement_player();
    if (button_pressed(J_START)) {
        navigate_to_scene(SCENE_GAMEPLAY);
    }
}
