//AUTOGENERATED FILE FROM png2asset
// Conversion args: /player-character-gbapduck-sprites.png -o /player_character_gbapduck_sprites.c -spr8x16 -px 12 -py 6 -sw 24 -sh 32 -noflip

#ifndef METASPRITE_player_character_gbapduck_sprites_H
#define METASPRITE_player_character_gbapduck_sprites_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define player_character_gbapduck_sprites_TILE_ORIGIN 0
#define player_character_gbapduck_sprites_TILE_W 8
#define player_character_gbapduck_sprites_TILE_H 16
#define player_character_gbapduck_sprites_WIDTH 24
#define player_character_gbapduck_sprites_HEIGHT 32
#define player_character_gbapduck_sprites_TILE_COUNT 124
#define player_character_gbapduck_sprites_PALETTE_COUNT 1
#define player_character_gbapduck_sprites_COLORS_PER_PALETTE 4
#define player_character_gbapduck_sprites_TOTAL_COLORS 4
#define player_character_gbapduck_sprites_PIVOT_X 12
#define player_character_gbapduck_sprites_PIVOT_Y 6
#define player_character_gbapduck_sprites_PIVOT_W 24
#define player_character_gbapduck_sprites_PIVOT_H 32
extern const metasprite_t* const player_character_gbapduck_sprites_metasprites[12];

BANKREF_EXTERN(player_character_gbapduck_sprites)

extern const palette_color_t player_character_gbapduck_sprites_palettes[4];
extern const uint8_t player_character_gbapduck_sprites_tiles[1984];

#endif
