/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * Copyright (c) 2026 Michal Svacha
 */
package io.github.gbkt.gradle.tasks

// =============================================================================
// WR-01 REGRESSION TEST — injectBankPragma uses System.lineSeparator()
//
// Before the fix: outputC.writeText(lines.joinToString("\n")) always wrote
// Unix LF regardless of host OS, causing CRLF→LF file rewrite on every
// task invocation on Windows (dirty output file, potential lcc conflict).
//
// After the fix: outputC.writeText(lines.joinToString(System.lineSeparator()))
// preserves host line endings.
//
// Test strategy (platform-agnostic):
//   1. Stage a .c file whose lines are joined with System.lineSeparator()
//      (the authoritative separator for the current host).
//   2. Call injectBankPragma() on that file.
//   3. Assert that the resulting file uses only System.lineSeparator() as its
//      line separator (no bare '\n' that is not part of the separator).
//
// This test works correctly on both Unix (sep="\n", trivially satisfied) and
// Windows (sep="\r\n", proves no CRLF→LF stripping). The test is a
// regression guard — it fails if the hard-coded "\n" is re-introduced.
// =============================================================================

import java.io.File
import kotlin.test.assertFalse
import kotlin.test.assertTrue
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.io.TempDir

class ConvertSpritesTaskPragmaTest {

    @TempDir lateinit var tempDir: File

    // -------------------------------------------------------------------------
    // Test 1 — WR-01: injectBankPragma preserves System.lineSeparator() endings
    //
    // Stages a .c file with System.lineSeparator()-joined lines, calls
    // injectBankPragma(), and verifies the output file does NOT contain any
    // bare '\n' that is not part of System.lineSeparator().
    // On Windows: this proves no CRLF→LF stripping occurred.
    // On Unix:    both "\n" and System.lineSeparator() are the same; the test
    //             documents the required behavior and catches regressions.
    // -------------------------------------------------------------------------
    @Test
    fun `injectBankPragma preserves host line separators (WR-01)`() {
        val sep = System.lineSeparator()

        // Stage a minimal .c file with host-native line endings
        // (simulates what ConvertZoneTilesetsTask or png2asset produces)
        val outputC = File(tempDir, "sprites/player.c")
        outputC.parentFile.mkdirs()
        val originalLines =
            listOf(
                "/* Auto-generated by png2asset */",
                "#include <stdint.h>",
                "const uint8_t player_tiles[] = {0x00, 0xFF};",
                "const unsigned int player_tiles_size = 2;",
            )
        outputC.writeText(originalLines.joinToString(sep))

        // Act: inject #pragma bank 1
        injectBankPragma(outputC, 1)

        // Read back as raw bytes and verify no bare '\n' outside sep
        val rawBytes = outputC.readBytes()
        val rawContent = String(rawBytes, Charsets.ISO_8859_1)

        if (sep == "\n") {
            // Unix: System.lineSeparator() == "\n" — just verify pragma was injected
            assertTrue(
                rawContent.contains("#pragma bank 1"),
                "WR-01: pragma must be injected; got:\n$rawContent",
            )
        } else {
            // Windows and other CRLF systems: bare '\n' must not appear without '\r'
            // Check that every '\n' in the output is preceded by '\r'
            val bareNewlineCount = rawContent.windowed(2).count { it == "\r\n" }
            val totalNewlines = rawContent.count { it == '\n' }
            assertTrue(
                bareNewlineCount == totalNewlines,
                "WR-01: all newlines must be part of CRLF (System.lineSeparator()).\n" +
                    "Total newlines=$totalNewlines, CRLF pairs=$bareNewlineCount — bare LF detected.\n" +
                    "Raw content:\n$rawContent",
            )
            // Also verify pragma was injected
            assertTrue(
                rawContent.contains("#pragma bank 1"),
                "WR-01: pragma must be injected; got:\n$rawContent",
            )
        }
    }

    // -------------------------------------------------------------------------
    // Test 2 — WR-01: injectBankPragma is idempotent
    //
    // Calling injectBankPragma() twice must NOT inject a second #pragma.
    // This tests the idempotency guard: "if (content.contains(pragmaLine)) return"
    // -------------------------------------------------------------------------
    @Test
    fun `injectBankPragma is idempotent (calling twice does not double-inject)`() {
        val sep = System.lineSeparator()
        val outputC = File(tempDir, "sprites/paddle.c")
        outputC.parentFile.mkdirs()
        val originalLines =
            listOf(
                "/* Auto-generated */",
                "#include <stdint.h>",
                "const uint8_t paddle_tiles[] = {0x00};",
            )
        outputC.writeText(originalLines.joinToString(sep))

        // Call twice
        injectBankPragma(outputC, 1)
        injectBankPragma(outputC, 1)

        val content = outputC.readText()
        val pragmaCount = content.lines().count { it.trim() == "#pragma bank 1" }
        assertTrue(
            pragmaCount == 1,
            "WR-01 idempotency: #pragma bank 1 must appear exactly once; found $pragmaCount times",
        )
        assertFalse(
            pragmaCount > 1,
            "WR-01 idempotency: double-injection detected — injectBankPragma is not idempotent",
        )
    }
}
