/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * Copyright (c) 2026 Michal Svacha
 */
package io.github.gbkt.gradle.tasks

import io.github.gbkt.gradle.internal.GbdkToolchain
import java.awt.image.BufferedImage
import java.awt.image.IndexColorModel
import java.io.File
import javax.imageio.ImageIO
import org.gradle.testfixtures.ProjectBuilder
import org.junit.jupiter.api.Assertions.assertFalse
import org.junit.jupiter.api.Assertions.assertNotNull
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.io.TempDir

// =============================================================================
// Phase 13.7 Plan 05 (Req 4) — Palette polarity WARNING emission tests.
//
// These tests verify the non-fatal WARNING logic wired into BOTH convert tasks:
//
//   BG path (ConvertZoneTilesetsTask):
//     - parsePaletteRgb555Values + checkPalettePolarity → warn if inverted
//   OBJ path (ConvertSpritesTask):
//     - parsePaletteRgb555Values + checkPalettePolarity → warn if inverted
//
// Tests:
//   Test 1: parsePaletteRgb555Values parses C file correctly
//   Test 2: parsePaletteRgb555Values parses C file correctly
//   Test 3: BG WARNING condition — inverted C output triggers checkPalettePolarity=true
//   Test 4: BG WARNING condition — corrected C output triggers checkPalettePolarity=false
//   Test 5: OBJ WARNING condition — inverted C output triggers checkPalettePolarity=true
//   Test 6: OBJ WARNING condition — corrected C output triggers checkPalettePolarity=false
//   Test 7: ConvertZoneTilesetsTask completes without throw on inverted fixture (skip-guarded)
//   Test 8: ConvertSpritesTask completes without throw on inverted fixture (skip-guarded)
//
// The "exactly one warn per inverted asset" and "zero warns on corrected" contracts are
// proven through Tests 3-6 which test the same conditional logic that drives the
// logger.warn call in each task. A checkPalettePolarity return of true = one warn would
// be emitted; false = zero warns would be emitted.
//
// Tests 7-8 prove the non-fatal contract: the task does not throw on an inverted palette
// (build EXIT 0 equivalent). Both tests are skip-guarded for png2asset.
// =============================================================================

class PalettePolarityWarningTest {

    @TempDir lateinit var tempDir: File

    // -------------------------------------------------------------------------
    // Test 1: parsePaletteRgb555Values correctly parses a C palette array in RGB8() form
    //         (the real png2asset output format for indexed BG tilesets)
    // -------------------------------------------------------------------------

    @Test
    fun `parsePaletteRgb555Values parses RGB8 macro palette_color_t array from C file`() {
        val cFile = File(tempDir, "test_tileset.c")
        // Write a synthetic C file with RGB8(r,g,b) format — the actual png2asset output shape.
        // Ascending luminance: black < dark < light < white
        cFile.writeText(
            """
            /* Generated by png2asset */
            const palette_color_t _zone_test_tileset_palettes[4] = {
            	RGB8(  0,  0,  0), RGB8( 64, 64, 64), RGB8(192,192,192), RGB8(255,255,255)
            	};
            """
                .trimIndent()
        )

        val symbol = "_zone_test_tileset_palettes"
        val values = parsePaletteRgb555Values(cFile, symbol)
        assertNotNull(
            values,
            "parsePaletteRgb555Values must parse an RGB8-format palette_color_t array",
        )
        assertTrue(values!!.isNotEmpty(), "Parsed values must not be empty")
        assertTrue(
            values.size == 4,
            "Must parse 4 palette entries from RGB8 form; got ${values.size}: $values",
        )
        // Black (0,0,0) → RGB555 = 0
        assertTrue(values[0] == 0, "First entry RGB8(0,0,0) must map to RGB555=0; got ${values[0]}")
        // White (255,255,255) → RGB555 = 0x7FFF = 32767
        assertTrue(
            values[3] == 0x7FFF,
            "Last entry RGB8(255,255,255) must map to RGB555=0x7FFF; got ${values[3]}",
        )
    }

    // -------------------------------------------------------------------------
    // Test 2: parsePaletteRgb555Values correctly parses a sprite palette array (RGB8 format)
    // -------------------------------------------------------------------------

    @Test
    fun `parsePaletteRgb555Values parses RGB8 macro palette_color_t array from sprite C file`() {
        val cFile = File(tempDir, "player.c")
        // Real png2asset format with RGB8 macros
        cFile.writeText(
            """
            /* Generated by png2asset */
            const palette_color_t player_palettes[4] = {
            	RGB8(255,128, 64), RGB8(  0,  0,  0), RGB8(248,248,248), RGB8(168,168,168)
            	};
            """
                .trimIndent()
        )

        val values = parsePaletteRgb555Values(cFile, "player_palettes")
        assertNotNull(values, "parsePaletteRgb555Values must parse an RGB8-format sprite palette")
        assertTrue(values!!.size == 4, "Must parse 4 entries from RGB8 form; got ${values.size}")
    }

    // -------------------------------------------------------------------------
    // Test 3: BG WARNING condition — inverted emitted palette triggers polarity check
    //
    // Source PNG: ascending luminance PLTE (black → dark → light → white)
    // Emitted C: RGB8 values in DESCENDING luminance order (white → light → dark → black)
    // Expected: checkPalettePolarity returns true → exactly one warn would be emitted
    // -------------------------------------------------------------------------

    @Test
    fun `BG polarity check triggers for inverted emitted palette (exactly one warn condition)`() {
        // Source PNG with ascending-luminance PLTE: black < dark-gray < light-gray < white
        val sourcePng = writeAscendingLumIndexedPng("world1-tileset.png")

        // Emitted C with DESCENDING luminance order (inverted relative to PLTE)
        // Uses RGB8(r,g,b) format — the actual png2asset output format.
        val outputC = File(tempDir, "_zone_test_tileset.c")
        val invertedSymbol = "_zone_test_tileset_palettes"
        outputC.writeText(
            """
            const palette_color_t ${invertedSymbol}[4] = {
            	RGB8(255,255,255), RGB8(192,192,192), RGB8( 64, 64, 64), RGB8(  0,  0,  0)
            	};
            """
                .trimIndent()
        )

        // Simulate the BG WARNING logic: parse → checkPalettePolarity
        val values = parsePaletteRgb555Values(outputC, invertedSymbol)
        assertNotNull(values, "parsePaletteRgb555Values must parse the inverted RGB8 palette array")
        val polarity = checkPalettePolarity(sourcePng, values!!)
        assertTrue(
            polarity,
            "BG inverted fixture: checkPalettePolarity must return true → one warn would be emitted. " +
                "values=$values",
        )
    }

    // -------------------------------------------------------------------------
    // Test 4: BG WARNING condition — corrected emitted palette produces zero warns
    //
    // Source PNG: ascending luminance PLTE (black → dark → light → white)
    // Emitted C: RGB8 values in ASCENDING luminance order (matching PLTE — correct)
    // Expected: checkPalettePolarity returns false → zero warns emitted
    // -------------------------------------------------------------------------

    @Test
    fun `BG polarity check does not trigger for corrected ascending emitted palette (zero warns)`() {
        // Source PNG with ascending-luminance PLTE
        val sourcePng = writeAscendingLumIndexedPng("world1-tileset-corrected.png")

        // Emitted C with ASCENDING luminance order (matching PLTE — correct)
        val outputC = File(tempDir, "_zone_test_corrected.c")
        val correctSymbol = "_zone_test_corrected_palettes"
        outputC.writeText(
            """
            const palette_color_t ${correctSymbol}[4] = {
            	RGB8(  0,  0,  0), RGB8( 64, 64, 64), RGB8(192,192,192), RGB8(255,255,255)
            	};
            """
                .trimIndent()
        )

        val values = parsePaletteRgb555Values(outputC, correctSymbol)
        assertNotNull(
            values,
            "parsePaletteRgb555Values must parse the corrected RGB8 palette array",
        )
        val polarity = checkPalettePolarity(sourcePng, values!!)
        assertFalse(
            polarity,
            "BG corrected fixture: checkPalettePolarity must return false → zero warns emitted. " +
                "values=$values",
        )
    }

    // -------------------------------------------------------------------------
    // Test 5: OBJ WARNING condition — inverted emitted sprite palette triggers polarity check
    //
    // Source PNG: ascending luminance PLTE
    // Emitted C: RGB8 values in DESCENDING luminance order (inverted)
    // Expected: checkPalettePolarity returns true → exactly one warn would be emitted
    // -------------------------------------------------------------------------

    @Test
    fun `OBJ polarity check triggers for inverted emitted sprite palette (exactly one warn condition)`() {
        val sourcePng = writeAscendingLumIndexedPng("player.png")

        val outputC = File(tempDir, "player.c")
        val spriteSymbol = "player_palettes"
        outputC.writeText(
            """
            const palette_color_t ${spriteSymbol}[4] = {
            	RGB8(255,255,255), RGB8(192,192,192), RGB8( 64, 64, 64), RGB8(  0,  0,  0)
            	};
            """
                .trimIndent()
        )

        val values = parsePaletteRgb555Values(outputC, spriteSymbol)
        assertNotNull(
            values,
            "parsePaletteRgb555Values must parse the inverted RGB8 sprite palette",
        )
        val polarity = checkPalettePolarity(sourcePng, values!!)
        assertTrue(
            polarity,
            "OBJ inverted fixture: checkPalettePolarity must return true → one warn would be emitted. " +
                "values=$values",
        )
    }

    // -------------------------------------------------------------------------
    // Test 6: OBJ WARNING condition — corrected emitted sprite palette produces zero warns
    // -------------------------------------------------------------------------

    @Test
    fun `OBJ polarity check does not trigger for corrected ascending sprite palette (zero warns)`() {
        val sourcePng = writeAscendingLumIndexedPng("player-corrected.png")

        val outputC = File(tempDir, "player-corrected.c")
        val spriteSymbol = "player_corrected_palettes"
        outputC.writeText(
            """
            const palette_color_t ${spriteSymbol}[4] = {
            	RGB8(  0,  0,  0), RGB8( 64, 64, 64), RGB8(192,192,192), RGB8(255,255,255)
            	};
            """
                .trimIndent()
        )

        val values = parsePaletteRgb555Values(outputC, spriteSymbol)
        assertNotNull(
            values,
            "parsePaletteRgb555Values must parse the corrected RGB8 sprite palette",
        )
        val polarity = checkPalettePolarity(sourcePng, values!!)
        assertFalse(
            polarity,
            "OBJ corrected fixture: checkPalettePolarity must return false → zero warns emitted. " +
                "values=$values",
        )
    }

    // -------------------------------------------------------------------------
    // Test 7: ConvertZoneTilesetsTask does NOT throw on an inverted palette PNG
    //         (non-fatal contract; build EXIT 0 equivalent)
    //
    // Skip-guarded: returns if png2asset is not available.
    // Uses a real indexed PNG fixture with descending luminance PLTE.
    // Asserts: convertZoneTilesets() completes without throwing.
    // -------------------------------------------------------------------------

    @Test
    fun `ConvertZoneTilesetsTask does not throw when BG palette is inverted (non-fatal)`() {
        val gbdkDir =
            try {
                GbdkToolchain.find(null)
            } catch (_: Exception) {
                return
            }
        val png2asset = GbdkToolchain.getPng2asset(gbdkDir)
        if (!png2asset.exists()) return

        // Use the real world1-tileset.png as the fixture (if available in this checkout).
        // It is a real indexed PNG — the polarity check will run against it.
        val realPng = findPlatformerTemplatePng("world1-tileset.png") ?: return

        val assetDir = File(tempDir, "res").apply { mkdirs() }
        val gfxDir = File(assetDir, "graphics").apply { mkdirs() }
        realPng.copyTo(File(gfxDir, "world1-tileset.png"), overwrite = true)

        val metadataFile = File(tempDir, "game_metadata.json")
        metadataFile.writeText(
            """
            {
              "zoneTilesets": [
                {
                  "id": "world1Area1Zone",
                  "path": "graphics/world1-tileset.png",
                  "sanitizedSymbol": "world1Area1Zone",
                  "mapWidth": 60,
                  "mapHeight": 32,
                  "bank": 2
                }
              ]
            }
            """
                .trimIndent()
        )

        val cSourceDir = File(tempDir, "out").apply { mkdirs() }
        val project = ProjectBuilder.builder().withProjectDir(tempDir).build()
        val task =
            project.tasks
                .register("convertZoneTilesetsPolarity", ConvertZoneTilesetsTask::class.java) {
                    gbdkHome.set(gbdkDir.absolutePath)
                    assetDirectory.set(assetDir)
                    this.metadataFile.set(metadataFile)
                    this.cSourceDir.set(cSourceDir)
                }
                .get()

        // Must NOT throw — the polarity WARNING is non-fatal (warn-not-fail).
        // Any GradleException or other exception would indicate a regression.
        var threw: Throwable? = null
        try {
            task.convertZoneTilesets()
        } catch (e: Throwable) {
            threw = e
        }

        assertTrue(
            threw == null,
            "ConvertZoneTilesetsTask must not throw for an inverted palette PNG " +
                "(non-fatal WARNING contract). Exception: $threw",
        )

        // Secondary: output .c was produced (task ran to completion)
        val outC = File(cSourceDir, "_zone_world1Area1Zone_tileset.c")
        assertTrue(
            outC.exists(),
            "Output .c must exist — task must run to completion even if palette is inverted. " +
                "path: ${outC.absolutePath}",
        )
    }

    // -------------------------------------------------------------------------
    // Test 8: ConvertSpritesTask does NOT throw on an inverted palette PNG
    //         (non-fatal contract; build EXIT 0 equivalent)
    //
    // Skip-guarded: returns if png2asset is not available or elephant.png absent.
    // Uses elephant.png from metasprites example (real indexed PNG).
    // Asserts: convertSprites() completes without throwing.
    // -------------------------------------------------------------------------

    @Test
    fun `ConvertSpritesTask does not throw when OBJ palette is inverted (non-fatal)`() {
        val gbdkDir =
            try {
                GbdkToolchain.find(null)
            } catch (_: Exception) {
                return
            }
        val png2asset = GbdkToolchain.getPng2asset(gbdkDir)
        if (!png2asset.exists()) return

        val elephantSrc = findElephantPng() ?: return

        val assetDir = File(tempDir, "res").apply { mkdirs() }
        val spritesDir = File(assetDir, "sprites").apply { mkdirs() }
        elephantSrc.copyTo(File(spritesDir, "elephant.png"), overwrite = true)

        val metadataFile = File(tempDir, "game_metadata.json")
        metadataFile.writeText(
            """
            {
              "sprites": [
                {
                  "id": "elephant",
                  "spritePath": "sprites/elephant.png",
                  "spriteMode": "SPR8x8",
                  "pivotX": 32,
                  "pivotY": 24,
                  "frameWidth": 64,
                  "frameHeight": 48,
                  "mirrorDedup": true,
                  "isMetasprite": true,
                  "includePath": "sprites/elephant.h",
                  "frameCount": 5
                }
              ]
            }
            """
                .trimIndent()
        )

        val outputDir = File(tempDir, "out").apply { mkdirs() }
        val project = ProjectBuilder.builder().withProjectDir(tempDir).build()
        val task =
            project.tasks
                .register("convertSpritesPolarity", ConvertSpritesTask::class.java) {
                    gbdkHome.set(gbdkDir.absolutePath)
                    assetDirectory.set(assetDir)
                    this.metadataFile.set(metadataFile)
                    cSourceDir.set(outputDir)
                    strictTransparency.set(false)
                }
                .get()

        // Must NOT throw — the polarity WARNING is non-fatal.
        var threw: Throwable? = null
        try {
            task.convertSprites()
        } catch (e: Throwable) {
            threw = e
        }

        assertTrue(
            threw == null,
            "ConvertSpritesTask must not throw for an inverted palette PNG " +
                "(non-fatal WARNING contract). Exception: $threw",
        )

        // Secondary: output .c was produced
        val outC = File(outputDir, "sprites/elephant.c")
        assertTrue(
            outC.exists(),
            "Output elephant.c must exist — task must run to completion. " +
                "path: ${outC.absolutePath}",
        )
    }

    // -------------------------------------------------------------------------
    // Fixture helpers
    // -------------------------------------------------------------------------

    /**
     * Writes an indexed PNG with 4 entries in ascending luminance order (PLTE): Index 0: black
     * RGB(0,0,0) lum=0 Index 1: dark RGB(64,64,64) lum=64 Index 2: light RGB(192,192,192) lum=192
     * Index 3: white RGB(255,255,255) lum=255
     *
     * This is the "non-inverted source" fixture. An emitted palette that is the strict reverse of
     * this PLTE will trigger checkPalettePolarity → true.
     */
    private fun writeAscendingLumIndexedPng(name: String): File {
        val reds = byteArrayOf(0, 64, 192.toByte(), 255.toByte())
        val greens = byteArrayOf(0, 64, 192.toByte(), 255.toByte())
        val blues = byteArrayOf(0, 64, 192.toByte(), 255.toByte())
        val alphas = ByteArray(4) { 0xFF.toByte() }
        val cm = IndexColorModel(8, 4, reds, greens, blues, alphas)
        val img = BufferedImage(4, 1, BufferedImage.TYPE_BYTE_INDEXED, cm)
        val raster = img.raster
        for (x in 0 until 4) {
            raster.setSample(x, 0, 0, x)
        }
        val target = File(tempDir, name)
        ImageIO.write(img, "PNG", target)
        return target
    }

    /**
     * Converts 8-bit RGB to GBC RGB555 packed integer. Layout: (b5 shl 10) or (g5 shl 5) or r5,
     * where r5 = r8*31/255.
     */
    private fun rgb888ToRgb555(r8: Int, g8: Int, b8: Int): Int {
        val r5 = (r8 * 31) / 255
        val g5 = (g8 * 31) / 255
        val b5 = (b8 * 31) / 255
        return (b5 shl 10) or (g5 shl 5) or r5
    }

    /**
     * Find a PNG in the platformer-template example directory. Mirrors the pattern in
     * World1TilesetGrassEncodingTest.
     */
    private fun findPlatformerTemplatePng(filename: String): File? {
        val rel = "gbkt-examples/platformer-template/res/graphics/$filename"
        var dir: File? = File("").absoluteFile
        repeat(6) {
            val candidate = dir?.let { File(it, rel) }
            if (candidate != null && candidate.isFile) return candidate
            dir = dir?.parentFile
        }
        return null
    }

    /**
     * Find elephant.png from the metasprites example directory via walk-up search. Mirrors
     * [findPlatformerTemplatePng] — starts at the process working directory and walks up to 6
     * parent directories looking for the asset. Returns null when the asset is genuinely absent
     * (e.g. a shallow checkout without the example subproject). The test returns early on null — it
     * does NOT fail.
     */
    private fun findElephantPng(): File? {
        val rel = "gbkt-examples/metasprites/res/sprites/elephant.png"
        var dir: File? = File("").absoluteFile
        repeat(6) {
            val candidate = dir?.let { File(it, rel) }
            if (candidate != null && candidate.isFile) return candidate
            dir = dir?.parentFile
        }
        return null
    }
}
